// Reviewed UI strings from the September 2026 mobile issue audit.
export const auditUiText: Record<'Hindi' | 'Punjabi', Record<string, string>> = {
  "Hindi": {
    "Dealer Wallet": "डीलर वॉलेट",
    "Login or signup to view your bonus wallet, payouts and linked account details.": "अपना बोनस वॉलेट, भुगतान और जुड़े खाते की जानकारी देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Dealer Notifications": "डीलर सूचनाएँ",
    "Login or signup to see dealer alerts, updates and account messages.": "डीलर सूचनाएँ, अपडेट और खाते के संदेश देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Dealer Profile": "डीलर प्रोफ़ाइल",
    "Login or signup to manage your dealer profile, password and app preferences.": "अपनी डीलर प्रोफ़ाइल, पासवर्ड और ऐप की पसंद प्रबंधित करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Associated Electricians": "जुड़े इलेक्ट्रीशियन",
    "Login or signup to manage your electrician network and dealer relationships.": "अपने इलेक्ट्रीशियन नेटवर्क और डीलर संबंध प्रबंधित करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to access your connected electricians and outreach tools.": "अपने जुड़े इलेक्ट्रीशियन और संपर्क साधनों का उपयोग करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Dealer Tier": "डीलर स्तर",
    "Login or signup to check your dealer growth level and next tier progress.": "अपना डीलर स्तर और अगले स्तर की प्रगति देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to request dealer bonus payouts and review linked bank details.": "डीलर बोनस भुगतान का अनुरोध करने और जुड़ा बैंक खाता देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Transfers": "ट्रांसफर",
    "Login or signup to access dealer transfer and linked wallet actions.": "डीलर ट्रांसफर और जुड़े वॉलेट के कार्यों के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to view your bonus earnings and withdrawal requests.": "अपनी बोनस कमाई और निकासी अनुरोध देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to see your wallet balance, points and activity.": "अपना वॉलेट बैलेंस, पॉइंट और गतिविधि देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to see your latest alerts, offers and updates.": "नवीनतम सूचनाएँ, ऑफ़र और अपडेट देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to manage your profile, password and personal settings.": "अपनी प्रोफ़ाइल, पासवर्ड और निजी सेटिंग प्रबंधित करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to redeem rewards and explore member-only benefits.": "रिवॉर्ड लेने और सदस्यों के लाभ देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to request bank payouts and review your linked account details.": "बैंक भुगतान का अनुरोध करने और जुड़े खाते की जानकारी देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to access point transfer and wallet actions.": "पॉइंट ट्रांसफर और वॉलेट के कार्यों के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to view your points, rewards and account-linked wallet details.": "अपने पॉइंट, रिवॉर्ड और खाते से जुड़े वॉलेट की जानकारी के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to read counter boy alerts, offers and updates.": "काउंटर बॉय की सूचनाएँ, ऑफ़र और अपडेट पढ़ने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to manage your profile, password and app preferences.": "अपनी प्रोफ़ाइल, पासवर्ड और ऐप की पसंद प्रबंधित करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to redeem gifts and explore rewards with your earned points.": "कमाए हुए पॉइंट से उपहार लेने और रिवॉर्ड देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to access wallet-linked transfer actions.": "वॉलेट से जुड़े ट्रांसफर कार्यों के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to see your points, rewards history and linked account details.": "अपने पॉइंट, रिवॉर्ड इतिहास और जुड़े खाते की जानकारी देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to read your latest alerts, offers and scan updates.": "नवीनतम सूचनाएँ, ऑफ़र और स्कैन अपडेट पढ़ने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to manage your profile, password and electrician preferences.": "अपनी प्रोफ़ाइल, पासवर्ड और इलेक्ट्रीशियन की पसंद प्रबंधित करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to redeem gifts and access your earned member rewards.": "उपहार लेने और कमाए हुए सदस्य रिवॉर्ड देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to scan products, earn points and track scan history.": "उत्पाद स्कैन करने, पॉइंट कमाने और स्कैन इतिहास देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to view your tier progress and reward level benefits.": "अपने स्तर की प्रगति और रिवॉर्ड स्तर के लाभ देखने के लिए लॉगिन करें या खाता बनाएँ।",
    "Login or signup to transfer points and access wallet actions securely.": "सुरक्षित पॉइंट ट्रांसफर और वॉलेट कार्यों के लिए लॉगिन करें या खाता बनाएँ।",
    "Protected Feature": "सुरक्षित सुविधा",
    "Login or signup to access this feature and continue with your account.": "इस सुविधा का उपयोग करने के लिए लॉगिन करें या खाता बनाएँ।",
    "SRV": "एसआरवी",
    "SRV ELECTRICALS": "एसआरवी इलेक्ट्रिकल्स",
    "NOW": "अभी",
    "Counter boy bottom navigation support": "काउंटर बॉय निचला नेविगेशन सहायता",
    "Account": "खाता",
    "FOR OUR SRV COUNTER BOYS": "हमारे एसआरवी काउंटर बॉय के लिए",
    "Face of Every Sale": "हर बिक्री की पहचान",
    "Building Customer Trust": "ग्राहकों का भरोसा बनाना",
    "Your product knowledge and warm attitude turns every visitor into a loyal customer": "उत्पादों की आपकी जानकारी और अच्छा व्यवहार हर आगंतुक को वफ़ादार ग्राहक बनाते हैं",
    "SMART BILLING": "स्मार्ट बिलिंग",
    "LIVE STOCK": "मौजूदा स्टॉक",
    "SALES REPORT": "बिक्री रिपोर्ट",
    "QUICK RETURNS": "त्वरित वापसी",
    "✦ 25 Years of Trust & Improvement ✦": "✦ भरोसे और सुधार के 25 वर्ष ✦",
    "SRV Electricals": "एसआरवी इलेक्ट्रिकल्स",
    "more items": "और आइटम",
    "Dealer bottom navigation electricians": "डीलर निचला नेविगेशन इलेक्ट्रीशियन",
    "All Time": "सभी समय",
    "Last Month": "पिछला महीना",
    "Rs.": "रु.",
    "Industrial Fan": "औद्योगिक पंखा",
    "Stabilizer": "स्टेबलाइज़र",
    "Bus Bar Super": "बस बार सुपर",
    "Dealer home call electrician": "डीलर होम इलेक्ट्रीशियन को कॉल करें",
    "Dealer home member tier": "डीलर होम सदस्य स्तर",
    "Electrician bottom navigation scan": "इलेक्ट्रीशियन निचला नेविगेशन स्कैन",
    "Electrician home total points wallet": "इलेक्ट्रीशियन होम कुल पॉइंट वॉलेट",
    "Electrician home member tier": "इलेक्ट्रीशियन होम सदस्य स्तर",
    "Customer account access and rewards overview": "ग्राहक खाता और रिवॉर्ड का परिचय",
    "Counter operations and account access": "काउंटर कार्य और खाते तक पहुँच",
    "For onboarding and rewards.": "पंजीकरण और रिवॉर्ड के लिए।",
    "Hindi onboarding and rewards.": "हिन्दी में पंजीकरण और रिवॉर्ड।",
    "Punjabi onboarding and rewards.": "पंजाबी में पंजीकरण और रिवॉर्ड।",
    "Enter the owner or business name and optional email address.": "मालिक या व्यवसाय का नाम और वैकल्पिक ईमेल पता दर्ज करें।",
    "Enter your state, district and 6-digit pincode manually.": "अपना राज्य, ज़िला और छह अंकों का पिनकोड दर्ज करें।",
    "name@business.com": "नाम@व्यवसाय.com",
    "% off": "% छूट",
    "Inclusive of all taxes": "सभी कर शामिल हैं",
    "% OFF": "% छूट",
    "No readable QR code was found in this image. Choose the original image with the complete QR code visible.": "इस तस्वीर में पढ़ने योग्य क्यूआर कोड नहीं मिला। वह मूल तस्वीर चुनें जिसमें पूरा क्यूआर कोड दिखाई दे।",
    "Request payout": "भुगतान का अनुरोध करें",
    "Order history": "ऑर्डर इतिहास",
    "Gift Order": "उपहार ऑर्डर",
    "Send to electrician": "इलेक्ट्रीशियन को भेजें",
    "Send to counter boy": "काउंटर बॉय को भेजें",
    "Available Bonus": "उपलब्ध बोनस",
    "Transactions": "लेन-देन",
    "FOR OUR SRV CUSTOMERS": "हमारे एसआरवी ग्राहकों के लिए",
    "Your Home Deserves": "आपके घर को मिले",
    "The Best Quality": "सर्वोत्तम गुणवत्ता",
    "250+ certified products trusted by 5L+ happy customers": "पाँच लाख से अधिक संतुष्ट ग्राहकों के भरोसे वाले 250 से अधिक प्रमाणित उत्पाद",
    "FOR OUR SRV DEALERS": "हमारे एसआरवी डीलरों के लिए",
    "PARTNERSHIP": "साझेदारी",
    "Let us build a strong relationship to ensure the distribution of SRV product range to the every corner of India.": "आइए मज़बूत संबंध बनाकर एसआरवी उत्पादों को भारत के हर कोने तक पहुँचाएँ।",
    "DEALERS": "डीलर",
    "REWARDS": "रिवॉर्ड",
    "STATES": "राज्य",
    "FOR OUR SRV ELECTRICIANS": "हमारे एसआरवी इलेक्ट्रीशियनों के लिए",
    "Scan Products": "उत्पाद स्कैन करें",
    "Earn Rewards": "रिवॉर्ड कमाएँ",
    "Get paid instantly for every SRV product you install": "हर एसआरवी उत्पाद लगाने पर तुरंत भुगतान पाएँ",
    "Scan QR": "क्यूआर स्कैन करें",
    "Get Points": "पॉइंट पाएँ",
    "REWARDS PAID": "दिए गए रिवॉर्ड",
    "ACTIVE MEMBERS": "सक्रिय सदस्य",
    "Scan QR. Earn rewards.": "क्यूआर स्कैन करें। रिवॉर्ड कमाएँ।",
    "Manage orders & benefits": "ऑर्डर और लाभ प्रबंधित करें",
    "Customer": "ग्राहक",
    "Explore SRV products": "एसआरवी उत्पाद देखें",
    "TRUST": "भरोसा",
    "QUALITY": "गुणवत्ता",
    "DURABLE": "टिकाऊ",
    "PRECISION": "सटीकता",
    "25 YEARS OF TRUST & IMPROVEMENT": "भरोसे और सुधार के 25 वर्ष",
    "SRV Welcomes You": "एसआरवी में आपका स्वागत है",
    "Select your SRV experience": "अपना एसआरवी अनुभव चुनें",
    "North India&apos;s Largest Metal Box Manufacturer": "उत्तर भारत का सबसे बड़ा मेटल बॉक्स निर्माता",
    "Choose Your Profile": "अपनी प्रोफ़ाइल चुनें",
    "Choose Source": "स्रोत चुनें",
    "Select document source": "दस्तावेज़ का स्रोत चुनें",
    "Camera": "कैमरा",
    "File": "फ़ाइल",
    "Failed to pick document": "दस्तावेज़ नहीं चुना जा सका",
    "Allow camera access to upload documents.": "दस्तावेज़ अपलोड करने के लिए कैमरे की अनुमति दें।",
    "Failed to pick file": "फ़ाइल नहीं चुनी जा सकी",
    "Document uploaded successfully": "दस्तावेज़ सफलतापूर्वक अपलोड हुआ",
    "Upload Failed": "अपलोड नहीं हुआ",
    "PDF": "PDF",
    "Tap to change": "बदलने के लिए टैप करें",
    "Tap to upload": "अपलोड करने के लिए टैप करें",
    "Choose from camera, gallery, or files": "कैमरा, गैलरी या फ़ाइलों से चुनें",
    "Request Account Deletion": "खाता हटाने का अनुरोध करें",
    "Aadhaar Number": "आधार नंबर",
    "Protected": "सुरक्षित",
    "Access Required": "लॉगिन आवश्यक है",
    "Login or signup to continue": "जारी रखने के लिए लॉगिन या पंजीकरण करें",
    "This feature becomes available as soon as your account is active.": "खाता सक्रिय होते ही यह सुविधा उपलब्ध होगी।",
    "Your deletion request has been submitted. SRV Support will verify the request and contact you about any records that must be retained by law.": "खाता हटाने का अनुरोध जमा हो गया है। SRV सहायता टीम अनुरोध की पुष्टि करेगी और कानूनी तौर पर सुरक्षित रखे जाने वाले रिकॉर्ड के बारे में आपसे संपर्क करेगी।",
    "We could not submit your request. Please try again or contact support.": "अनुरोध जमा नहीं हो सका। दोबारा कोशिश करें या सहायता टीम से संपर्क करें।",
    "Account & Data Deletion": "खाता और डेटा हटाना",
    "Request account deletion": "खाता हटाने का अनुरोध",
    "This closes your SRV Electricals app account after identity verification. Wallet, reward and transaction records are retained only where required for legal, accounting or fraud-prevention obligations.": "पहचान की पुष्टि के बाद आपका SRV Electricals ऐप खाता बंद कर दिया जाएगा। वॉलेट, रिवॉर्ड और लेनदेन के रिकॉर्ड केवल कानूनी, लेखांकन या धोखाधड़ी रोकने की आवश्यकताओं के अनुसार रखे जाएंगे।",
    "Submit this request?": "यह अनुरोध जमा करें?",
    "SRV Support will receive a verified deletion request for your signed-in account.": "आपके लॉगिन किए गए खाते को हटाने का सत्यापित अनुरोध SRV सहायता टीम को भेजा जाएगा।",
    "Request deletion": "हटाने का अनुरोध करें",
    "Don't get bored — check out our website for exciting new products!": "नए उत्पाद देखने के लिए हमारी वेबसाइट पर जाएँ!",
    "srvelectricals.com →": "srvelectricals.com →",
    "🏢 Dealer": "🏢 डीलर",
    "WALLET ACCESS": "वॉलेट की सुविधा",
    "Documents submitted": "दस्तावेज़ जमा हो गए",
    "Wallet unlocks automatically once SRV Team approves your KYC.": "SRV टीम द्वारा KYC मंज़ूर होने पर वॉलेट अपने आप खुल जाएगा।",
    "Steps to unlock wallet": "वॉलेट खोलने के चरण",
    "Wallet features locked": "वॉलेट सुविधाएँ बंद हैं",
    "PAN Card (Optional)": "पैन कार्ड (वैकल्पिक)",
    "GST Number (Optional)": "GST नंबर (वैकल्पिक)",
    "Return Order": "ऑर्डर वापस करें",
    "Shipped": "भेज दिया गया",
    "Points redeemed": "इस्तेमाल किए गए पॉइंट्स",
    "Processing": "प्रक्रिया जारी है",
    "Dispatched": "रवाना कर दिया गया",
    "Valid till:": "इस तारीख तक मान्य:",
    "One capital letter": "एक बड़ा अंग्रेज़ी अक्षर",
    "One special character": "एक विशेष चिह्न",
    "CREATE ACCESS ->": "खाता बनाएँ →",
    "UPDATE SECURITY ->": "सुरक्षा अपडेट करें →",
    "SRV privacy policy": "SRV गोपनीयता नीति",
    "1. Information Collection": "1. जानकारी एकत्र करना",
    "2. Use of Information": "2. जानकारी का उपयोग",
    "3. Data Security": "3. डेटा सुरक्षा",
    "4. Information Sharing": "4. जानकारी साझा करना",
    "5. User Rights": "5. उपयोगकर्ता के अधिकार",
    "6. Cookies & Tracking": "6. कुकीज़ और ट्रैकिंग",
    "7. Third-Party Links": "7. अन्य वेबसाइटों के लिंक",
    "8. Children's Privacy": "8. बच्चों की गोपनीयता",
    "9. Policy Changes": "9. नीति में बदलाव",
    "10. Contact Us": "10. संपर्क करें",
    "April 2026": "अप्रैल 2026",
    "Please request a new OTP for this phone number.": "इस फ़ोन नंबर के लिए नया OTP माँगें।",
    "Verify your new phone number before saving.": "सहेजने से पहले नए फ़ोन नंबर की पुष्टि करें।",
    "KYC Verified": "KYC सत्यापित",
    "Achieved Gifts": "प्राप्त उपहार",
    "Phone number verified": "फ़ोन नंबर सत्यापित है",
    "GST Number / PAN Number": "GST नंबर / पैन नंबर",
    "Are you sure you want to log out? Your data will be saved.": "क्या आप लॉगआउट करना चाहते हैं? आपका डेटा सुरक्षित रहेगा।",
    "You get": "आपको मिलेगा",
    "Friend gets": "मित्र को मिलेगा",
    "Guides": "गाइड",
    "Reels": "रील्स",
    "Tips": "सुझाव",
    "Don't have an account?": "खाता नहीं है?",
    "Already have an account?": "पहले से खाता है?",
    "User bottom navigation categories": "ग्राहक का श्रेणी नेविगेशन",
    "Play": "चलाएँ",
    "Qty:": "मात्रा:",
    "User home need help": "ग्राहक होम सहायता",
    "User home my cart": "ग्राहक होम कार्ट",
    "All Videos": "सभी वीडियो",
    "Video Guides": "वीडियो गाइड",
    "Quick Reels": "छोटी रील्स",
    "Helpful Tips": "उपयोगी सुझाव",
    "Quick Reel": "छोटी रील",
    "Video Guide": "वीडियो गाइड",
    "Helpful Tip": "उपयोगी सुझाव",
    "SRV Play": "SRV प्ले",
    "Tap to open full video": "पूरा वीडियो खोलने के लिए टैप करें",
    "comments": "टिप्पणियाँ",
    "Comment here and get SRV Team reply": "यहाँ टिप्पणी करें और SRV टीम का जवाब पाएँ",
    "Could not sync likes or comments right now": "अभी लाइक या टिप्पणियाँ अपडेट नहीं हो सके",
    "Please make sure you are signed in and the server is reachable, then try again.": "सुनिश्चित करें कि आपने लॉगिन किया है और सर्वर से कनेक्शन है, फिर दोबारा कोशिश करें।",
    "Add your comment": "अपनी टिप्पणी जोड़ें",
    "Write your feedback, question or review...": "अपनी प्रतिक्रिया, प्रश्न या समीक्षा लिखें...",
    "No comments yet": "अभी कोई टिप्पणी नहीं है",
    "Be the first one to ask something or share feedback on this video.": "इस वीडियो पर सबसे पहले सवाल पूछें या प्रतिक्रिया दें।",
    "Video": "वीडियो",
    "✦ SRV Play Zone ✦": "✦ SRV प्ले ज़ोन ✦",
    "This Feature is": "यह सुविधा",
    "Coming Soon": "जल्द आ रही है",
    "Stay Updated": "अपडेट पाते रहें",
    "We&apos;re crafting an amazing video experience for you - product guides, quick reels, and helpful tips. It&apos;ll be worth the wait!": "हम आपके लिए उत्पाद गाइड, छोटी रील्स और उपयोगी सुझावों वाला शानदार वीडियो अनुभव तैयार कर रहे हैं। इंतज़ार का फल अच्छा होगा!",
    "skipped": "छोड़ दिया गया",
    "OK": "ठीक है",
    "Update Available": "अपडेट उपलब्ध है",
    "New Version Required": "नया संस्करण आवश्यक है",
    "SRV Electricals · Powering Your Rewards": "SRV Electricals · आपके रिवॉर्ड का साथी",
    "Under Maintenance": "रखरखाव जारी है",
    "We&apos;ll be back soon!": "हम जल्द वापस आएँगे!",
    "Check Again": "फिर जाँचें",
    "&ldquo;": "“",
    "&rdquo;": "”",
    "SRV की पूरी प्रोडक्ट रेंज ऑनलाइन देखें": "SRV की पूरी प्रोडक्ट रेंज ऑनलाइन देखें",
    "कैटेगरी, प्रोडक्ट डिटेल्स और लेटेस्ट अपडेट सीधे SRV Electricals की आधिकारिक वेबसाइट पर देखें।": "कैटेगरी, प्रोडक्ट डिटेल्स और लेटेस्ट अपडेट सीधे SRV Electricals की आधिकारिक वेबसाइट पर देखें।",
    "SRV ਦੀ ਪੂਰੀ ਪ੍ਰੋਡਕਟ ਰੇਂਜ ਆਨਲਾਈਨ ਵੇਖੋ": "SRV की पूरी प्रोडक्ट रेंज ऑनलाइन देखें",
    "ਕੈਟੇਗਰੀਆਂ, ਪ੍ਰੋਡਕਟ ਡੀਟੇਲ ਅਤੇ ਤਾਜ਼ਾ ਅਪਡੇਟ ਸਿੱਧੇ SRV Electricals ਦੀ ਅਧਿਕਾਰਿਕ ਵੈਬਸਾਈਟ ਉੱਤੇ ਵੇਖੋ।": "कैटेगरी, प्रोडक्ट डिटेल्स और लेटेस्ट अपडेट सीधे SRV Electricals की आधिकारिक वेबसाइट पर देखें।",
    "Explore the full SRV product range online": "SRV की पूरी उत्पाद रेंज ऑनलाइन देखें",
    "Discover categories, product details, and the latest updates directly on the official SRV Electricals website.": "श्रेणियाँ, उत्पाद की जानकारी और नए अपडेट सीधे SRV Electricals की आधिकारिक वेबसाइट पर देखें।",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Electrician access for QR rewards, secure login, and fast registration.": "QR रिवॉर्ड, सुरक्षित लॉगिन और तेज़ पंजीकरण के लिए इलेक्ट्रीशियन खाता।",
    "Dealer access for business onboarding, orders, and verified partner login.": "व्यवसाय पंजीकरण, ऑर्डर और सत्यापित पार्टनर लॉगिन के लिए डीलर खाता।",
    "Browse certified electrical products and connect with dealers and electricians.": "प्रमाणित विद्युत उत्पाद देखें और डीलरों व इलेक्ट्रीशियनों से जुड़ें।",
    "Counter boy access for billing support, scanning, and day-to-day store operations.": "बिलिंग सहायता, स्कैनिंग और दुकान के रोज़मर्रा के काम के लिए काउंटर बॉय खाता।",
    "F8 / FC / FDB 18-40 PC": "F8 / FC / FDB 18-40 PC",
    "FC 4 17-30 / 20-40 PC": "FC 4 17-30 / 20-40 PC",
    "CRD PL precision build": "CRD PL सटीक बनावट",
    "Outdoor high-throw lighting": "बाहर दूर तक रोशनी",
    "Appliances": "उपकरण",
    "Junction Box": "जंक्शन बॉक्स",
    "Accessories": "सहायक सामान",
    "SRV Switch 16A scanned": "SRV स्विच 16A स्कैन हुआ",
    "Cashback redeemed": "कैशबैक लिया गया",
    "Referral bonus earned": "रेफ़रल बोनस मिला",
    "Verify Phone Number": "फ़ोन नंबर की पुष्टि करें",
    "Please wait...": "कृपया प्रतीक्षा करें...",
    "Enter OTP": "OTP दर्ज करें",
    "Send OTP": "OTP भेजें",
    "Verify OTP": "OTP की पुष्टि करें",
    "No readable QR code was found in this image. Please choose a clear, uncropped QR image.": "इस तस्वीर में पढ़ने योग्य QR कोड नहीं मिला। साफ़ और पूरा QR कोड वाली तस्वीर चुनें।"
  },
  "Punjabi": {
    "Dealer Wallet": "ਡੀਲਰ ਵਾਲਿਟ",
    "Login or signup to view your bonus wallet, payouts and linked account details.": "ਆਪਣਾ ਬੋਨਸ ਵਾਲਿਟ, ਭੁਗਤਾਨ ਅਤੇ ਜੁੜੇ ਖਾਤੇ ਦੀ ਜਾਣਕਾਰੀ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Dealer Notifications": "ਡੀਲਰ ਸੂਚਨਾਵਾਂ",
    "Login or signup to see dealer alerts, updates and account messages.": "ਡੀਲਰ ਸੂਚਨਾਵਾਂ, ਅੱਪਡੇਟ ਅਤੇ ਖਾਤੇ ਦੇ ਸੁਨੇਹੇ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Dealer Profile": "ਡੀਲਰ ਪ੍ਰੋਫਾਈਲ",
    "Login or signup to manage your dealer profile, password and app preferences.": "ਆਪਣੀ ਡੀਲਰ ਪ੍ਰੋਫਾਈਲ, ਪਾਸਵਰਡ ਅਤੇ ਐਪ ਦੀਆਂ ਪਸੰਦਾਂ ਸੰਭਾਲਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Associated Electricians": "ਜੁੜੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ",
    "Login or signup to manage your electrician network and dealer relationships.": "ਆਪਣਾ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨੈੱਟਵਰਕ ਅਤੇ ਡੀਲਰ ਸੰਬੰਧ ਸੰਭਾਲਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to access your connected electricians and outreach tools.": "ਆਪਣੇ ਜੁੜੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਅਤੇ ਸੰਪਰਕ ਸਾਧਨਾਂ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Dealer Tier": "ਡੀਲਰ ਪੱਧਰ",
    "Login or signup to check your dealer growth level and next tier progress.": "ਆਪਣਾ ਡੀਲਰ ਪੱਧਰ ਅਤੇ ਅਗਲੇ ਪੱਧਰ ਦੀ ਤਰੱਕੀ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to request dealer bonus payouts and review linked bank details.": "ਡੀਲਰ ਬੋਨਸ ਭੁਗਤਾਨ ਦੀ ਬੇਨਤੀ ਕਰਨ ਅਤੇ ਜੁੜਿਆ ਬੈਂਕ ਖਾਤਾ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Transfers": "ਟ੍ਰਾਂਸਫਰ",
    "Login or signup to access dealer transfer and linked wallet actions.": "ਡੀਲਰ ਟ੍ਰਾਂਸਫਰ ਅਤੇ ਜੁੜੇ ਵਾਲਿਟ ਦੇ ਕੰਮਾਂ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to view your bonus earnings and withdrawal requests.": "ਆਪਣੀ ਬੋਨਸ ਕਮਾਈ ਅਤੇ ਨਿਕਾਸੀ ਬੇਨਤੀਆਂ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to see your wallet balance, points and activity.": "ਆਪਣਾ ਵਾਲਿਟ ਬਕਾਇਆ, ਪੁਆਇੰਟ ਅਤੇ ਸਰਗਰਮੀ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to see your latest alerts, offers and updates.": "ਤਾਜ਼ਾ ਸੂਚਨਾਵਾਂ, ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਅੱਪਡੇਟ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to manage your profile, password and personal settings.": "ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ, ਪਾਸਵਰਡ ਅਤੇ ਨਿੱਜੀ ਸੈਟਿੰਗਾਂ ਸੰਭਾਲਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to redeem rewards and explore member-only benefits.": "ਇਨਾਮ ਲੈਣ ਅਤੇ ਮੈਂਬਰਾਂ ਦੇ ਲਾਭ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to request bank payouts and review your linked account details.": "ਬੈਂਕ ਭੁਗਤਾਨ ਦੀ ਬੇਨਤੀ ਕਰਨ ਅਤੇ ਜੁੜੇ ਖਾਤੇ ਦੀ ਜਾਣਕਾਰੀ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to access point transfer and wallet actions.": "ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਅਤੇ ਵਾਲਿਟ ਦੇ ਕੰਮਾਂ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to view your points, rewards and account-linked wallet details.": "ਆਪਣੇ ਪੁਆਇੰਟ, ਇਨਾਮ ਅਤੇ ਖਾਤੇ ਨਾਲ ਜੁੜੇ ਵਾਲਿਟ ਦੀ ਜਾਣਕਾਰੀ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to read counter boy alerts, offers and updates.": "ਕਾਊਂਟਰ ਬੁਆਏ ਦੀਆਂ ਸੂਚਨਾਵਾਂ, ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਅੱਪਡੇਟ ਪੜ੍ਹਨ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to manage your profile, password and app preferences.": "ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ, ਪਾਸਵਰਡ ਅਤੇ ਐਪ ਦੀਆਂ ਪਸੰਦਾਂ ਸੰਭਾਲਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to redeem gifts and explore rewards with your earned points.": "ਕਮਾਏ ਪੁਆਇੰਟਾਂ ਨਾਲ ਤੋਹਫ਼ੇ ਲੈਣ ਅਤੇ ਇਨਾਮ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to access wallet-linked transfer actions.": "ਵਾਲਿਟ ਨਾਲ ਜੁੜੇ ਟ੍ਰਾਂਸਫਰ ਕੰਮਾਂ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to see your points, rewards history and linked account details.": "ਆਪਣੇ ਪੁਆਇੰਟ, ਇਨਾਮ ਇਤਿਹਾਸ ਅਤੇ ਜੁੜੇ ਖਾਤੇ ਦੀ ਜਾਣਕਾਰੀ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to read your latest alerts, offers and scan updates.": "ਤਾਜ਼ਾ ਸੂਚਨਾਵਾਂ, ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਸਕੈਨ ਅੱਪਡੇਟ ਪੜ੍ਹਨ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to manage your profile, password and electrician preferences.": "ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ, ਪਾਸਵਰਡ ਅਤੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਦੀਆਂ ਪਸੰਦਾਂ ਸੰਭਾਲਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to redeem gifts and access your earned member rewards.": "ਤੋਹਫ਼ੇ ਲੈਣ ਅਤੇ ਕਮਾਏ ਮੈਂਬਰ ਇਨਾਮ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to scan products, earn points and track scan history.": "ਉਤਪਾਦ ਸਕੈਨ ਕਰਨ, ਪੁਆਇੰਟ ਕਮਾਉਣ ਅਤੇ ਸਕੈਨ ਇਤਿਹਾਸ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to view your tier progress and reward level benefits.": "ਆਪਣੇ ਪੱਧਰ ਦੀ ਤਰੱਕੀ ਅਤੇ ਇਨਾਮ ਪੱਧਰ ਦੇ ਲਾਭ ਵੇਖਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Login or signup to transfer points and access wallet actions securely.": "ਸੁਰੱਖਿਅਤ ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਅਤੇ ਵਾਲਿਟ ਕੰਮਾਂ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Protected Feature": "ਸੁਰੱਖਿਅਤ ਸਹੂਲਤ",
    "Login or signup to access this feature and continue with your account.": "ਇਸ ਸਹੂਲਤ ਨੂੰ ਵਰਤਣ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "SRV": "ਐੱਸਆਰਵੀ",
    "SRV ELECTRICALS": "ਐੱਸਆਰਵੀ ਇਲੈਕਟ੍ਰਿਕਲਜ਼",
    "NOW": "ਹੁਣ",
    "Counter boy bottom navigation support": "ਕਾਊਂਟਰ ਬੁਆਏ ਹੇਠਲਾ ਨੈਵੀਗੇਸ਼ਨ ਸਹਾਇਤਾ",
    "Account": "ਖਾਤਾ",
    "FOR OUR SRV COUNTER BOYS": "ਸਾਡੇ ਐੱਸਆਰਵੀ ਕਾਊਂਟਰ ਬੁਆਏ ਲਈ",
    "Face of Every Sale": "ਹਰ ਵਿਕਰੀ ਦੀ ਪਛਾਣ",
    "Building Customer Trust": "ਗਾਹਕਾਂ ਦਾ ਭਰੋਸਾ ਬਣਾਉਣਾ",
    "Your product knowledge and warm attitude turns every visitor into a loyal customer": "ਉਤਪਾਦਾਂ ਦੀ ਤੁਹਾਡੀ ਜਾਣਕਾਰੀ ਅਤੇ ਚੰਗਾ ਵਿਹਾਰ ਹਰ ਆਉਣ ਵਾਲੇ ਨੂੰ ਵਫ਼ਾਦਾਰ ਗਾਹਕ ਬਣਾਉਂਦੇ ਹਨ",
    "SMART BILLING": "ਸਮਾਰਟ ਬਿਲਿੰਗ",
    "LIVE STOCK": "ਮੌਜੂਦਾ ਸਟਾਕ",
    "SALES REPORT": "ਵਿਕਰੀ ਰਿਪੋਰਟ",
    "QUICK RETURNS": "ਤੁਰੰਤ ਵਾਪਸੀ",
    "✦ 25 Years of Trust & Improvement ✦": "✦ ਭਰੋਸੇ ਅਤੇ ਸੁਧਾਰ ਦੇ 25 ਸਾਲ ✦",
    "SRV Electricals": "ਐੱਸਆਰਵੀ ਇਲੈਕਟ੍ਰਿਕਲਜ਼",
    "more items": "ਹੋਰ ਚੀਜ਼ਾਂ",
    "Dealer bottom navigation electricians": "ਡੀਲਰ ਹੇਠਲਾ ਨੈਵੀਗੇਸ਼ਨ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ",
    "All Time": "ਸਾਰਾ ਸਮਾਂ",
    "Last Month": "ਪਿਛਲਾ ਮਹੀਨਾ",
    "Rs.": "ਰੁ.",
    "Industrial Fan": "ਉਦਯੋਗਿਕ ਪੱਖਾ",
    "Stabilizer": "ਸਟੇਬਲਾਈਜ਼ਰ",
    "Bus Bar Super": "ਬੱਸ ਬਾਰ ਸੁਪਰ",
    "Dealer home call electrician": "ਡੀਲਰ ਹੋਮ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨੂੰ ਕਾਲ ਕਰੋ",
    "Dealer home member tier": "ਡੀਲਰ ਹੋਮ ਮੈਂਬਰ ਪੱਧਰ",
    "Electrician bottom navigation scan": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਹੇਠਲਾ ਨੈਵੀਗੇਸ਼ਨ ਸਕੈਨ",
    "Electrician home total points wallet": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਹੋਮ ਕੁੱਲ ਪੁਆਇੰਟ ਵਾਲਿਟ",
    "Electrician home member tier": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਹੋਮ ਮੈਂਬਰ ਪੱਧਰ",
    "Customer account access and rewards overview": "ਗਾਹਕ ਖਾਤੇ ਅਤੇ ਇਨਾਮਾਂ ਦੀ ਜਾਣਕਾਰੀ",
    "Counter operations and account access": "ਕਾਊਂਟਰ ਦੇ ਕੰਮ ਅਤੇ ਖਾਤੇ ਤੱਕ ਪਹੁੰਚ",
    "For onboarding and rewards.": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਤੇ ਇਨਾਮਾਂ ਲਈ।",
    "Hindi onboarding and rewards.": "ਹਿੰਦੀ ਵਿੱਚ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਤੇ ਇਨਾਮ।",
    "Punjabi onboarding and rewards.": "ਪੰਜਾਬੀ ਵਿੱਚ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਤੇ ਇਨਾਮ।",
    "Enter the owner or business name and optional email address.": "ਮਾਲਕ ਜਾਂ ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ ਅਤੇ ਚੋਣਵਾਂ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ।",
    "Enter your state, district and 6-digit pincode manually.": "ਆਪਣਾ ਰਾਜ, ਜ਼ਿਲ੍ਹਾ ਅਤੇ ਛੇ ਅੰਕਾਂ ਦਾ ਪਿੰਨਕੋਡ ਦਰਜ ਕਰੋ।",
    "name@business.com": "ਨਾਮ@ਕਾਰੋਬਾਰ.com",
    "% off": "% ਛੋਟ",
    "Inclusive of all taxes": "ਸਾਰੇ ਟੈਕਸ ਸ਼ਾਮਲ ਹਨ",
    "% OFF": "% ਛੋਟ",
    "No readable QR code was found in this image. Choose the original image with the complete QR code visible.": "ਇਸ ਤਸਵੀਰ ਵਿੱਚ ਪੜ੍ਹਨਯੋਗ ਕਿਊਆਰ ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ। ਉਹ ਅਸਲ ਤਸਵੀਰ ਚੁਣੋ ਜਿਸ ਵਿੱਚ ਪੂਰਾ ਕਿਊਆਰ ਕੋਡ ਦਿਖਾਈ ਦੇਵੇ।",
    "Request payout": "ਭੁਗਤਾਨ ਦੀ ਬੇਨਤੀ ਕਰੋ",
    "Order history": "ਆਰਡਰ ਇਤਿਹਾਸ",
    "Gift Order": "ਤੋਹਫ਼ੇ ਦਾ ਆਰਡਰ",
    "Send to electrician": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨੂੰ ਭੇਜੋ",
    "Send to counter boy": "ਕਾਊਂਟਰ ਬੁਆਏ ਨੂੰ ਭੇਜੋ",
    "Available Bonus": "ਉਪਲਬਧ ਬੋਨਸ",
    "Transactions": "ਲੈਣ-ਦੇਣ",
    "FOR OUR SRV CUSTOMERS": "ਸਾਡੇ ਐੱਸਆਰਵੀ ਗਾਹਕਾਂ ਲਈ",
    "Your Home Deserves": "ਤੁਹਾਡੇ ਘਰ ਨੂੰ ਮਿਲੇ",
    "The Best Quality": "ਸਭ ਤੋਂ ਵਧੀਆ ਗੁਣਵੱਤਾ",
    "250+ certified products trusted by 5L+ happy customers": "ਪੰਜ ਲੱਖ ਤੋਂ ਵੱਧ ਸੰਤੁਸ਼ਟ ਗਾਹਕਾਂ ਦੇ ਭਰੋਸੇ ਵਾਲੇ 250 ਤੋਂ ਵੱਧ ਪ੍ਰਮਾਣਿਤ ਉਤਪਾਦ",
    "FOR OUR SRV DEALERS": "ਸਾਡੇ ਐੱਸਆਰਵੀ ਡੀਲਰਾਂ ਲਈ",
    "PARTNERSHIP": "ਭਾਈਵਾਲੀ",
    "Let us build a strong relationship to ensure the distribution of SRV product range to the every corner of India.": "ਆਓ ਮਜ਼ਬੂਤ ਸੰਬੰਧ ਬਣਾ ਕੇ ਐੱਸਆਰਵੀ ਉਤਪਾਦਾਂ ਨੂੰ ਭਾਰਤ ਦੇ ਹਰ ਕੋਨੇ ਤੱਕ ਪਹੁੰਚਾਈਏ।",
    "DEALERS": "ਡੀਲਰ",
    "REWARDS": "ਇਨਾਮ",
    "STATES": "ਰਾਜ",
    "FOR OUR SRV ELECTRICIANS": "ਸਾਡੇ ਐੱਸਆਰਵੀ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਲਈ",
    "Scan Products": "ਉਤਪਾਦ ਸਕੈਨ ਕਰੋ",
    "Earn Rewards": "ਇਨਾਮ ਕਮਾਓ",
    "Get paid instantly for every SRV product you install": "ਹਰ ਐੱਸਆਰਵੀ ਉਤਪਾਦ ਲਗਾਉਣ ਉੱਤੇ ਤੁਰੰਤ ਭੁਗਤਾਨ ਲਵੋ",
    "Scan QR": "ਕਿਊਆਰ ਸਕੈਨ ਕਰੋ",
    "Get Points": "ਪੁਆਇੰਟ ਲਵੋ",
    "REWARDS PAID": "ਦਿੱਤੇ ਗਏ ਇਨਾਮ",
    "ACTIVE MEMBERS": "ਸਰਗਰਮ ਮੈਂਬਰ",
    "Scan QR. Earn rewards.": "ਕਿਊਆਰ ਸਕੈਨ ਕਰੋ। ਇਨਾਮ ਕਮਾਓ।",
    "Manage orders & benefits": "ਆਰਡਰ ਅਤੇ ਲਾਭ ਸੰਭਾਲੋ",
    "Customer": "ਗਾਹਕ",
    "Explore SRV products": "ਐੱਸਆਰਵੀ ਉਤਪਾਦ ਵੇਖੋ",
    "TRUST": "ਭਰੋਸਾ",
    "QUALITY": "ਗੁਣਵੱਤਾ",
    "DURABLE": "ਟਿਕਾਊ",
    "PRECISION": "ਸ਼ੁੱਧਤਾ",
    "25 YEARS OF TRUST & IMPROVEMENT": "ਭਰੋਸੇ ਅਤੇ ਸੁਧਾਰ ਦੇ 25 ਸਾਲ",
    "SRV Welcomes You": "ਐੱਸਆਰਵੀ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ",
    "Select your SRV experience": "ਆਪਣਾ ਐੱਸਆਰਵੀ ਅਨੁਭਵ ਚੁਣੋ",
    "North India&apos;s Largest Metal Box Manufacturer": "ਉੱਤਰੀ ਭਾਰਤ ਦਾ ਸਭ ਤੋਂ ਵੱਡਾ ਮੈਟਲ ਬਾਕਸ ਨਿਰਮਾਤਾ",
    "Choose Your Profile": "ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਚੁਣੋ",
    "Choose Source": "ਸਰੋਤ ਚੁਣੋ",
    "Select document source": "ਦਸਤਾਵੇਜ਼ ਦਾ ਸਰੋਤ ਚੁਣੋ",
    "Camera": "ਕੈਮਰਾ",
    "File": "ਫਾਈਲ",
    "Failed to pick document": "ਦਸਤਾਵੇਜ਼ ਨਹੀਂ ਚੁਣਿਆ ਜਾ ਸਕਿਆ",
    "Allow camera access to upload documents.": "ਦਸਤਾਵੇਜ਼ ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਕੈਮਰੇ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ।",
    "Failed to pick file": "ਫਾਈਲ ਨਹੀਂ ਚੁਣੀ ਜਾ ਸਕੀ",
    "Document uploaded successfully": "ਦਸਤਾਵੇਜ਼ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਲੋਡ ਹੋਇਆ",
    "Upload Failed": "ਅੱਪਲੋਡ ਨਹੀਂ ਹੋਇਆ",
    "PDF": "PDF",
    "Tap to change": "ਬਦਲਣ ਲਈ ਟੈਪ ਕਰੋ",
    "Tap to upload": "ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ",
    "Choose from camera, gallery, or files": "ਕੈਮਰਾ, ਗੈਲਰੀ ਜਾਂ ਫਾਈਲਾਂ ਵਿੱਚੋਂ ਚੁਣੋ",
    "Request Account Deletion": "ਖਾਤਾ ਮਿਟਾਉਣ ਦੀ ਬੇਨਤੀ ਕਰੋ",
    "Aadhaar Number": "ਆਧਾਰ ਨੰਬਰ",
    "Protected": "ਸੁਰੱਖਿਅਤ",
    "Access Required": "ਲੌਗਇਨ ਜ਼ਰੂਰੀ ਹੈ",
    "Login or signup to continue": "ਜਾਰੀ ਰੱਖਣ ਲਈ ਲੌਗਇਨ ਜਾਂ ਰਜਿਸਟਰ ਕਰੋ",
    "This feature becomes available as soon as your account is active.": "ਖਾਤਾ ਸਰਗਰਮ ਹੁੰਦੇ ਹੀ ਇਹ ਸਹੂਲਤ ਉਪਲਬਧ ਹੋਵੇਗੀ।",
    "Your deletion request has been submitted. SRV Support will verify the request and contact you about any records that must be retained by law.": "ਖਾਤਾ ਮਿਟਾਉਣ ਦੀ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਹੋ ਗਈ ਹੈ। SRV ਸਹਾਇਤਾ ਟੀਮ ਬੇਨਤੀ ਦੀ ਪੁਸ਼ਟੀ ਕਰੇਗੀ ਅਤੇ ਕਾਨੂੰਨ ਅਨੁਸਾਰ ਰੱਖੇ ਜਾਣ ਵਾਲੇ ਰਿਕਾਰਡਾਂ ਬਾਰੇ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੇਗੀ।",
    "We could not submit your request. Please try again or contact support.": "ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਨਹੀਂ ਹੋ ਸਕੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਸਹਾਇਤਾ ਟੀਮ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।",
    "Account & Data Deletion": "ਖਾਤਾ ਅਤੇ ਡਾਟਾ ਮਿਟਾਉਣਾ",
    "Request account deletion": "ਖਾਤਾ ਮਿਟਾਉਣ ਦੀ ਬੇਨਤੀ",
    "This closes your SRV Electricals app account after identity verification. Wallet, reward and transaction records are retained only where required for legal, accounting or fraud-prevention obligations.": "ਪਛਾਣ ਦੀ ਪੁਸ਼ਟੀ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡਾ SRV Electricals ਐਪ ਖਾਤਾ ਬੰਦ ਕੀਤਾ ਜਾਵੇਗਾ। ਵਾਲਿਟ, ਇਨਾਮ ਅਤੇ ਲੈਣ-ਦੇਣ ਦੇ ਰਿਕਾਰਡ ਸਿਰਫ਼ ਕਾਨੂੰਨੀ, ਲੇਖਾ ਜਾਂ ਧੋਖਾਧੜੀ ਰੋਕਣ ਦੀਆਂ ਲੋੜਾਂ ਅਨੁਸਾਰ ਰੱਖੇ ਜਾਣਗੇ।",
    "Submit this request?": "ਇਹ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰਨੀ ਹੈ?",
    "SRV Support will receive a verified deletion request for your signed-in account.": "ਤੁਹਾਡੇ ਲੌਗਇਨ ਕੀਤੇ ਖਾਤੇ ਨੂੰ ਮਿਟਾਉਣ ਦੀ ਤਸਦੀਕਸ਼ੁਦਾ ਬੇਨਤੀ SRV ਸਹਾਇਤਾ ਟੀਮ ਨੂੰ ਭੇਜੀ ਜਾਵੇਗੀ।",
    "Request deletion": "ਮਿਟਾਉਣ ਦੀ ਬੇਨਤੀ ਕਰੋ",
    "Don't get bored — check out our website for exciting new products!": "ਨਵੇਂ ਉਤਪਾਦ ਵੇਖਣ ਲਈ ਸਾਡੀ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਜਾਓ!",
    "srvelectricals.com →": "srvelectricals.com →",
    "🏢 Dealer": "🏢 ਡੀਲਰ",
    "WALLET ACCESS": "ਵਾਲਿਟ ਦੀ ਸਹੂਲਤ",
    "Documents submitted": "ਦਸਤਾਵੇਜ਼ ਜਮ੍ਹਾਂ ਹੋ ਗਏ",
    "Wallet unlocks automatically once SRV Team approves your KYC.": "SRV ਟੀਮ ਵੱਲੋਂ KYC ਮਨਜ਼ੂਰ ਹੋਣ ਉੱਤੇ ਵਾਲਿਟ ਆਪਣੇ ਆਪ ਖੁੱਲ੍ਹ ਜਾਵੇਗਾ।",
    "Steps to unlock wallet": "ਵਾਲਿਟ ਖੋਲ੍ਹਣ ਦੇ ਕਦਮ",
    "Wallet features locked": "ਵਾਲਿਟ ਸਹੂਲਤਾਂ ਬੰਦ ਹਨ",
    "PAN Card (Optional)": "ਪੈਨ ਕਾਰਡ (ਵਿਕਲਪਿਕ)",
    "GST Number (Optional)": "GST ਨੰਬਰ (ਵਿਕਲਪਿਕ)",
    "Return Order": "ਆਰਡਰ ਵਾਪਸ ਕਰੋ",
    "Shipped": "ਭੇਜ ਦਿੱਤਾ ਗਿਆ",
    "Points redeemed": "ਵਰਤੇ ਗਏ ਪੁਆਇੰਟ",
    "Processing": "ਕਾਰਵਾਈ ਜਾਰੀ ਹੈ",
    "Dispatched": "ਰਵਾਨਾ ਕਰ ਦਿੱਤਾ ਗਿਆ",
    "Valid till:": "ਇਸ ਤਾਰੀਖ ਤੱਕ ਵੈਧ:",
    "One capital letter": "ਇੱਕ ਵੱਡਾ ਅੰਗਰੇਜ਼ੀ ਅੱਖਰ",
    "One special character": "ਇੱਕ ਵਿਸ਼ੇਸ਼ ਚਿੰਨ੍ਹ",
    "CREATE ACCESS ->": "ਖਾਤਾ ਬਣਾਓ →",
    "UPDATE SECURITY ->": "ਸੁਰੱਖਿਆ ਅੱਪਡੇਟ ਕਰੋ →",
    "SRV privacy policy": "SRV ਪਰਦੇਦਾਰੀ ਨੀਤੀ",
    "1. Information Collection": "1. ਜਾਣਕਾਰੀ ਇਕੱਠੀ ਕਰਨਾ",
    "2. Use of Information": "2. ਜਾਣਕਾਰੀ ਦੀ ਵਰਤੋਂ",
    "3. Data Security": "3. ਡਾਟਾ ਸੁਰੱਖਿਆ",
    "4. Information Sharing": "4. ਜਾਣਕਾਰੀ ਸਾਂਝੀ ਕਰਨਾ",
    "5. User Rights": "5. ਵਰਤੋਂਕਾਰ ਦੇ ਅਧਿਕਾਰ",
    "6. Cookies & Tracking": "6. ਕੂਕੀਜ਼ ਅਤੇ ਟ੍ਰੈਕਿੰਗ",
    "7. Third-Party Links": "7. ਹੋਰ ਵੈੱਬਸਾਈਟਾਂ ਦੇ ਲਿੰਕ",
    "8. Children's Privacy": "8. ਬੱਚਿਆਂ ਦੀ ਪਰਦੇਦਾਰੀ",
    "9. Policy Changes": "9. ਨੀਤੀ ਵਿੱਚ ਬਦਲਾਅ",
    "10. Contact Us": "10. ਸੰਪਰਕ ਕਰੋ",
    "April 2026": "ਅਪ੍ਰੈਲ 2026",
    "Please request a new OTP for this phone number.": "ਇਸ ਫ਼ੋਨ ਨੰਬਰ ਲਈ ਨਵਾਂ OTP ਮੰਗੋ।",
    "Verify your new phone number before saving.": "ਸੇਵ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਨਵੇਂ ਫ਼ੋਨ ਨੰਬਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।",
    "KYC Verified": "KYC ਤਸਦੀਕਸ਼ੁਦਾ",
    "Achieved Gifts": "ਮਿਲੇ ਤੋਹਫ਼ੇ",
    "Phone number verified": "ਫ਼ੋਨ ਨੰਬਰ ਤਸਦੀਕ ਹੋ ਗਿਆ",
    "GST Number / PAN Number": "GST ਨੰਬਰ / ਪੈਨ ਨੰਬਰ",
    "Are you sure you want to log out? Your data will be saved.": "ਕੀ ਤੁਸੀਂ ਲੌਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ? ਤੁਹਾਡਾ ਡਾਟਾ ਸੁਰੱਖਿਅਤ ਰਹੇਗਾ।",
    "You get": "ਤੁਹਾਨੂੰ ਮਿਲੇਗਾ",
    "Friend gets": "ਦੋਸਤ ਨੂੰ ਮਿਲੇਗਾ",
    "Guides": "ਗਾਈਡ",
    "Reels": "ਰੀਲਾਂ",
    "Tips": "ਸੁਝਾਅ",
    "Don't have an account?": "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    "Already have an account?": "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
    "User bottom navigation categories": "ਗਾਹਕ ਦੀ ਸ਼੍ਰੇਣੀ ਨੈਵੀਗੇਸ਼ਨ",
    "Play": "ਚਲਾਓ",
    "Qty:": "ਗਿਣਤੀ:",
    "User home need help": "ਗਾਹਕ ਹੋਮ ਸਹਾਇਤਾ",
    "User home my cart": "ਗਾਹਕ ਹੋਮ ਕਾਰਟ",
    "All Videos": "ਸਾਰੇ ਵੀਡੀਓ",
    "Video Guides": "ਵੀਡੀਓ ਗਾਈਡ",
    "Quick Reels": "ਛੋਟੀਆਂ ਰੀਲਾਂ",
    "Helpful Tips": "ਲਾਭਦਾਇਕ ਸੁਝਾਅ",
    "Quick Reel": "ਛੋਟੀ ਰੀਲ",
    "Video Guide": "ਵੀਡੀਓ ਗਾਈਡ",
    "Helpful Tip": "ਲਾਭਦਾਇਕ ਸੁਝਾਅ",
    "SRV Play": "SRV ਪਲੇ",
    "Tap to open full video": "ਪੂਰਾ ਵੀਡੀਓ ਖੋਲ੍ਹਣ ਲਈ ਟੈਪ ਕਰੋ",
    "comments": "ਟਿੱਪਣੀਆਂ",
    "Comment here and get SRV Team reply": "ਇੱਥੇ ਟਿੱਪਣੀ ਕਰੋ ਅਤੇ SRV ਟੀਮ ਦਾ ਜਵਾਬ ਪਾਓ",
    "Could not sync likes or comments right now": "ਹੁਣੇ ਲਾਈਕ ਜਾਂ ਟਿੱਪਣੀਆਂ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀਆਂ",
    "Please make sure you are signed in and the server is reachable, then try again.": "ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਤੁਸੀਂ ਲੌਗਇਨ ਕੀਤਾ ਹੈ ਅਤੇ ਸਰਵਰ ਨਾਲ ਕਨੈਕਸ਼ਨ ਹੈ, ਫਿਰ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Add your comment": "ਆਪਣੀ ਟਿੱਪਣੀ ਜੋੜੋ",
    "Write your feedback, question or review...": "ਆਪਣੀ ਪ੍ਰਤੀਕਿਰਿਆ, ਸਵਾਲ ਜਾਂ ਸਮੀਖਿਆ ਲਿਖੋ...",
    "No comments yet": "ਹਾਲੇ ਕੋਈ ਟਿੱਪਣੀ ਨਹੀਂ ਹੈ",
    "Be the first one to ask something or share feedback on this video.": "ਇਸ ਵੀਡੀਓ ਉੱਤੇ ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਸਵਾਲ ਪੁੱਛੋ ਜਾਂ ਪ੍ਰਤੀਕਿਰਿਆ ਦਿਓ।",
    "Video": "ਵੀਡੀਓ",
    "✦ SRV Play Zone ✦": "✦ SRV ਪਲੇ ਜ਼ੋਨ ✦",
    "This Feature is": "ਇਹ ਸਹੂਲਤ",
    "Coming Soon": "ਜਲਦੀ ਆ ਰਹੀ ਹੈ",
    "Stay Updated": "ਅੱਪਡੇਟ ਲੈਂਦੇ ਰਹੋ",
    "We&apos;re crafting an amazing video experience for you - product guides, quick reels, and helpful tips. It&apos;ll be worth the wait!": "ਅਸੀਂ ਤੁਹਾਡੇ ਲਈ ਉਤਪਾਦ ਗਾਈਡਾਂ, ਛੋਟੀਆਂ ਰੀਲਾਂ ਅਤੇ ਲਾਭਦਾਇਕ ਸੁਝਾਵਾਂ ਵਾਲਾ ਸ਼ਾਨਦਾਰ ਵੀਡੀਓ ਅਨੁਭਵ ਤਿਆਰ ਕਰ ਰਹੇ ਹਾਂ। ਉਡੀਕ ਦਾ ਫਲ ਚੰਗਾ ਹੋਵੇਗਾ!",
    "skipped": "ਛੱਡ ਦਿੱਤਾ ਗਿਆ",
    "OK": "ਠੀਕ ਹੈ",
    "Update Available": "ਅੱਪਡੇਟ ਉਪਲਬਧ ਹੈ",
    "New Version Required": "ਨਵਾਂ ਵਰਜ਼ਨ ਜ਼ਰੂਰੀ ਹੈ",
    "SRV Electricals · Powering Your Rewards": "SRV Electricals · ਤੁਹਾਡੇ ਇਨਾਮਾਂ ਦਾ ਸਾਥੀ",
    "Under Maintenance": "ਰੱਖ-ਰਖਾਅ ਜਾਰੀ ਹੈ",
    "We&apos;ll be back soon!": "ਅਸੀਂ ਜਲਦੀ ਵਾਪਸ ਆਵਾਂਗੇ!",
    "Check Again": "ਦੁਬਾਰਾ ਜਾਂਚੋ",
    "&ldquo;": "“",
    "&rdquo;": "”",
    "SRV की पूरी प्रोडक्ट रेंज ऑनलाइन देखें": "SRV ਦੀ ਪੂਰੀ ਪ੍ਰੋਡਕਟ ਰੇਂਜ ਆਨਲਾਈਨ ਵੇਖੋ",
    "कैटेगरी, प्रोडक्ट डिटेल्स और लेटेस्ट अपडेट सीधे SRV Electricals की आधिकारिक वेबसाइट पर देखें।": "ਕੈਟੇਗਰੀਆਂ, ਪ੍ਰੋਡਕਟ ਡੀਟੇਲ ਅਤੇ ਤਾਜ਼ਾ ਅੱਪਡੇਟ ਸਿੱਧੇ SRV Electricals ਦੀ ਅਧਿਕਾਰਿਕ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਵੇਖੋ।",
    "SRV ਦੀ ਪੂਰੀ ਪ੍ਰੋਡਕਟ ਰੇਂਜ ਆਨਲਾਈਨ ਵੇਖੋ": "SRV ਦੀ ਪੂਰੀ ਪ੍ਰੋਡਕਟ ਰੇਂਜ ਆਨਲਾਈਨ ਵੇਖੋ",
    "ਕੈਟੇਗਰੀਆਂ, ਪ੍ਰੋਡਕਟ ਡੀਟੇਲ ਅਤੇ ਤਾਜ਼ਾ ਅਪਡੇਟ ਸਿੱਧੇ SRV Electricals ਦੀ ਅਧਿਕਾਰਿਕ ਵੈਬਸਾਈਟ ਉੱਤੇ ਵੇਖੋ।": "ਕੈਟੇਗਰੀਆਂ, ਪ੍ਰੋਡਕਟ ਡੀਟੇਲ ਅਤੇ ਤਾਜ਼ਾ ਅੱਪਡੇਟ ਸਿੱਧੇ SRV Electricals ਦੀ ਅਧਿਕਾਰਿਕ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਵੇਖੋ।",
    "Explore the full SRV product range online": "SRV ਦੀ ਪੂਰੀ ਉਤਪਾਦ ਰੇਂਜ ਆਨਲਾਈਨ ਵੇਖੋ",
    "Discover categories, product details, and the latest updates directly on the official SRV Electricals website.": "ਸ਼੍ਰੇਣੀਆਂ, ਉਤਪਾਦਾਂ ਦੀ ਜਾਣਕਾਰੀ ਅਤੇ ਨਵੇਂ ਅੱਪਡੇਟ ਸਿੱਧੇ SRV Electricals ਦੀ ਅਧਿਕਾਰਿਕ ਵੈੱਬਸਾਈਟ ਉੱਤੇ ਵੇਖੋ।",
    "Facebook": "Facebook",
    "Twitter": "Twitter",
    "Electrician access for QR rewards, secure login, and fast registration.": "QR ਇਨਾਮਾਂ, ਸੁਰੱਖਿਅਤ ਲੌਗਇਨ ਅਤੇ ਤੇਜ਼ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਲਈ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਖਾਤਾ।",
    "Dealer access for business onboarding, orders, and verified partner login.": "ਕਾਰੋਬਾਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ, ਆਰਡਰਾਂ ਅਤੇ ਤਸਦੀਕਸ਼ੁਦਾ ਪਾਰਟਨਰ ਲੌਗਇਨ ਲਈ ਡੀਲਰ ਖਾਤਾ।",
    "Browse certified electrical products and connect with dealers and electricians.": "ਪ੍ਰਮਾਣਿਤ ਬਿਜਲੀ ਉਤਪਾਦ ਵੇਖੋ ਅਤੇ ਡੀਲਰਾਂ ਤੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਨਾਲ ਜੁੜੋ।",
    "Counter boy access for billing support, scanning, and day-to-day store operations.": "ਬਿਲਿੰਗ ਸਹਾਇਤਾ, ਸਕੈਨਿੰਗ ਅਤੇ ਦੁਕਾਨ ਦੇ ਰੋਜ਼ਾਨਾ ਕੰਮਾਂ ਲਈ ਕਾਊਂਟਰ ਬੁਆਏ ਖਾਤਾ।",
    "F8 / FC / FDB 18-40 PC": "F8 / FC / FDB 18-40 PC",
    "FC 4 17-30 / 20-40 PC": "FC 4 17-30 / 20-40 PC",
    "CRD PL precision build": "CRD PL ਸਟੀਕ ਬਣਤਰ",
    "Outdoor high-throw lighting": "ਬਾਹਰ ਦੂਰ ਤੱਕ ਰੋਸ਼ਨੀ",
    "Appliances": "ਉਪਕਰਨ",
    "Junction Box": "ਜੰਕਸ਼ਨ ਬਾਕਸ",
    "Accessories": "ਸਹਾਇਕ ਸਮਾਨ",
    "SRV Switch 16A scanned": "SRV ਸਵਿੱਚ 16A ਸਕੈਨ ਹੋਇਆ",
    "Cashback redeemed": "ਕੈਸ਼ਬੈਕ ਲਿਆ ਗਿਆ",
    "Referral bonus earned": "ਰੈਫ਼ਰਲ ਬੋਨਸ ਮਿਲਿਆ",
    "Verify Phone Number": "ਫ਼ੋਨ ਨੰਬਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    "Please wait...": "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
    "Enter OTP": "OTP ਭਰੋ",
    "Send OTP": "OTP ਭੇਜੋ",
    "Verify OTP": "OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    "No readable QR code was found in this image. Please choose a clear, uncropped QR image.": "ਇਸ ਤਸਵੀਰ ਵਿੱਚ ਪੜ੍ਹਨਯੋਗ QR ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ। ਸਾਫ਼ ਅਤੇ ਪੂਰੇ QR ਕੋਡ ਵਾਲੀ ਤਸਵੀਰ ਚੁਣੋ।"
  }
};
