// Generated from static tx(...) UI labels.
export const generatedUiText: Record<'Hindi' | 'Punjabi', Record<string, string>> = {
  "Hindi": {
    "Enter complete delivery address": "पूरा डिलीवरी पता दर्ज करें",
    "images": "तस्वीरें",
    "Swipe to view": "देखने के लिए स्वाइप करें",
    "Welcome": "स्वागत है",
    "You can explore the home page as a guest. Login or create an account to use all app features.": "आप अतिथि के रूप में होम पेज देख सकते हैं। सभी ऐप सुविधाओं का उपयोग करने के लिए लॉगिन करें या खाता बनाएँ।",
    "Back": "पीछे",
    "SUPPORT": "सहायता",
    "Clear All": "सभी साफ करें",
    "Notification Details": "अधिसूचना विवरण",
    "This will hide all current notifications only for your account.": "यह केवल आपके खाते के लिए सभी मौजूदा सूचनाएं छिपाएगा।",
    "updates": "अपडेट",
    "No notifications yet": "अभी तक कोई सूचना नहीं",
    "Clear all notifications": "सभी सूचनाएं साफ़ करें",
    "Pts.": "अंक.",
    "Clear": "स्पष्ट",
    "You need": "आप की जरूरत है",
    "Minimum Points Required": "न्यूनतम अंक आवश्यक",
    "You're all caught up. New updates will appear here.": "आप सब फंस गए हैं। नए अपडेट यहां दिखाई देंगे.",
    "Out of Stock": "स्टॉक ख़त्म",
    "You need at least 100 points to redeem. You have": "भुनाने के लिए आपको कम से कम 100 अंक चाहिए। आपके पास",
    "points. Keep scanning to earn more!": "अंक. अधिक कमाने के लिए स्कैन करते रहें!",
    "pts but have": "पीटी लेकिन है",
    "Not Enough Points": "पर्याप्त अंक नहीं",
    "Your request for": "के लिए आपका अनुरोध",
    "pts. Keep scanning to unlock this gift!": "पीटी. इस उपहार को अनलॉक करने के लिए स्कैन करते रहें!",
    "points from your wallet.": "आपके बटुए से अंक.",
    "This will use": "ये उपयोग होगा",
    "This gift is currently out of stock. Check back soon!": "यह उपहार फिलहाल स्टॉक से बाहर है. जल्दी वापस जाँच करें!",
    "Gift Order Requested": "उपहार आदेश का अनुरोध किया गया",
    "Redemption Failed": "मोचन विफल",
    "Check back soon!": "जल्दी वापस जाँच करें!",
    "has been submitted. SRV team will process it shortly.": "प्रस्तुत किया गया है। एसआरवी टीम शीघ्र ही इस पर कार्रवाई करेगी।",
    "No scans yet": "अभी तक कोई स्कैन नहीं",
    "Scan verification failed": "स्कैन सत्यापन विफल रहा",
    "Your Points": "आपके अंक",
    "No gifts available": "कोई उपहार उपलब्ध नहीं",
    "Multi": "मल्टी",
    "Single": "अकेला",
    "Scan & earn to redeem gifts": "उपहार भुनाने के लिए स्कैन करें और कमाएँ",
    "Invalid QR Code": "अमान्य क्यूआर कोड",
    "Verified": "सत्यापित",
    "The camera could not start. Close the scanner and try again.": "कैमरा प्रारंभ नहीं हो सका. स्कैनर बंद करें और पुनः प्रयास करें।",
    "Scan one product, get instant points credited to your account": "एक उत्पाद को स्कैन करें, अपने खाते में तुरंत अंक प्राप्त करें",
    "Scan at least one SRV product before finishing.": "ख़त्म करने से पहले कम से कम एक SRV उत्पाद को स्कैन करें।",
    "This QR was already redeemed. First scan details are shown below.": "यह QR पहले ही भुना लिया गया था. प्रथम स्कैन विवरण नीचे दिखाया गया है।",
    "Points for this QR were already claimed.": "इस क्यूआर के लिए अंकों का दावा पहले ही किया जा चुका था।",
    "This QR is not registered with SRV products.": "यह क्यूआर एसआरवी उत्पादों के साथ पंजीकृत नहीं है।",
    "Points credited to your wallet!": "अंक आपके बटुए में जमा किए गए!",
    "Keep scanning multiple products and finish batch when you're done": "अनेक उत्पादों को स्कैन करते रहें और जब आपका काम पूरा हो जाए तो बैच समाप्त करें",
    "Phone": "फ़ोन",
    "Not available": "उपलब्ध नहीं है",
    "Dealer Name": "डीलर का नाम",
    "Date & Time": "दिनांक समय",
    "Scanned By": "द्वारा स्कैन किया गया",
    "Items": "सामान",
    "Scan Summary": "सारांश स्कैन करें",
    "Points": "अंक",
    "Dealer Phone": "डीलर फ़ोन",
    "On": "पर",
    "Light": "रोशनी",
    "Call Us": "हमें कॉल करें",
    "Continue Scanning": "स्कैनिंग जारी रखें",
    "Chat with us on WhatsApp": "हमारे साथ व्हाट्सएप पर चैट करें",
    "Email Us": "हमें ईमेल करें",
    "All Scanned Items": "सभी स्कैन किए गए आइटम",
    "First scanner details are hidden.": "प्रथम स्कैनर विवरण छिपा हुआ है.",
    "Start scanning products to build your batch": "अपना बैच बनाने के लिए उत्पादों को स्कैन करना प्रारंभ करें",
    "Speak directly to our support team": "हमारी सहायता टीम से सीधे बात करें",
    "Get in Touch": "संपर्क में रहो",
    "Have a question or need assistance? We are just a tap away.": "क्या आपके पास कोई प्रश्न है या सहायता की आवश्यकता है? हम बस एक नल दूर हैं.",
    "Our team typically responds within 24 hours.": "हमारी टीम आमतौर पर 24 घंटों के भीतर जवाब देती है।",
    "electricians in your network": "आपके नेटवर्क में इलेक्ट्रीशियन",
    "No electricians yet": "अभी तक कोई इलेक्ट्रीशियन नहीं है",
    "Send us an email anytime": "हमें किसी भी समय एक ईमेल भेजें",
    "Associate electricians from the home screen to see them here.": "उन्हें यहां देखने के लिए होम स्क्रीन से इलेक्ट्रीशियन को संबद्ध करें।",
    "Unable to save electrician right now. Please check the details and try again.": "अभी इलेक्ट्रीशियन को बचाने में असमर्थ. कृपया विवरण जांचें और पुनः प्रयास करें।",
    "Add electrician failed": "इलेक्ट्रीशियन जोड़ें विफल",
    "Unable to load wallet activity": "वॉलेट गतिविधि लोड करने में असमर्थ",
    "Review connected electricians and monitor their network activity from one place.": "कनेक्टेड इलेक्ट्रीशियन की समीक्षा करें और एक ही स्थान से उनकी नेटवर्क गतिविधि की निगरानी करें।",
    "Inactive Electricians": "निष्क्रिय इलेक्ट्रीशियन",
    "Network filter": "नेटवर्क फ़िल्टर",
    "Total Network": "कुल नेटवर्क",
    "Check active and inactive electricians by joining month": "माह से जुड़कर सक्रिय व निष्क्रिय बिजली मिस्त्रियों की जांच करें",
    "Wallet history, withdrawal requests and your 5% bonus": "वॉलेट इतिहास, निकासी अनुरोध और आपका 5% बोनस",
    "Electrician activity": "इलेक्ट्रीशियन गतिविधि",
    "Wallet balance": "बटुआ शेष",
    "No electricians connected yet. Add your first electrician!": "अभी तक कोई इलेक्ट्रीशियन नहीं जुड़ा है. अपना पहला इलेक्ट्रीशियन जोड़ें!",
    "Withdrawals": "निकासी",
    "View wallet & withdrawals": "वॉलेट और निकासी देखें",
    "No withdrawal requests yet.": "अभी तक कोई निकासी अनुरोध नहीं.",
    "Balance": "संतुलन",
    "Wallet transaction": "वॉलेट लेनदेन",
    "Withdrawal requests & 5% bonus": "निकासी अनुरोध और 5% बोनस",
    "5% bonus credited": "5% बोनस जमा किया गया",
    "Expected 5% bonus after approval": "अनुमोदन के बाद 5% बोनस की उम्मीद है",
    "Saving...": "सहेजा जा रहा है...",
    "points": "अंक",
    "Wallet history": "बटुआ इतिहास",
    "No wallet activity yet.": "अभी तक कोई वॉलेट गतिविधि नहीं.",
    "This electrician will be saved directly to your dealer network in the live database.": "यह इलेक्ट्रीशियन लाइव डेटाबेस में सीधे आपके डीलर नेटवर्क में सहेजा जाएगा।",
    "Punjabi": "पंजाबी",
    "Something went wrong. Please try again.": "कुछ गलत हो गया। कृपया पुन: प्रयास करें।",
    "English": "अंग्रेज़ी",
    "Hindi": "हिंदी",
    "Enter the OTP sent to your mobile number.": "आपके मोबाइल नंबर पर भेजा गया ओटीपी दर्ज करें।",
    "Your current grading is based on total reward points earned through scans and redemptions.": "आपकी वर्तमान ग्रेडिंग स्कैन और रिडेम्पशन के माध्यम से अर्जित कुल इनाम अंकों पर आधारित है।",
    "Invalid Mobile Number": "अमान्य मोबाइल नंबर",
    "OTP Required": "ओटीपी आवश्यक",
    "Could not create account": "खाता नहीं बनाया जा सका",
    "Could not send OTP": "ओटीपी नहीं भेजा जा सका",
    "Password Required": "पासवर्ड आवश्यक",
    "Password Mismatch": "पासवर्ड बेमेल",
    "You can now login with your new password.": "अब आप अपने नए पासवर्ड से लॉगिन कर सकते हैं।",
    "Now create your new password.": "अब अपना नया पासवर्ड बनाएं.",
    "Passwords do not match. Please re-enter the same password.": "सांकेतिक शब्द मेल नहीं खाते। कृपया वही पासवर्ड पुनः दर्ज करें.",
    "OTP Verification Required": "ओटीपी सत्यापन आवश्यक है",
    "Please verify OTP before updating password.": "कृपया पासवर्ड अपडेट करने से पहले ओटीपी सत्यापित करें।",
    "Electrician Login": "इलेक्ट्रीशियन लॉगिन",
    "Choose a secure login method and continue with your account.": "एक सुरक्षित लॉगिन विधि चुनें और अपने खाते को जारी रखें।",
    "Password Updated": "पासवर्ड अपडेट किया गया",
    "Could not reset password": "पासवर्ड रीसेट नहीं किया जा सका",
    "Create Electrician Account": "इलेक्ट्रीशियन खाता बनाएं",
    "Dealer number cannot be same as your phone number. Please enter a different dealer number.": "डीलर नंबर आपके फ़ोन नंबर के समान नहीं हो सकता. कृपया कोई भिन्न डीलर नंबर दर्ज करें.",
    "Create Dealer Account": "डीलर खाता बनाएं",
    "Complete the account setup flow and create your electrician profile.": "खाता सेटअप प्रक्रिया पूरी करें और अपनी इलेक्ट्रीशियन प्रोफ़ाइल बनाएं।",
    "Counter Boy Login": "काउंटर बॉय लॉगिन",
    "Choose a secure login method and continue with your dealer account.": "एक सुरक्षित लॉगिन विधि चुनें और अपने डीलर खाते को जारी रखें।",
    "Dealer Login": "डीलर लॉगिन",
    "Choose a secure login method and continue with your counter boy account.": "एक सुरक्षित लॉगिन विधि चुनें और अपने काउंटर बॉय खाते को जारी रखें।",
    "Forgot Password?": "पासवर्ड भूल गए?",
    "Complete the account setup flow and create your dealer profile.": "खाता सेटअप प्रवाह पूरा करें और अपनी डीलर प्रोफ़ाइल बनाएं।",
    "Email Address (Optional)": "ईमेल पता (वैकल्पिक)",
    "District": "ज़िला",
    "Create Counter Boy Account": "काउंटर बॉय अकाउंट बनाएं",
    "Referral Code (Optional)": "रेफरल कोड (वैकल्पिक)",
    "Complete the account setup flow and create your counter boy profile.": "खाता सेटअप प्रवाह पूरा करें और अपना काउंटर बॉय प्रोफ़ाइल बनाएं।",
    "Enter your friend’s referral code": "अपने मित्र का रेफरल कोड दर्ज करें",
    "Complete the account setup flow and create your profile.": "खाता सेटअप प्रवाह पूरा करें और अपनी प्रोफ़ाइल बनाएं।",
    "GST / PAN Number": "जीएसटी/पैन नंबर",
    "Forgot Password": "पासवर्ड भूल गए",
    "Business Name *": "व्यवसाय का नाम *",
    "After signup, you and your friend will each receive 20 points.": "साइनअप के बाद, आपको और आपके मित्र को 20 अंक प्राप्त होंगे।",
    "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
    "OTP verified. Now create a new password for your account.": "ओटीपी सत्यापित. अब अपने अकाउंट के लिए एक नया पासवर्ड बनाएं।",
    "Create a password (minimum 8 characters)": "एक पासवर्ड बनाएं (न्यूनतम 8 अक्षर)",
    "Password skipped. Accept the terms below to continue.": "पासवर्ड छोड़ दिया गया. जारी रखने के लिए नीचे दी गई शर्तें स्वीकार करें।",
    "Please wait...": "कृपया प्रतीक्षा करें...",
    "Product Details": "उत्पाद विवरण",
    "Out of stock": "स्टॉक ख़त्म",
    "Enter and verify the OTP sent to your mobile number.": "अपने मोबाइल नंबर पर भेजे गए ओटीपी को दर्ज करें और सत्यापित करें।",
    "Enter your registered mobile number to receive an OTP.": "ओटीपी प्राप्त करने के लिए अपना पंजीकृत मोबाइल नंबर दर्ज करें।",
    "Earn": "कमाना",
    "Free delivery": "नि: शुल्क डिलिवरी",
    "Available Offers": "उपलब्ध ऑफर",
    "SKU": "एसकेयू",
    "Re-enter new password": "नया पासवर्ड पुनः दर्ज करें",
    "Weight": "वज़न",
    "Use COD, Razorpay, or wallet points at checkout.": "चेकआउट के समय सीओडी, रेज़रपे या वॉलेट पॉइंट का उपयोग करें।",
    "SRV Assured": "एसआरवी ने आश्वासन दिया",
    "Standard": "मानक",
    "reward points on this product.": "इस उत्पाद पर इनाम अंक।",
    "instant discount compared with MRP.": "एमआरपी की तुलना में तत्काल छूट।",
    "Related Products": "संबंधित उत्पाद",
    "Add to Cart": "कार्ट में जोड़ें",
    "Qty": "मात्रा",
    "Login / Signup": "लॉगइन साइनअप",
    "Description": "विवरण",
    "You may also like": "आपको यह भी पसंद आ सकता हैं",
    "Added to cart": "कार्ट में जोड़ा गया",
    "Login required": "लॉगिन आवश्यक है",
    "SRV product details will appear here once updated from SRV Team.": "एसआरवी उत्पाद विवरण एसआरवी टीम से अपडेट होने के बाद यहां दिखाई देंगे।",
    "Product added to your cart.": "उत्पाद आपके कार्ट में जोड़ा गया.",
    "Your product order has been sent to SRV Team.": "आपका उत्पाद ऑर्डर एसआरवी टीम को भेज दिया गया है।",
    "Top matches": "शीर्ष मैच",
    "Order failed": "आदेश विफल",
    "Cart update failed": "कार्ट अद्यतन विफल रहा",
    "results for": "के परिणाम",
    "Loading...": "लोड हो रहा है...",
    "Please login or signup to continue with this product.": "कृपया इस उत्पाद को जारी रखने के लिए लॉगिन या साइनअप करें।",
    "Open cart": "खुली गाड़ी",
    "No products found": "कोई उत्पाद नहीं मिला",
    "SRV Electricals — since 2000. Explore the latest SRV product range and offers.": "एसआरवी इलेक्ट्रिकल्स - 2000 से। नवीनतम एसआरवी उत्पाद रेंज और ऑफ़र का अन्वेषण करें।",
    "Choose a category to see matching products.": "मेल खाते उत्पाद देखने के लिए एक श्रेणी चुनें।",
    "points. Your bonus grows as your electricians redeem more!": "अंक. जैसे-जैसे आपके इलेक्ट्रीशियन अधिक भुगतान करते हैं, आपका बोनस बढ़ता जाता है!",
    "products available": "उत्पाद उपलब्ध हैं",
    "points. Scan SRV products to earn more!": "अंक. अधिक कमाने के लिए SRV उत्पादों को स्कैन करें!",
    "Loading products...": "उत्पाद लोड हो रहे हैं...",
    "Gift Order Requested!": "उपहार आदेश का अनुरोध किया गया!",
    "Next": "अगला",
    "Quick Actions": "त्वरित कार्रवाई",
    "Already Scanned": "पहले ही स्कैन किया जा चुका है",
    "Scan products to earn more": "अधिक कमाने के लिए उत्पादों को स्कैन करें",
    "Login or Signup": "लॉग इन या साइन अप",
    "What you unlock after login": "लॉगिन करने के बाद आप क्या अनलॉक करते हैं",
    "Back to Home": "घर वापिस जा रहा हूँ",
    "Use another number": "दूसरे नंबर का प्रयोग करें",
    "This QR code has already been redeemed. Original scan details are shown below.": "यह QR कोड पहले ही रिडीम किया जा चुका है. मूल स्कैन विवरण नीचे दिखाए गए हैं।",
    "pts. Keep growing your electrician network to unlock this gift!": "पीटी. इस उपहार को अनलॉक करने के लिए अपने इलेक्ट्रीशियन नेटवर्क को बढ़ाते रहें!",
    "Dealer account access": "डीलर खाते तक पहुंच",
    "Login or signup to access this feature": "इस सुविधा तक पहुंचने के लिए लॉगिन या साइनअप करें",
    "Chat on WhatsApp": "व्हाट्सएप पर चैट करें",
    "Partners": "भागीदारों",
    "Electrician account access": "इलेक्ट्रीशियन खाते तक पहुंच",
    "Welcome Dealer": "आपका स्वागत है डीलर",
    "Members": "सदस्यों",
    "Login or create your dealer account to unlock profile tools, network details and business controls.": "प्रोफ़ाइल टूल, नेटवर्क विवरण और व्यवसाय नियंत्रण अनलॉक करने के लिए लॉगिन करें या अपना डीलर खाता बनाएं।",
    "Login or create your electrician account to unlock rewards, scan history and your complete profile.": "पुरस्कार अनलॉक करने, इतिहास और अपनी पूरी प्रोफ़ाइल स्कैन करने के लिए लॉगिन करें या अपना इलेक्ट्रीशियन खाता बनाएं।",
    "Welcome Electrician": "इलेक्ट्रीशियन का स्वागत है",
    "Get Started": "शुरू हो जाओ",
    "Upload failed": "अपलोड विफल रहा",
    "Switch Your Role": "अपनी भूमिका बदलें",
    "Login to Account": "खाते में लॉगिन करें",
    "Track rewards, scans and profile progress with your SRV account.": "अपने एसआरवी खाते से पुरस्कार, स्कैन और प्रोफ़ाइल प्रगति को ट्रैक करें।",
    "Manage business growth, connected electricians and dealer tools in one place.": "व्यवसाय वृद्धि, कनेक्टेड इलेक्ट्रीशियन और डीलर टूल्स को एक ही स्थान पर प्रबंधित करें।",
    "Error": "गलती",
    "Could not read this image. Please choose another one.": "इस छवि को पढ़ नहीं सका. कृपया करके दूसरा चुनो।",
    "Payment details linked": "भुगतान विवरण लिंक किया गया",
    "Invalid Google Pay number": "अमान्य Google Pay नंबर",
    "Failed to save bank details. Please try again.": "बैंक विवरण सहेजने में विफल. कृपया पुन: प्रयास करें।",
    "Please enter a valid 10 digit Google Pay number.": "कृपया एक वैध 10 अंकीय Google Pay नंबर दर्ज करें।",
    "Google Pay Number": "गूगल पे नंबर",
    "Add Google Pay number and UPI ID for smooth payouts": "सहज भुगतान के लिए Google Pay नंबर और UPI आईडी जोड़ें",
    "Upload UPI QR Code": "यूपीआई क्यूआर कोड अपलोड करें",
    "Uploading...": "अपलोड हो रहा है...",
    "Select a clear square QR image from your gallery": "अपनी गैलरी से एक स्पष्ट वर्गाकार QR छवि चुनें",
    "UPI QR Code": "यूपीआई क्यूआर कोड",
    "Enter Google Pay Number": "Google Pay नंबर दर्ज करें",
    "Replace QR image": "QR छवि बदलें",
    "Invalid amount": "अमान्य राशि",
    "Linked account": "लिंक किया गया खाता",
    "Please add your bank details first.": "कृपया पहले अपना बैंक विवरण जोड़ें.",
    "Bank details required": "बैंक विवरण आवश्यक है",
    "Request failed": "अनुरोध विफल रहा",
    "Request dealer bonus payout": "डीलर बोनस भुगतान का अनुरोध करें",
    "Requested points cannot be more than your available balance.": "अनुरोधित अंक आपके उपलब्ध शेष से अधिक नहीं हो सकते।",
    "points withdrawal request has been sent for SRV Team approval.": "अंक वापसी अनुरोध एसआरवी टीम अनुमोदन के लिए भेजा गया है।",
    "Available Dealer Bonus": "उपलब्ध डीलर बोनस",
    "Available Points": "उपलब्ध अंक",
    "1 point = 1 INR payout request": "1 अंक = 1 INR भुगतान अनुरोध",
    "Enter how many points you want in your bank account. SRV Team will review and transfer the payout manually.": "आप अपने बैंक खाते में कितने अंक चाहते हैं, दर्ज करें। एसआरवी टीम भुगतान की समीक्षा करेगी और मैन्युअल रूप से ट्रांसफर करेगी।",
    "Requested amount cannot be more than your available dealer bonus.": "अनुरोधित राशि आपके उपलब्ध डीलर बोनस से अधिक नहीं हो सकती।",
    "Linked bank account": "लिंक किया गया बैंक खाता",
    "Account Holder": "खाताधारक",
    "Add bank details before raising a withdrawal request": "निकासी अनुरोध करने से पहले बैंक विवरण जोड़ें",
    "Edit Bank Details": "बैंक विवरण संपादित करें",
    "withdrawal request has been sent for SRV Team approval.": "वापसी अनुरोध एसआरवी टीम अनुमोदन के लिए भेजा गया है।",
    "Enter the dealer bonus amount you want in your bank account. SRV Team will review and transfer it manually.": "अपने बैंक खाते में इच्छित डीलर बोनस राशि दर्ज करें। एसआरवी टीम इसकी समीक्षा करेगी और इसे मैन्युअल रूप से स्थानांतरित करेगी।",
    "No account holder saved yet.": "अभी तक कोई खाताधारक सहेजा नहीं गया.",
    "Withdrawal amount": "निकासी राशि",
    "Call": "पुकारना",
    "Add Bank Details": "बैंक विवरण जोड़ें",
    "Head Office": "प्रधान कार्यालय",
    "Enter points amount": "अंक राशि दर्ज करें",
    "Points to withdraw": "वापस लेने के लिए अंक",
    "Submit transfer request": "स्थानांतरण अनुरोध सबमिट करें",
    "Email support at": "पर ईमेल समर्थन",
    "Call support at": "सहायता को यहां कॉल करें",
    "What is SRV Electricals?": "एसआरवी इलेक्ट्रिकल्स क्या है?",
    "Which products are available in the app?": "ऐप में कौन से उत्पाद उपलब्ध हैं?",
    "Where can I see my points and wallet history?": "मैं अपने पॉइंट और वॉलेट इतिहास कहाँ देख सकता हूँ?",
    "How do QR rewards work?": "क्यूआर पुरस्कार कैसे काम करते हैं?",
    "Open Wallet from the bottom navigation to view your available balance and transaction history. Pull down to refresh if you have just scanned a QR code or received transferred points.": "अपने उपलब्ध शेष और लेनदेन इतिहास को देखने के लिए नीचे नेविगेशन से वॉलेट खोलें। यदि आपने अभी-अभी एक क्यूआर कोड स्कैन किया है या स्थानांतरित अंक प्राप्त किए हैं तो रीफ्रेश करने के लिए नीचे खींचें।",
    "Sign in with the correct role, open the scanner and scan the genuine QR code printed on an eligible SRV product. Valid points are credited to your wallet after successful verification. Each QR code can be redeemed only once.": "सही भूमिका के साथ साइन इन करें, स्कैनर खोलें और योग्य एसआरवी उत्पाद पर मुद्रित वास्तविक क्यूआर कोड को स्कैन करें। सफल सत्यापन के बाद वैध अंक आपके वॉलेट में जमा कर दिए जाते हैं। प्रत्येक QR कोड को केवल एक बार रिडीम किया जा सकता है।",
    "How can I redeem a gift?": "मैं किसी उपहार को कैसे भुना सकता हूँ?",
    "Which payment methods are supported?": "कौन सी भुगतान विधियाँ समर्थित हैं?",
    "SRV Electricals is an Indian electrical-products manufacturer established in 2000. The company supplies reliable products for residential, commercial and industrial installations.": "एसआरवी इलेक्ट्रिकल्स 2000 में स्थापित एक भारतीय विद्युत-उत्पाद निर्माता है। कंपनी आवासीय, वाणिज्यिक और औद्योगिक प्रतिष्ठानों के लिए विश्वसनीय उत्पादों की आपूर्ति करती है।",
    "Open Gift Store, select a gift available for your role, confirm that you have enough points and submit the redemption. Gift redemptions and their delivery updates are shown separately under Gift Store Order.": "उपहार स्टोर खोलें, अपनी भूमिका के लिए उपलब्ध उपहार का चयन करें, पुष्टि करें कि आपके पास पर्याप्त अंक हैं और मोचन जमा करें। उपहार मोचन और उनके वितरण अपडेट उपहार स्टोर ऑर्डर के अंतर्गत अलग से दिखाए जाते हैं।",
    "You can browse fan boxes, concealed and modular boxes, MCB distribution boxes, bus bars, ventilation and industrial fans, stabilizers, switchgear, lighting products and other electrical accessories.": "आप पंखे के बक्से, छुपाए गए और मॉड्यूलर बक्से, एमसीबी वितरण बक्से, बस बार, वेंटिलेशन और औद्योगिक पंखे, स्टेबलाइजर्स, स्विचगियर, प्रकाश उत्पाद और अन्य विद्युत सहायक उपकरण ब्राउज़ कर सकते हैं।",
    "Closing the payment window does not confirm an order and no successful purchase will appear in My Orders. You can return to checkout and try again whenever you are ready.": "भुगतान विंडो बंद करने से ऑर्डर की पुष्टि नहीं होती है और कोई भी सफल खरीदारी मेरे ऑर्डर में दिखाई नहीं देगी। आप चेकआउट पर वापस लौट सकते हैं और जब भी आप तैयार हों तो पुनः प्रयास कर सकते हैं।",
    "How can I cancel, return or request a refund?": "मैं कैसे रद्द कर सकता हूं, वापसी कर सकता हूं या धनवापसी का अनुरोध कैसे कर सकता हूं?",
    "Online product purchases are processed securely through Razorpay using supported UPI, card, netbanking or wallet options. An order is confirmed only after the payment is successfully verified.": "समर्थित यूपीआई, कार्ड, नेटबैंकिंग या वॉलेट विकल्पों का उपयोग करके रेज़रपे के माध्यम से ऑनलाइन उत्पाद खरीदारी को सुरक्षित रूप से संसाधित किया जाता है। भुगतान सफलतापूर्वक सत्यापित होने के बाद ही ऑर्डर की पुष्टि की जाती है।",
    "What happens if I cancel or close Razorpay?": "यदि मैं रेज़रपे को रद्द या बंद कर दूं तो क्या होगा?",
    "How do I contact support?": "मैं सहायता से कैसे संपर्क करूं?",
    "What should I do if an OTP is delayed?": "यदि ओटीपी आने में देरी हो तो मुझे क्या करना चाहिए?",
    "Where can I download the latest catalogue?": "मैं नवीनतम कैटलॉग कहां से डाउनलोड कर सकता हूं?",
    "Open My Orders, select the relevant product order and choose an available action. Cancellation is available for eligible active orders, while returns and refunds depend on delivery and payment status. Add a clear reason before submitting.": "मेरे ऑर्डर खोलें, प्रासंगिक उत्पाद ऑर्डर चुनें और एक उपलब्ध कार्रवाई चुनें। पात्र सक्रिय ऑर्डर के लिए रद्दीकरण उपलब्ध है, जबकि रिटर्न और रिफंड डिलीवरी और भुगतान की स्थिति पर निर्भर करते हैं। सबमिट करने से पहले एक स्पष्ट कारण जोड़ें.",
    "Tap Product Catalog on the home page to open the latest SRV catalogue. The catalogue contains the current product range and is updated by SRV administrators.": "नवीनतम एसआरवी कैटलॉग खोलने के लिए होम पेज पर उत्पाद कैटलॉग पर टैप करें। कैटलॉग में वर्तमान उत्पाद श्रेणी शामिल है और इसे SRV प्रशासकों द्वारा अद्यतन किया जाता है।",
    "Confirm that the mobile number is correct, wait for the SMS and use only the latest OTP within its validity period. If it expires, request a fresh OTP and avoid pressing Verify more than once.": "पुष्टि करें कि मोबाइल नंबर सही है, एसएमएस की प्रतीक्षा करें और इसकी वैधता अवधि के भीतर केवल नवीनतम ओटीपी का उपयोग करें। यदि यह समाप्त हो जाता है, तो एक नए ओटीपी का अनुरोध करें और एक से अधिक बार सत्यापित करें दबाने से बचें।",
    "KYC Verification": "केवाईसी सत्यापन",
    "Use the phone, WhatsApp or email options in Contact Us, or open Need Help to create a support ticket. Include your registered mobile number and order or QR details so the team can assist quickly.": "हमसे संपर्क करें में फ़ोन, व्हाट्सएप या ईमेल विकल्पों का उपयोग करें, या सहायता टिकट बनाने के लिए सहायता चाहिए खोलें। अपना पंजीकृत मोबाइल नंबर और ऑर्डर या क्यूआर विवरण शामिल करें ताकि टीम शीघ्र सहायता कर सके।",
    "Rejection Reason": "अस्वीकृति का कारण",
    "KYC Status": "केवाईसी स्थिति",
    "Ready to Resubmit": "पुनः सबमिट करने के लिए तैयार",
    "Failed to submit KYC documents. Please try again.": "केवाईसी दस्तावेज़ जमा करने में विफल. कृपया पुन: प्रयास करें।",
    "Please upload either PAN Card or GST Number": "कृपया पैन कार्ड या जीएसटी नंबर अपलोड करें",
    "Please upload Aadhar Card": "कृपया आधार कार्ड अपलोड करें",
    "Required Documents": "आवश्यक दस्तावेज",
    "Aadhar Card": "आधार कार्ड",
    "Upload Aadhar Card and either PAN Card or GST Number for verification": "सत्यापन के लिए आधार कार्ड और पैन कार्ड या जीएसटी नंबर अपलोड करें",
    "Your updated documents are ready. Tap submit to send them for fresh SRV Team review.": "आपके अद्यतन दस्तावेज़ तैयार हैं. उन्हें नई एसआरवी टीम समीक्षा के लिए भेजने के लिए सबमिट पर टैप करें।",
    "Submitting...": "सबमिट किया जा रहा है...",
    "Please try again later.": "कृपया बाद में पुन: प्रयास करें।",
    "Completion Progress": "समापन प्रगति",
    "Order Updates": "ऑर्डर अपडेट",
    "Order": "आदेश",
    "Upload Aadhar Card for KYC verification": "केवाईसी सत्यापन के लिए आधार कार्ड अपलोड करें",
    "Choose one from both PAN Card or GST Number": "पैन कार्ड या जीएसटी नंबर दोनों में से एक चुनें",
    "Gift": "उपहार",
    "Reason": "कारण",
    "Tracking ID": "ट्रैकिंग आईडी",
    "Sending": "भेजा जा रहा है",
    "PAN Card or GST Number": "पैन कार्ड या जीएसटी नंबर",
    "SRV's promises": "एसआरवी के वादे",
    "No product orders found yet.": "अभी तक कोई उत्पाद ऑर्डर नहीं मिला.",
    "No orders found for this filter.": "इस फ़िल्टर के लिए कोई ऑर्डर नहीं मिला.",
    "Tell us why you want to cancel, return or refund": "हमें बताएं कि आप क्यों रद्द करना, वापसी या धनवापसी करना चाहते हैं",
    "This reason is shared with the order support team.": "यह कारण ऑर्डर सपोर्ट टीम के साथ साझा किया गया है।",
    "Delivery Executive details will be available once the order is out for delivery": "डिलीवरी के लिए ऑर्डर निकलने के बाद डिलीवरी एक्जीक्यूटिव विवरण उपलब्ध होंगे",
    "Expected Delivery": "अपेक्षित सुपुर्दगी",
    "Courier Partner": "कूरियर पार्टनर",
    "Total Requests": "कुल अनुरोध",
    "Delivery Address": "डिलिवरी का पता",
    "Load more orders": "अधिक ऑर्डर लोड करें",
    "Reward redemption": "इनाम मोचन",
    "Gift Order Details": "उपहार ऑर्डर विवरण",
    "Gift Store Order": "उपहार स्टोर ऑर्डर",
    "Loading your orders...": "आपके ऑर्डर लोड हो रहे हैं...",
    "Address saved with order": "आदेश के साथ पता सहेजा गया",
    "Your future redemption activity will appear here.": "आपकी भविष्य की मोचन गतिविधि यहां दिखाई देगी।",
    "No redemption history yet": "अभी तक कोई मोचन इतिहास नहीं",
    "Photo limit reached": "फ़ोटो की सीमा पूरी हो गई",
    "Could not send reply. Please try again.": "उत्तर नहीं भेजा जा सका. कृपया पुन: प्रयास करें।",
    "You can attach up to 5 photos.": "आप अधिकतम 5 फ़ोटो संलग्न कर सकते हैं.",
    "Your request has been submitted successfully.": "आपका अनुरोध सफलतापूर्वक सबमिट कर दिया गया है.",
    "Ticket Closed": "टिकट बंद",
    "We could not submit your request right now. Please try again.": "हम अभी आपका अनुरोध सबमिट नहीं कर सके. कृपया पुन: प्रयास करें।",
    "Photos ready": "तस्वीरें तैयार",
    "In Progress": "प्रगति पर है",
    "Resolved": "हल किया",
    "Closed": "बंद किया हुआ",
    "WhatsApp chat has opened on the SRV number. Please attach the selected photos manually inside WhatsApp.": "एसआरवी नंबर पर व्हाट्सएप चैट खुल गई है। कृपया चयनित फ़ोटो को व्हाट्सएप के अंदर मैन्युअल रूप से संलग्न करें।",
    "Could not close ticket. Please try again.": "टिकट बंद नहीं किया जा सका. कृपया पुन: प्रयास करें।",
    "Just now": "बस अब",
    "Created": "बनाया था",
    "Delete message": "संदेश को हटाएं",
    "Delete": "मिटाना",
    "Could not delete message. Please try again.": "संदेश हटाया नहीं जा सका. कृपया पुन: प्रयास करें।",
    "Your ticket has been closed.": "आपका टिकट बंद कर दिया गया है.",
    "Continue on WhatsApp": "व्हाट्सएप पर जारी रखें",
    "Your reply is sent securely": "आपका उत्तर सुरक्षित रूप से भेजा गया है",
    "Do you want to delete this message?": "क्या आप यह संदेश हटाना चाहते हैं?",
    "Type a message...": "एक संदेश टाइप करें...",
    "This ticket is closed": "यह टिकट बंद है",
    "Reply to support": "समर्थन का उत्तर दें",
    "Ticket closed": "टिकट बंद",
    "My Tickets": "मेरे टिकट",
    "New Request": "नया अनुरोध",
    "You cannot send more messages": "आप अधिक संदेश नहीं भेज सकते",
    "Are you sure you want to close this ticket?": "क्या आप वाकई यह टिकट बंद करना चाहते हैं?",
    "Photos": "तस्वीरें",
    "Remove photo": "फ़ोटो हटाएँ",
    "Add more": "अधिक जोड़ें",
    "Close Ticket": "टिकट बंद करें",
    "Closing...": "समापन...",
    "Submit Request": "अनुरोध सबमिट करें",
    "Add multiple photos": "एकाधिक फ़ोटो जोड़ें",
    "Upload Photos": "तस्वीरें अपलोड करें",
    "Support activity": "समर्थन गतिविधि",
    "Tap + to select and attach multiple photos": "एकाधिक फ़ोटो चुनने और संलग्न करने के लिए + टैप करें",
    "No tickets yet": "अभी तक कोई टिकट नहीं",
    "View details": "विवरण देखें",
    "replies": "जवाब",
    "Tap any ticket to view replies or close it.": "उत्तर देखने या उसे बंद करने के लिए किसी भी टिकट पर टैप करें।",
    "This saves your issue in the SRV system so SRV Team can track and resolve it.": "यह आपकी समस्या को एसआरवी सिस्टम में सहेजता है ताकि एसआरवी टीम इसे ट्रैक और हल कर सके।",
    "No notifications yet.": "अभी तक कोई सूचना नहीं.",
    "Create a new request to get help": "सहायता प्राप्त करने के लिए एक नया अनुरोध बनाएं",
    "Offer Details": "प्रस्ताव विवरण",
    "Add selected photos?": "चयनित फ़ोटो जोड़ें?",
    "Bumper Offer": "फटी छूट",
    "Valid till": "तक मान्य",
    "Discount": "छूट",
    "Open ticket": "खुला टिकट",
    "Special offer": "विशेष पेशकश",
    "Offer Validity": "प्रस्ताव की वैधता",
    "Bonus Points": "बोनस अंक",
    "Starts": "प्रारंभ होगा",
    "Available now": "अब उपलब्ध है",
    "Ends": "समाप्त होता है",
    "Category": "वर्ग",
    "Limited period offer": "सीमित अवधि की पेशकश",
    "End date will be updated soon": "अंतिम तिथि जल्द ही अपडेट की जाएगी",
    "Failed": "असफल",
    "will be transferred to your bank account after approval.": "अनुमोदन के बाद आपके बैंक खाते में स्थानांतरित कर दिया जाएगा।",
    "Offers coming soon": "ऑफर जल्द ही आ रहे हैं",
    "Link bank account first": "सबसे पहले बैंक अकाउंट लिंक करें",
    "New SRV offers and promotions will appear here as soon as they are available.": "नए एसआरवी ऑफ़र और प्रमोशन उपलब्ध होते ही यहां दिखाई देंगे।",
    "OTP sent successfully": "ओटीपी सफलतापूर्वक भेजा गया",
    "Total bonus earned": "कुल अर्जित बोनस",
    "Pending withdrawals": "लंबित निकासी",
    "Enter the OTP to continue.": "जारी रखने के लिए ओटीपी दर्ज करें।",
    "Could not send OTP. Please try again.": "ओटीपी नहीं भेजा जा सका. कृपया पुन: प्रयास करें।",
    "Invalid OTP. Please try again.": "अमान्य ओटीपी. कृपया पुन: प्रयास करें।",
    "Password Changed": "पासवर्ड बदला गया",
    "Please check your phone for the OTP": "कृपया ओटीपी के लिए अपना फोन जांचें",
    "Please enter both passwords same.": "कृपया दोनों पासवर्ड एक जैसे दर्ज करें।",
    "ACCOUNT SECURITY": "खाता सुरक्षा",
    "OTP verified successfully. Create your new password now.": "ओटीपी सफलतापूर्वक सत्यापित हो गया. अब अपना नया पासवर्ड बनाएं.",
    "You successfully changed your password.": "आपने सफलतापूर्वक अपना पासवर्ड बदल लिया है.",
    "Please request OTP first.": "कृपया पहले ओटीपी का अनुरोध करें।",
    "CREATE ACCESS  ->": "पहुंच बनाएं ->",
    "UPDATE SECURITY  ->": "अद्यतन सुरक्षा ->",
    "Password center": "पासवर्ड केंद्र",
    "Re-enter your password": "अपना पासवर्ड पुनः दर्ज करें",
    "Choose what you would like to do. Your account stays protected at every step.": "चुनें कि आप क्या करना चाहेंगे. आपका खाता हर कदम पर सुरक्षित रहता है.",
    "Password already set": "पासवर्ड पहले से ही सेट है",
    "Enter your current password": "अपने वर्तमान पासवर्ड को दर्ज करें",
    "Reset Password": "पासवर्ड रीसेट",
    "Use at least 8 characters for a secure password.": "सुरक्षित पासवर्ड के लिए कम से कम 8 अक्षरों का प्रयोग करें।",
    "Verify OTP sent to your phone, then create a new password.": "अपने फ़ोन पर भेजे गए OTP को सत्यापित करें, फिर एक नया पासवर्ड बनाएं।",
    "gifts": "उपहार",
    "Clear use of data": "डेटा का स्पष्ट उपयोग",
    "Policy updates shared": "नीति अद्यतन साझा किए गए",
    "Verify OTP to unlock new password fields.": "नए पासवर्ड फ़ील्ड अनलॉक करने के लिए ओटीपी सत्यापित करें।",
    "You have already set a password for your account. Use Change Password to update it, or use Forgot Password from the login screen.": "आपने अपने खाते के लिए पहले ही पासवर्ड सेट कर लिया है. इसे अपडेट करने के लिए पासवर्ड बदलें का उपयोग करें, या लॉगिन स्क्रीन से पासवर्ड भूल गए का उपयोग करें।",
    "Unable to save changes": "परिवर्तन सहेजने में असमर्थ",
    "Invalid district": "अमान्य जिला",
    "Save": "बचाना",
    "Save profile changes?": "प्रोफ़ाइल परिवर्तन सहेजें?",
    "Please enter a valid 10-digit phone number.": "कृपया एक वैध 10-अंकीय फ़ोन नंबर दर्ज करें।",
    "Edit Rating": "रेटिंग संपादित करें",
    "Rating not saved": "रेटिंग सहेजी नहीं गई",
    "Go to Home": "घर जाओ",
    "District should contain only alphabets and spaces.": "जिले में केवल अक्षर और रिक्त स्थान होने चाहिए।",
    "Welcome from SRV": "एसआरवी की ओर से आपका स्वागत है",
    "Rate your app experience": "अपने ऐप अनुभव को रेट करें",
    "Are you sure you want to update your profile details?": "क्या आप वाकई अपना प्रोफ़ाइल विवरण अपडेट करना चाहते हैं?",
    "Your feedback helps us improve. You can update it anytime.": "आपका फीडबैक सुधार में मददगार है। आप इसे कभी भी अपडेट कर सकते हैं.",
    "Copied": "कॉपी किया गया",
    "Tap once to choose your score": "अपना स्कोर चुनने के लिए एक बार टैप करें",
    "Referral app link copied successfully.": "रेफ़रल ऐप लिंक सफलतापूर्वक कॉपी किया गया.",
    "SRV Referral Rewards": "एसआरवी रेफरल पुरस्कार",
    "Invite a friend. Both earn points.": "किसी मित्र को आमंत्रित करें। दोनों अंक अर्जित करते हैं.",
    "Your review helps us improve support, rewards, orders, and daily app experience.": "आपकी समीक्षा से हमें समर्थन, पुरस्कार, ऑर्डर और दैनिक ऐप अनुभव को बेहतर बनाने में मदद मिलती है।",
    "Allow SRV to show this review in the app with my name and role. It may appear after 7 days.": "एसआरवी को इस समीक्षा को मेरे नाम और भूमिका के साथ ऐप में दिखाने की अनुमति दें। यह 7 दिनों के बाद दिखाई दे सकता है.",
    "Your Referral Code": "आपका रेफरल कोड",
    "Loading": "लोड हो रहा है",
    "Please try again in a moment.": "कृपया एक क्षण में पुनः प्रयास करें.",
    "Comment failed": "टिप्पणी विफल",
    "Unable to open": "खोलने में असमर्थ",
    "When your friend creates an account successfully from your referral, both of you receive 20 reward points.": "जब आपका मित्र आपके रेफरल से सफलतापूर्वक एक खाता बनाता है, तो आप दोनों को 20 इनाम अंक मिलते हैं।",
    "Copy App Link": "ऐप लिंक कॉपी करें",
    "Open": "खुला",
    "Instagram": "Instagram",
    "views": "दृश्य",
    "This video link cannot be opened on this device.": "यह वीडियो लिंक इस डिवाइस पर नहीं खोला जा सकता.",
    "Please login to like or comment on videos.": "कृपया वीडियो को पसंद करने या उस पर टिप्पणी करने के लिए लॉगिन करें।",
    "Show more": "और दिखाएँ",
    "Show less": "कम दिखाओ",
    "Loading videos...": "वीडियो लोड हो रहा है...",
    "Unable to preview this video": "इस वीडियो का पूर्वावलोकन करने में असमर्थ",
    "Comments": "टिप्पणियाँ",
    "No comments yet. Start the conversation.": "अब तक कोई टिप्पणी नहीं। बातचीत शुरू करें.",
    "Play Zone is temporarily disabled": "प्ले ज़ोन अस्थायी रूप से अक्षम है",
    "Admin Team": "एडमिन टीम",
    "No videos available yet": "अभी तक कोई वीडियो उपलब्ध नहीं है",
    "Login to comment": "टिप्पणी करने के लिए लॉगिन करें",
    "Add a comment...": "एक टिप्पणी जोड़ने...",
    "Posting": "प्रविष्टि",
    "Total Scans": "कुल स्कैन",
    "Send": "भेजना",
    "Points Earned": "अर्जित अंक",
    "SRV User": "एसआरवी उपयोगकर्ता",
    "Fresh videos for this profile will appear here once SRV Team uploads them.": "इस प्रोफ़ाइल के ताज़ा वीडियो एसआरवी टीम द्वारा अपलोड करने के बाद यहां दिखाई देंगे।",
    "Videos will appear here again once SRV Team enables Play Zone from settings.": "एक बार जब एसआरवी टीम सेटिंग्स से प्ले ज़ोन को सक्षम कर देगी तो वीडियो यहां फिर से दिखाई देंगे।",
    "Counter Boy": "काउंटर बॉय",
    "Not allowed": "अनुमति नहीं",
    "Only electricians and counter boys can transfer points.": "केवल इलेक्ट्रीशियन और काउंटर बॉय ही पॉइंट ट्रांसफर कर सकते हैं।",
    "No scans yet. Start scanning products to earn points!": "अभी तक कोई स्कैन नहीं. अंक अर्जित करने के लिए उत्पादों को स्कैन करना शुरू करें!",
    "Filter scan history": "स्कैन इतिहास फ़िल्टर करें",
    "No scan history found for this date.": "इस तिथि का कोई स्कैन इतिहास नहीं मिला.",
    "User not found with this number": "इस नंबर वाला उपयोगकर्ता नहीं मिला",
    "Invalid receiver": "अमान्य रिसीवर",
    "Invite link": "लिंक आमंत्रित करें",
    "Search first": "पहले खोजें",
    "You do not have enough points.": "आपके पास पर्याप्त अंक नहीं हैं.",
    "Transfer failed": "स्थानांतरण विफल रहा",
    "Enter valid points to transfer.": "स्थानांतरण के लिए वैध अंक दर्ज करें।",
    "Please search for a user first.": "कृपया पहले किसी उपयोगकर्ता को खोजें.",
    "Share this app link with receiver": "इस ऐप लिंक को रिसीवर के साथ साझा करें",
    "Points to Transfer": "स्थानांतरण के लिए अंक",
    "Please enter your phone number": "कृपया अपना फोन नंबर दर्ज करें",
    "Insufficient points": "अपर्याप्त अंक",
    "points transferred to": "अंक हस्तांतरित किये गये",
    "Not Registered": "पंजीकृत नहीं है",
    "Failed to send OTP": "ओटीपी भेजने में विफल",
    "Send App Link": "ऐप लिंक भेजें",
    "Please enter your name": "कृपया अपना नाम दर्ज करें",
    "Already Registered": "पहले से ही पंजीकृत",
    "Login Failed": "लॉगिन विफल",
    "This number is not registered. Send app link so they can create account, then transfer points to this number.": "यह नंबर पंजीकृत नहीं है. ऐप लिंक भेजें ताकि वे खाता बना सकें, फिर इस नंबर पर अंक स्थानांतरित कर सकें।",
    "This phone number is not registered. Please create an account first.": "यह फ़ोन नंबर पंजीकृत नहीं है. कृपया पहले एक खाता बनाएं.",
    "Please enter a valid Indian mobile number": "कृपया एक वैध भारतीय मोबाइल नंबर दर्ज करें",
    "Wrong Password": "ग़लत पासवर्ड",
    "Please enter your password": "अपना पासवर्ड दर्ज करें",
    "Scan any SRV product QR to earn and manage electrician wallet points.": "इलेक्ट्रीशियन वॉलेट पॉइंट अर्जित करने और प्रबंधित करने के लिए किसी भी एसआरवी उत्पाद क्यूआर को स्कैन करें।",
    "This phone number is already registered. Please login instead.": "यह फ़ोन नंबर पहले से पंजीकृत है. कृपया इसके बजाय लॉगिन करें.",
    "Customer only": "केवल ग्राहक",
    "Google not configured": "Google कॉन्फ़िगर नहीं किया गया",
    "Google sign-in is not available in this app build. Please update the app and try again.": "इस ऐप बिल्ड में Google साइन-इन उपलब्ध नहीं है। कृपया ऐप को अपडेट करें और पुनः प्रयास करें।",
    "Incorrect password. Try again or use OTP login.": "गलत पासवर्ड। पुनः प्रयास करें या ओटीपी लॉगिन का उपयोग करें।",
    "Check your credentials and try again.": "अपनी साख जांचें और पुनः प्रयास करें।",
    "OTP verification failed. Please try again.": "ओटीपी सत्यापन विफल रहा. कृपया पुन: प्रयास करें।",
    "Google Sign-In Failed": "Google साइन-इन विफल",
    "Google did not return a sign-in token.": "Google ने साइन-इन टोकन वापस नहीं किया.",
    "Google Play Services is unavailable or needs an update on this device.": "Google Play सेवाएँ अनुपलब्ध है या इस डिवाइस पर अपडेट की आवश्यकता है।",
    "Google sign-in is already in progress.": "Google साइन-इन पहले से ही प्रगति पर है.",
    "Please enter your state": "कृपया अपना राज्य दर्ज करें",
    "Registration Failed": "पंजीकरण विफल रहा",
    "Please enter your district": "कृपया अपना जिला दर्ज करें",
    "Welcome Back": "वापसी पर स्वागत है",
    "Login or create a new account": "लॉगिन करें या नया अकाउंट बनाएं",
    "Customers": "ग्राहकों",
    "Sending...": "भेजा जा रहा है...",
    "Please enter a valid 6-digit pincode": "कृपया एक वैध 6-अंकीय पिनकोड दर्ज करें",
    "6-digit OTP": "6 अंकों का ओटीपी",
    "Updating...": "अद्यतन किया जा रहा है...",
    "Back to Login": "लॉगिन पर वापस जाएं",
    "Trusted electrical products since 2000": "2000 से विश्वसनीय विद्युत उत्पाद",
    "Verify OTP first, then create your new password": "पहले ओटीपी वेरिफाई करें, फिर अपना नया पासवर्ड बनाएं",
    "Could not create account. Please try again.": "खाता नहीं बनाया जा सका. कृपया पुन: प्रयास करें।",
    "Your full name": "आपका पूरा नाम",
    "Please enter a valid email address without spaces": "कृपया रिक्त स्थान के बिना एक वैध ईमेल पता दर्ज करें",
    "optional": "वैकल्पिक",
    "your@email.com": "your@email.com",
    "Join SRV Electricals today": "आज ही एसआरवी इलेक्ट्रिकल्स से जुड़ें",
    "Welcome back to SRV Electricals": "एसआरवी इलेक्ट्रिकल्स में आपका पुनः स्वागत है",
    "Add the remaining details below to finish creating your account.": "अपना खाता बनाना समाप्त करने के लिए नीचे शेष विवरण जोड़ें।",
    "Enter the OTP and verify before continuing to the remaining details.": "ओटीपी दर्ज करें और शेष विवरण जारी रखने से पहले सत्यापित करें।",
    "6-digit pincode": "6 अंकों का पिनकोड",
    "Create a password": "एक पासवर्ड बनाएं",
    "Referral Code": "रेफरल कोड",
    "4-digit OTP": "4 अंकों का ओटीपी",
    "Logging in...": "प्रवेश किया...",
    "Creating...": "बनाया जा रहा है...",
    "Already have an account? ": "क्या आपके पास पहले से एक खाता मौजूद है?",
    "Don't have an account? ": "कोई खाता नहीं है?",
    "Sign up": "साइन अप करें",
    "Cart": "कार्ट",
    "Total Qty": "कुल मात्रा",
    "Customer Cart": "ग्राहक कार्ट",
    "Dealer Cart": "डीलर कार्ट",
    "Counterboy Cart": "काउंटरबॉय कार्ट",
    "Your cart is empty": "आपकी गाड़ी खाली है",
    "Browse Products": "उत्पाद ब्राउज़ करें",
    "No matching products": "कोई मेल खाता उत्पाद नहीं",
    "Order Summary": "आदेश सारांश",
    "item(s)": "सामान)",
    "Review your selected products, adjust quantity and continue with enquiry.": "अपने चयनित उत्पादों की समीक्षा करें, मात्रा समायोजित करें और पूछताछ जारी रखें।",
    "Proceed to Checkout": "चेकआउट के लिए आगे बढ़ें",
    "product": "उत्पाद",
    "Search products in cart": "कार्ट में उत्पाद खोजें",
    "Save your favorite items here and enquire when you are ready.": "अपने पसंदीदा आइटम यहां सहेजें और पूछें कि आप कब तैयार हैं।",
    "in cart": "गाड़ी में",
    "Try another product name or clear search.": "किसी अन्य उत्पाद का नाम आज़माएँ या खोज साफ़ करें।",
    "Razorpay secure payment": "रेज़रपे सुरक्षित भुगतान",
    "Browse categories, explore products and add items here for a cleaner enquiry flow.": "स्वच्छ पूछताछ प्रवाह के लिए यहां श्रेणियां ब्राउज़ करें, उत्पाद खोजें और आइटम जोड़ें।",
    "Buy This Product": "यह उत्पाद खरीदें",
    "Cash on Delivery": "डिलवरी पर नकदी",
    "Address required": "पता आवश्यक है",
    "UPI, cards & wallets": "UPI, कार्ड और वॉलेट",
    "points available": "अंक उपलब्ध",
    "Pay with Points": "अंकों के साथ भुगतान करें",
    "Pay when your order arrives": "आपका ऑर्डर आने पर भुगतान करें",
    "Please enter your shipping address.": "कृपया अपना शिपिंग पता दर्ज करें.",
    "Address updated": "पता अपडेट किया गया",
    "but this order needs": "लेकिन इस आदेश की जरूरत है",
    "Your order has been placed using points.": "आपका ऑर्डर पॉइंट्स का उपयोग करके दिया गया है।",
    "Minimum order amount": "न्यूनतम आदेश राशि",
    "Your shipping address has been updated successfully.": "आपका शिपिंग पता सफलतापूर्वक अपडेट कर दिया गया है.",
    "Online payment is available in the Android app.": "ऑनलाइन भुगतान एंड्रॉइड ऐप में उपलब्ध है।",
    "Cart item": "गाड़ी का सामान",
    "points deducted.": "अंक काटे गए.",
    "All cart products have been placed successfully with Cash on Delivery. You can track them from My Orders.": "सभी कार्ट उत्पादों को कैश ऑन डिलीवरी के साथ सफलतापूर्वक रखा गया है। आप उन्हें माई ऑर्डर्स से ट्रैक कर सकते हैं।",
    "Your order has been placed successfully with Cash on Delivery. You can track it from My Orders.": "आपका ऑर्डर कैश ऑन डिलीवरी के साथ सफलतापूर्वक प्लेस हो गया है। आप इसे माई ऑर्डर्स से ट्रैक कर सकते हैं।",
    "Payment not completed": "भुगतान पूरा नहीं हुआ",
    "Payment failed": "भुगतान विफल रही",
    "SECURE CHECKOUT": "सुरक्षित चेकआउट",
    "Checkout": "चेक आउट",
    "The payment could not be completed. Please try again.": "भुगतान पूरा नहीं हो सका. कृपया पुन: प्रयास करें।",
    "Review, choose payment, place order": "समीक्षा करें, भुगतान चुनें, ऑर्डर दें",
    "Payment received for all cart products. Your orders are confirmed and ready for processing.": "सभी कार्ट उत्पादों के लिए भुगतान प्राप्त हुआ। आपके ऑर्डर की पुष्टि हो गई है और प्रसंस्करण के लिए तैयार हैं।",
    "Contact Info": "संपर्क सूचना",
    "The payment was cancelled or could not be completed. No order has been confirmed and you have not been charged.": "भुगतान रद्द कर दिया गया या पूरा नहीं किया जा सका. किसी ऑर्डर की पुष्टि नहीं की गई है और आपसे शुल्क नहीं लिया गया है.",
    "Shipping Address": "शिपिंग पता",
    "Payment received. Your order has been confirmed and is ready for processing.": "भुगतान प्राप्त। आपके ऑर्डर की पुष्टि हो गई है और प्रसंस्करण के लिए तैयार है।",
    "1. Review": "1. समीक्षा",
    "Edit": "संपादन करना",
    "2. Delivery": "2. डिलिवरी",
    "Enter your address": "अपना पता दर्ज करें",
    "Save Address": "पता सहेजें",
    "3. Pay": "3. भुगतान करें",
    "PAYMENT": "भुगतान",
    "Tap edit to update your delivery address.": "अपना डिलीवरी पता अपडेट करने के लिए संपादित करें पर टैप करें।",
    "FAST": "तेज़",
    "Edit shipping address": "शिपिंग पता संपादित करें",
    "UPI, cards, netbanking and wallets": "UPI, कार्ड, नेटबैंकिंग और वॉलेट",
    "COD": "सीओडी",
    "Add another address": "दूसरा पता जोड़ें",
    "Available": "उपलब्ध",
    "Choose how you want to pay": "चुनें कि आप भुगतान कैसे करना चाहते हैं",
    "POINTS": "अंक",
    "PAYMENT METHOD": "भुगतान विधि",
    "Pay Online with Razorpay": "रेज़रपे से ऑनलाइन भुगतान करें",
    "Not enough points": "पर्याप्त अंक नहीं",
    "Change": "परिवर्तन",
    "Item Total": "आइटम का कुल",
    "Shipping": "शिपिंग",
    "Free": "मुक्त",
    "Total": "कुल",
    "Currently not supported": "वर्तमान में समर्थित नहीं है",
    "Pay Securely": "सुरक्षित रूप से भुगतान करें",
    "Enough for this order": "इस आदेश के लिए पर्याप्त है",
    "Choose payment method": "भुगतान विधि चुनें",
    "Place COD Order": "सीओडी ऑर्डर दें",
    "Select a method before placing your order": "अपना ऑर्डर देने से पहले एक विधि चुनें",
    "No videos yet": "अभी तक कोई वीडियो नहीं",
    "OTP verified. Now create a new secure password.": "ओटीपी सत्यापित. अब एक नया सुरक्षित पासवर्ड बनाएं।",
    "Enter your registered mobile number. We will send an OTP to verify your account.": "अपना पंजीकृत मोबाइल नंबर दर्ज करें। हम आपके खाते को सत्यापित करने के लिए एक ओटीपी भेजेंगे।",
    "videos": "वीडियो",
    "visible": "दृश्यमान",
    "Now Showing": "अब दिखा रहे हैं",
    "items": "सामान",
    "SRV Videos": "एसआरवी वीडियो",
    "Video Picks": "वीडियो चयन",
    "Fresh Picks": "ताज़ा चयन",
    "Videos will appear here once uploaded by SRV Team": "एसआरवी टीम द्वारा अपलोड किए जाने पर वीडियो यहां दिखाई देंगे",
    "points.": "अंक.",
    "Switch category or wait for SRV Team uploads": "श्रेणी बदलें या एसआरवी टीम अपलोड की प्रतीक्षा करें",
    "No videos in this category": "इस श्रेणी में कोई वीडियो नहीं है",
    "No matching categories found": "कोई मेल खाती श्रेणियां नहीं मिलीं",
    "Explore smart product videos, quick reels, and simple explainers picked for everyday browsing.": "रोजमर्रा की ब्राउज़िंग के लिए चुने गए स्मार्ट उत्पाद वीडियो, त्वरित रीलों और सरल व्याख्याकारों का अन्वेषण करें।",
    "pts.": "पीटी.",
    "Redeem your SRV rewards": "अपने एसआरवी पुरस्कार भुनाएं",
    "Professional Product Overview": "व्यावसायिक उत्पाद अवलोकन",
    "Use your earned points to claim gifts, offers, and customer rewards from one place.": "एक ही स्थान से उपहार, ऑफ़र और ग्राहक पुरस्कार का दावा करने के लिए अपने अर्जित अंकों का उपयोग करें।",
    "Scanned At": "पर स्कैन किया गया",
    "Redemption Requested!": "मोचन का अनुरोध किया गया!",
    "Counter Boy Account": "काउंटर बॉय अकाउंट",
    "Tap to return to profile card": "प्रोफ़ाइल कार्ड पर लौटने के लिए टैप करें",
    "Open Website": "वेबसाइट खोलें",
    "Tap to view your details": "अपना विवरण देखने के लिए टैप करें",
    "Save profile card PDF": "प्रोफ़ाइल कार्ड पीडीएफ सहेजें",
    "Add": "जोड़ना",
    "Points can only be transferred to another": "अंक केवल दूसरे को हस्तांतरित किये जा सकते हैं",
    "When electrician points are redeemed, the dealer bonus is credited automatically:": "जब इलेक्ट्रीशियन अंक भुनाए जाते हैं, तो डीलर बोनस स्वचालित रूप से जमा हो जाता है:",
    "of the points redeemed by any electrician will be credited to your dealer wallet. 1 point = 1 INR, and you can withdraw it directly to your bank account.": "किसी भी इलेक्ट्रीशियन द्वारा भुनाए गए अंकों का हिस्सा आपके डीलर वॉलेट में जमा किया जाएगा। 1 अंक = 1 INR, और आप इसे सीधे अपने बैंक खाते से निकाल सकते हैं।",
    "Points transfer is available only between users with the same role.": "पॉइंट ट्रांसफर केवल समान भूमिका वाले उपयोगकर्ताओं के बीच ही उपलब्ध है।",
    "Auto Bonus": "ऑटो बोनस",
    "Please increase quantity. The minimum order amount is": "कृपया मात्रा बढ़ाएँ. न्यूनतम ऑर्डर राशि है",
    "more to reach the minimum order amount.": "न्यूनतम ऑर्डर राशि तक पहुंचने के लिए और अधिक।"
  },
  "Punjabi": {
    "Enter complete delivery address": "ਪੂਰਾ ਡਿਲਿਵਰੀ ਪਤਾ ਦਰਜ ਕਰੋ",
    "images": "ਤਸਵੀਰਾਂ",
    "Swipe to view": "ਵੇਖਣ ਲਈ ਸਵਾਈਪ ਕਰੋ",
    "Welcome": "ਜੀ ਆਇਆਂ ਨੂੰ",
    "You can explore the home page as a guest. Login or create an account to use all app features.": "ਤੁਸੀਂ ਮਹਿਮਾਨ ਵਜੋਂ ਹੋਮ ਪੇਜ ਵੇਖ ਸਕਦੇ ਹੋ। ਐਪ ਦੀਆਂ ਸਾਰੀਆਂ ਸੁਵਿਧਾਵਾਂ ਵਰਤਣ ਲਈ ਲਾਗਇਨ ਕਰੋ ਜਾਂ ਖਾਤਾ ਬਣਾਓ।",
    "Back": "ਵਾਪਸ",
    "SUPPORT": "ਸਹਿਯੋਗ",
    "Clear All": "ਸਭ ਸਾਫ਼ ਕਰੋ",
    "No notifications yet": "ਅਜੇ ਤੱਕ ਕੋਈ ਸੂਚਨਾਵਾਂ ਨਹੀਂ ਹਨ",
    "You're all caught up. New updates will appear here.": "ਤੁਸੀਂ ਸਭ ਸਮਝ ਲਿਆ ਹੈ। ਨਵੇਂ ਅੱਪਡੇਟ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।",
    "updates": "ਅੱਪਡੇਟ",
    "This will hide all current notifications only for your account.": "ਇਹ ਸਿਰਫ਼ ਤੁਹਾਡੇ ਖਾਤੇ ਲਈ ਸਾਰੀਆਂ ਮੌਜੂਦਾ ਸੂਚਨਾਵਾਂ ਨੂੰ ਲੁਕਾ ਦੇਵੇਗਾ।",
    "Notification Details": "ਸੂਚਨਾ ਵੇਰਵੇ",
    "Clear": "ਸਾਫ਼",
    "Clear all notifications": "ਸਾਰੀਆਂ ਸੂਚਨਾਵਾਂ ਕਲੀਅਰ ਕਰੋ",
    "Minimum Points Required": "ਘੱਟੋ-ਘੱਟ ਅੰਕ ਲੋੜੀਂਦੇ ਹਨ",
    "You need at least 100 points to redeem. You have": "ਤੁਹਾਨੂੰ ਰੀਡੀਮ ਕਰਨ ਲਈ ਘੱਟੋ-ਘੱਟ 100 ਪੁਆਇੰਟਾਂ ਦੀ ਲੋੜ ਹੈ। ਤੁਹਾਡੇ ਕੋਲ ਹੈ",
    "points. Keep scanning to earn more!": "ਅੰਕ ਹੋਰ ਕਮਾਈ ਕਰਨ ਲਈ ਸਕੈਨ ਕਰਦੇ ਰਹੋ!",
    "You need": "ਤੁਹਾਨੂੰ ਲੋੜ ਹੈ",
    "Out of Stock": "ਖਤਮ ਹੈ",
    "pts but have": "ਅੰਕ ਪਰ ਹੈ",
    "Not Enough Points": "ਕਾਫ਼ੀ ਅੰਕ ਨਹੀਂ ਹਨ",
    "Pts.": "ਅੰਕ",
    "Gift Order Requested": "ਗਿਫਟ ​​ਆਰਡਰ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ",
    "pts. Keep scanning to unlock this gift!": "ਅੰਕ ਇਸ ਤੋਹਫ਼ੇ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ ਸਕੈਨ ਕਰਦੇ ਰਹੋ!",
    "This gift is currently out of stock. Check back soon!": "ਇਹ ਤੋਹਫ਼ਾ ਇਸ ਸਮੇਂ ਸਟਾਕ ਤੋਂ ਬਾਹਰ ਹੈ। ਜਲਦੀ ਹੀ ਵਾਪਸ ਜਾਂਚ ਕਰੋ!",
    "Your request for": "ਲਈ ਤੁਹਾਡੀ ਬੇਨਤੀ",
    "points from your wallet.": "ਤੁਹਾਡੇ ਬਟੂਏ ਤੋਂ ਅੰਕ।",
    "This will use": "ਇਹ ਵਰਤੇਗਾ",
    "Check back soon!": "ਜਲਦੀ ਹੀ ਵਾਪਸ ਜਾਂਚ ਕਰੋ!",
    "Redemption Failed": "ਰੀਡੈਂਪਸ਼ਨ ਅਸਫਲ ਰਿਹਾ",
    "has been submitted. SRV team will process it shortly.": "ਪੇਸ਼ ਕੀਤਾ ਗਿਆ ਹੈ। SRV ਟੀਮ ਜਲਦੀ ਹੀ ਇਸ 'ਤੇ ਕਾਰਵਾਈ ਕਰੇਗੀ।",
    "Scan & earn to redeem gifts": "ਤੋਹਫ਼ੇ ਰੀਡੀਮ ਕਰਨ ਲਈ ਸਕੈਨ ਕਰੋ ਅਤੇ ਕਮਾਓ",
    "Your Points": "ਤੁਹਾਡੇ ਅੰਕ",
    "Single": "ਸਿੰਗਲ",
    "No gifts available": "ਕੋਈ ਤੋਹਫ਼ੇ ਉਪਲਬਧ ਨਹੀਂ ਹਨ",
    "Multi": "ਬਹੁ",
    "No scans yet": "ਅਜੇ ਤੱਕ ਕੋਈ ਸਕੈਨ ਨਹੀਂ ਹੈ",
    "The camera could not start. Close the scanner and try again.": "ਕੈਮਰਾ ਚਾਲੂ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਸਕੈਨਰ ਬੰਦ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Verified": "ਪ੍ਰਮਾਣਿਤ",
    "Scan verification failed": "ਸਕੈਨ ਪੁਸ਼ਟੀਕਰਨ ਅਸਫਲ ਰਿਹਾ",
    "Scan one product, get instant points credited to your account": "ਇੱਕ ਉਤਪਾਦ ਨੂੰ ਸਕੈਨ ਕਰੋ, ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਤੁਰੰਤ ਪੁਆਇੰਟ ਕ੍ਰੈਡਿਟ ਕਰੋ",
    "Scan at least one SRV product before finishing.": "ਮੁਕੰਮਲ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ ਇੱਕ SRV ਉਤਪਾਦ ਨੂੰ ਸਕੈਨ ਕਰੋ।",
    "This QR is not registered with SRV products.": "ਇਹ QR SRV ਉਤਪਾਦਾਂ ਨਾਲ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ।",
    "Invalid QR Code": "ਅਵੈਧ QR ਕੋਡ",
    "Not available": "ਉਪਲਭਦ ਨਹੀ",
    "Points credited to your wallet!": "ਤੁਹਾਡੇ ਵਾਲਿਟ ਵਿੱਚ ਪੁਆਇੰਟ ਕ੍ਰੈਡਿਟ ਕੀਤੇ ਗਏ!",
    "Keep scanning multiple products and finish batch when you're done": "ਕਈ ਉਤਪਾਦਾਂ ਨੂੰ ਸਕੈਨ ਕਰਨਾ ਜਾਰੀ ਰੱਖੋ ਅਤੇ ਜਦੋਂ ਤੁਸੀਂ ਪੂਰਾ ਕਰ ਲਓ ਤਾਂ ਬੈਚ ਨੂੰ ਪੂਰਾ ਕਰੋ",
    "Phone": "ਫ਼ੋਨ",
    "Dealer Name": "ਡੀਲਰ ਦਾ ਨਾਮ",
    "Date & Time": "ਮਿਤੀ ਅਤੇ ਸਮਾਂ",
    "This QR was already redeemed. First scan details are shown below.": "ਇਹ QR ਪਹਿਲਾਂ ਹੀ ਰੀਡੀਮ ਕੀਤਾ ਗਿਆ ਸੀ। ਪਹਿਲੇ ਸਕੈਨ ਵੇਰਵੇ ਹੇਠਾਂ ਦਿਖਾਏ ਗਏ ਹਨ।",
    "Points for this QR were already claimed.": "ਇਸ QR ਲਈ ਪੁਆਇੰਟਾਂ ਦਾ ਪਹਿਲਾਂ ਹੀ ਦਾਅਵਾ ਕੀਤਾ ਗਿਆ ਸੀ।",
    "Scanned By": "ਦੁਆਰਾ ਸਕੈਨ ਕੀਤਾ ਗਿਆ",
    "Dealer Phone": "ਡੀਲਰ ਦਾ ਫ਼ੋਨ",
    "Items": "ਆਈਟਮਾਂ",
    "Points": "ਅੰਕ",
    "First scanner details are hidden.": "ਪਹਿਲੇ ਸਕੈਨਰ ਵੇਰਵੇ ਲੁਕੇ ਹੋਏ ਹਨ।",
    "Light": "ਚਾਨਣ",
    "On": "'ਤੇ",
    "Scan Summary": "ਸਕੈਨ ਸੰਖੇਪ",
    "All Scanned Items": "ਸਾਰੀਆਂ ਸਕੈਨ ਕੀਤੀਆਂ ਆਈਟਮਾਂ",
    "Chat with us on WhatsApp": "ਸਾਡੇ ਨਾਲ WhatsApp 'ਤੇ ਚੈਟ ਕਰੋ",
    "Continue Scanning": "ਸਕੈਨਿੰਗ ਜਾਰੀ ਰੱਖੋ",
    "Start scanning products to build your batch": "ਆਪਣਾ ਬੈਚ ਬਣਾਉਣ ਲਈ ਉਤਪਾਦਾਂ ਨੂੰ ਸਕੈਨ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ",
    "Email Us": "ਸਾਨੂੰ ਈਮੇਲ ਕਰੋ",
    "Get in Touch": "ਸੰਪਰਕ ਵਿੱਚ ਰਹੋ",
    "Send us an email anytime": "ਸਾਨੂੰ ਕਿਸੇ ਵੀ ਸਮੇਂ ਇੱਕ ਈਮੇਲ ਭੇਜੋ",
    "Call Us": "ਸਾਨੂੰ ਕਾਲ ਕਰੋ",
    "Speak directly to our support team": "ਸਾਡੀ ਸਹਾਇਤਾ ਟੀਮ ਨਾਲ ਸਿੱਧਾ ਗੱਲ ਕਰੋ",
    "Our team typically responds within 24 hours.": "ਸਾਡੀ ਟੀਮ ਆਮ ਤੌਰ 'ਤੇ 24 ਘੰਟਿਆਂ ਦੇ ਅੰਦਰ ਜਵਾਬ ਦਿੰਦੀ ਹੈ।",
    "Have a question or need assistance? We are just a tap away.": "ਕੋਈ ਸਵਾਲ ਹੈ ਜਾਂ ਸਹਾਇਤਾ ਦੀ ਲੋੜ ਹੈ? ਅਸੀਂ ਸਿਰਫ਼ ਇੱਕ ਟੈਪ ਦੂਰ ਹਾਂ।",
    "electricians in your network": "ਤੁਹਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ",
    "Unable to save electrician right now. Please check the details and try again.": "ਇਸ ਸਮੇਂ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨੂੰ ਬਚਾਉਣ ਵਿੱਚ ਅਸਮਰੱਥ। ਕਿਰਪਾ ਕਰਕੇ ਵੇਰਵਿਆਂ ਦੀ ਜਾਂਚ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "No electricians yet": "ਅਜੇ ਤੱਕ ਕੋਈ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨਹੀਂ ਹੈ",
    "Associate electricians from the home screen to see them here.": "ਉਹਨਾਂ ਨੂੰ ਇੱਥੇ ਦੇਖਣ ਲਈ ਹੋਮ ਸਕ੍ਰੀਨ ਤੋਂ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨਾਲ ਜੁੜੋ।",
    "Add electrician failed": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਸ਼ਾਮਲ ਕਰਨਾ ਅਸਫਲ ਰਿਹਾ",
    "Unable to load wallet activity": "ਵਾਲਿਟ ਗਤੀਵਿਧੀ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ",
    "Network filter": "ਨੈੱਟਵਰਕ ਫਿਲਟਰ",
    "Inactive Electricians": "ਅਕਿਰਿਆਸ਼ੀਲ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ",
    "Electrician activity": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਗਤੀਵਿਧੀ",
    "Total Network": "ਕੁੱਲ ਨੈੱਟਵਰਕ",
    "Review connected electricians and monitor their network activity from one place.": "ਕਨੈਕਟ ਕੀਤੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ ਅਤੇ ਇੱਕ ਥਾਂ ਤੋਂ ਉਹਨਾਂ ਦੀ ਨੈੱਟਵਰਕ ਗਤੀਵਿਧੀ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ।",
    "Wallet balance": "ਵਾਲਿਟ ਬੈਲੰਸ",
    "View wallet & withdrawals": "ਵਾਲਿਟ ਅਤੇ ਕਢਵਾਉਣਾ ਦੇਖੋ",
    "Check active and inactive electricians by joining month": "ਮਹੀਨਾ ਜੋੜ ਕੇ ਕਿਰਿਆਸ਼ੀਲ ਅਤੇ ਨਾ-ਸਰਗਰਮ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨਾਂ ਦੀ ਜਾਂਚ ਕਰੋ",
    "Withdrawal requests & 5% bonus": "ਕਢਵਾਉਣ ਦੀਆਂ ਬੇਨਤੀਆਂ ਅਤੇ 5% ਬੋਨਸ",
    "No electricians connected yet. Add your first electrician!": "ਅਜੇ ਤੱਕ ਕੋਈ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨਹੀਂ ਜੁੜਿਆ ਹੈ। ਆਪਣਾ ਪਹਿਲਾ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਸ਼ਾਮਲ ਕਰੋ!",
    "Withdrawals": "ਕਢਵਾਉਣਾ",
    "Wallet history, withdrawal requests and your 5% bonus": "ਵਾਲਿਟ ਇਤਿਹਾਸ, ਕਢਵਾਉਣ ਦੀਆਂ ਬੇਨਤੀਆਂ ਅਤੇ ਤੁਹਾਡਾ 5% ਬੋਨਸ",
    "5% bonus credited": "5% ਬੋਨਸ ਕ੍ਰੈਡਿਟ ਕੀਤਾ ਗਿਆ",
    "Balance": "ਸੰਤੁਲਨ",
    "Wallet history": "ਵਾਲਿਟ ਇਤਿਹਾਸ",
    "Expected 5% bonus after approval": "ਮਨਜ਼ੂਰੀ ਤੋਂ ਬਾਅਦ 5% ਬੋਨਸ ਦੀ ਉਮੀਦ ਹੈ",
    "No withdrawal requests yet.": "ਅਜੇ ਤੱਕ ਕੋਈ ਵਾਪਸੀ ਦੀਆਂ ਬੇਨਤੀਆਂ ਨਹੀਂ ਹਨ।",
    "Wallet transaction": "ਵਾਲਿਟ ਲੈਣ-ਦੇਣ",
    "Saving...": "ਰੱਖਿਅਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "English": "ਅੰਗਰੇਜ਼ੀ",
    "This electrician will be saved directly to your dealer network in the live database.": "ਇਹ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਲਾਈਵ ਡੇਟਾਬੇਸ ਵਿੱਚ ਸਿੱਧੇ ਤੁਹਾਡੇ ਡੀਲਰ ਨੈਟਵਰਕ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਜਾਵੇਗਾ।",
    "Hindi": "ਹਿੰਦੀ",
    "No wallet activity yet.": "ਅਜੇ ਤੱਕ ਕੋਈ ਵਾਲਿਟ ਗਤੀਵਿਧੀ ਨਹੀਂ ਹੈ।",
    "Punjabi": "ਪੰਜਾਬੀ",
    "points": "ਅੰਕ",
    "Something went wrong. Please try again.": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Invalid Mobile Number": "ਅਵੈਧ ਮੋਬਾਈਲ ਨੰਬਰ",
    "Could not create account": "ਖਾਤਾ ਨਹੀਂ ਬਣਾਇਆ ਜਾ ਸਕਿਆ",
    "Enter the OTP sent to your mobile number.": "ਆਪਣੇ ਮੋਬਾਈਲ ਨੰਬਰ 'ਤੇ ਭੇਜਿਆ ਗਿਆ OTP ਦਾਖਲ ਕਰੋ।",
    "Please enter a valid 10-digit mobile number.": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10-ਅੰਕਾਂ ਵਾਲਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਾਖਲ ਕਰੋ।",
    "Your current grading is based on total reward points earned through scans and redemptions.": "ਤੁਹਾਡੀ ਮੌਜੂਦਾ ਗਰੇਡਿੰਗ ਸਕੈਨ ਅਤੇ ਰੀਡੈਮਪਸ਼ਨ ਦੁਆਰਾ ਕਮਾਏ ਗਏ ਕੁੱਲ ਇਨਾਮ ਪੁਆਇੰਟਾਂ 'ਤੇ ਆਧਾਰਿਤ ਹੈ।",
    "Could not send OTP": "OTP ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ",
    "Password Required": "ਪਾਸਵਰਡ ਦੀ ਲੋੜ ਹੈ",
    "Now create your new password.": "ਹੁਣ ਆਪਣਾ ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ।",
    "OTP Required": "OTP ਲੋੜੀਂਦਾ ਹੈ",
    "Please verify OTP before updating password.": "ਕਿਰਪਾ ਕਰਕੇ ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।",
    "Password Mismatch": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ",
    "OTP Verification Required": "OTP ਪੁਸ਼ਟੀਕਰਨ ਦੀ ਲੋੜ ਹੈ",
    "You can now login with your new password.": "ਹੁਣ ਤੁਸੀਂ ਆਪਣੇ ਨਵੇਂ ਪਾਸਵਰਡ ਨਾਲ ਲਾਗਇਨ ਕਰ ਸਕਦੇ ਹੋ।",
    "Password Updated": "ਪਾਸਵਰਡ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ",
    "Passwords do not match. Please re-enter the same password.": "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ। ਕਿਰਪਾ ਕਰਕੇ ਉਹੀ ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਦਾਖਲ ਕਰੋ।",
    "Could not reset password": "ਪਾਸਵਰਡ ਰੀਸੈਟ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ",
    "Electrician Login": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਲੌਗਇਨ",
    "Dealer number cannot be same as your phone number. Please enter a different dealer number.": "ਡੀਲਰ ਦਾ ਨੰਬਰ ਤੁਹਾਡੇ ਫ਼ੋਨ ਨੰਬਰ ਵਰਗਾ ਨਹੀਂ ਹੋ ਸਕਦਾ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਵੱਖਰਾ ਡੀਲਰ ਨੰਬਰ ਦਾਖਲ ਕਰੋ।",
    "Dealer Login": "ਡੀਲਰ ਲਾਗਇਨ",
    "Complete the account setup flow and create your electrician profile.": "ਖਾਤਾ ਸੈੱਟਅੱਪ ਪ੍ਰਵਾਹ ਨੂੰ ਪੂਰਾ ਕਰੋ ਅਤੇ ਆਪਣਾ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ।",
    "Create Dealer Account": "ਡੀਲਰ ਖਾਤਾ ਬਣਾਓ",
    "Choose a secure login method and continue with your account.": "ਇੱਕ ਸੁਰੱਖਿਅਤ ਲੌਗਇਨ ਵਿਧੀ ਚੁਣੋ ਅਤੇ ਆਪਣੇ ਖਾਤੇ ਨਾਲ ਜਾਰੀ ਰੱਖੋ।",
    "Create Electrician Account": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਖਾਤਾ ਬਣਾਓ",
    "Counter Boy Login": "ਕਾਊਂਟਰ ਬੁਆਏ ਲਾਗਇਨ",
    "Create Counter Boy Account": "ਕਾਊਂਟਰ ਬੁਆਏ ਖਾਤਾ ਬਣਾਓ",
    "Choose a secure login method and continue with your dealer account.": "ਇੱਕ ਸੁਰੱਖਿਅਤ ਲੌਗਇਨ ਵਿਧੀ ਚੁਣੋ ਅਤੇ ਆਪਣੇ ਡੀਲਰ ਖਾਤੇ ਨਾਲ ਜਾਰੀ ਰੱਖੋ।",
    "Forgot Password?": "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    "Complete the account setup flow and create your dealer profile.": "ਖਾਤਾ ਸੈੱਟਅੱਪ ਪ੍ਰਵਾਹ ਨੂੰ ਪੂਰਾ ਕਰੋ ਅਤੇ ਆਪਣਾ ਡੀਲਰ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ।",
    "District": "ਜ਼ਿਲ੍ਹਾ",
    "Complete the account setup flow and create your counter boy profile.": "ਖਾਤਾ ਸੈੱਟਅੱਪ ਪ੍ਰਵਾਹ ਨੂੰ ਪੂਰਾ ਕਰੋ ਅਤੇ ਆਪਣੀ ਕਾਊਂਟਰ ਬੁਆਏ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ।",
    "Choose a secure login method and continue with your counter boy account.": "ਇੱਕ ਸੁਰੱਖਿਅਤ ਲੌਗਇਨ ਵਿਧੀ ਚੁਣੋ ਅਤੇ ਆਪਣੇ ਕਾਊਂਟਰ ਬੁਆਏ ਖਾਤੇ ਨਾਲ ਜਾਰੀ ਰੱਖੋ।",
    "Referral Code (Optional)": "ਰੈਫਰਲ ਕੋਡ (ਵਿਕਲਪਿਕ)",
    "Complete the account setup flow and create your profile.": "ਖਾਤਾ ਸੈੱਟਅੱਪ ਪ੍ਰਵਾਹ ਨੂੰ ਪੂਰਾ ਕਰੋ ਅਤੇ ਆਪਣਾ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ।",
    "Email Address (Optional)": "ਈਮੇਲ ਪਤਾ (ਵਿਕਲਪਿਕ)",
    "Password skipped. Accept the terms below to continue.": "ਪਾਸਵਰਡ ਛੱਡਿਆ ਗਿਆ। ਜਾਰੀ ਰੱਖਣ ਲਈ ਹੇਠਾਂ ਦਿੱਤੀਆਂ ਸ਼ਰਤਾਂ ਨੂੰ ਸਵੀਕਾਰ ਕਰੋ।",
    "GST / PAN Number": "GST/PAN ਨੰਬਰ",
    "Enter your friend’s referral code": "ਆਪਣੇ ਦੋਸਤ ਦਾ ਰੈਫਰਲ ਕੋਡ ਦਾਖਲ ਕਰੋ",
    "Forgot Password": "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ",
    "After signup, you and your friend will each receive 20 points.": "ਸਾਈਨ ਅੱਪ ਕਰਨ ਤੋਂ ਬਾਅਦ, ਤੁਹਾਨੂੰ ਅਤੇ ਤੁਹਾਡੇ ਦੋਸਤ ਨੂੰ 20 ਪੁਆਇੰਟ ਮਿਲਣਗੇ।",
    "Business Name *": "ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ *",
    "Confirm Password": "ਪਾਸਵਰਡ ਪੱਕਾ ਕਰੋ",
    "Create a password (minimum 8 characters)": "ਇੱਕ ਪਾਸਵਰਡ ਬਣਾਓ (ਘੱਟੋ ਘੱਟ 8 ਅੱਖਰ)",
    "Please wait...": "ਕ੍ਰਿਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
    "Re-enter new password": "ਨਵਾਂ ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਦਰਜ ਕਰੋ",
    "Product Details": "ਉਤਪਾਦ ਵੇਰਵੇ",
    "Out of stock": "ਖਤਮ ਹੈ",
    "Enter and verify the OTP sent to your mobile number.": "ਤੁਹਾਡੇ ਮੋਬਾਈਲ ਨੰਬਰ 'ਤੇ ਭੇਜਿਆ ਗਿਆ OTP ਦਰਜ ਕਰੋ ਅਤੇ ਪੁਸ਼ਟੀ ਕਰੋ।",
    "Enter your registered mobile number to receive an OTP.": "ਇੱਕ OTP ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।",
    "OTP verified. Now create a new password for your account.": "OTP ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ। ਹੁਣ ਆਪਣੇ ਖਾਤੇ ਲਈ ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ।",
    "Earn": "ਕਮਾਓ",
    "Available Offers": "ਉਪਲਬਧ ਪੇਸ਼ਕਸ਼ਾਂ",
    "SRV Assured": "SRV ਨੇ ਭਰੋਸਾ ਦਿਵਾਇਆ",
    "Free delivery": "ਮੁਫ਼ਤ ਡਿਲੀਵਰੀ",
    "Weight": "ਭਾਰ",
    "Standard": "ਮਿਆਰੀ",
    "Description": "ਵਰਣਨ",
    "Use COD, Razorpay, or wallet points at checkout.": "ਚੈੱਕਆਉਟ ਵੇਲੇ COD, Razorpay, ਜਾਂ ਵਾਲਿਟ ਪੁਆਇੰਟਸ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "reward points on this product.": "ਇਸ ਉਤਪਾਦ 'ਤੇ ਇਨਾਮ ਅੰਕ.",
    "instant discount compared with MRP.": "MRP ਦੇ ਮੁਕਾਬਲੇ ਤੁਰੰਤ ਛੂਟ।",
    "Related Products": "ਸੰਬੰਧਿਤ ਉਤਪਾਦ",
    "You may also like": "ਤੁਸੀਂ ਵੀ ਪਸੰਦ ਕਰ ਸਕਦੇ ਹੋ",
    "Qty": "ਮਾਤਰਾ",
    "Add to Cart": "ਠੇਲ੍ਹੇ ਵਿੱਚ ਪਾਓ",
    "SKU": "SKU",
    "SRV product details will appear here once updated from SRV Team.": "ਇੱਕ ਵਾਰ SRV ਟੀਮ ਵੱਲੋਂ ਅੱਪਡੇਟ ਕੀਤੇ ਜਾਣ 'ਤੇ SRV ਉਤਪਾਦ ਵੇਰਵੇ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।",
    "Login required": "ਲੌਗਇਨ ਲੋੜੀਂਦਾ ਹੈ",
    "Login / Signup": "ਲੌਗਇਨ / ਸਾਈਨ ਅੱਪ ਕਰੋ",
    "Added to cart": "ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕੀਤਾ ਗਿਆ",
    "Product added to your cart.": "ਉਤਪਾਦ ਤੁਹਾਡੇ ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕੀਤਾ ਗਿਆ।",
    "Please login or signup to continue with this product.": "ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਉਤਪਾਦ ਨਾਲ ਜਾਰੀ ਰੱਖਣ ਲਈ ਲੌਗਇਨ ਜਾਂ ਸਾਈਨ ਅੱਪ ਕਰੋ।",
    "Your product order has been sent to SRV Team.": "ਤੁਹਾਡਾ ਉਤਪਾਦ ਆਰਡਰ SRV ਟੀਮ ਨੂੰ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
    "Cart update failed": "ਕਾਰਟ ਅੱਪਡੇਟ ਅਸਫਲ ਰਿਹਾ",
    "Choose a category to see matching products.": "ਮੇਲ ਖਾਂਦੇ ਉਤਪਾਦਾਂ ਨੂੰ ਦੇਖਣ ਲਈ ਇੱਕ ਸ਼੍ਰੇਣੀ ਚੁਣੋ।",
    "Loading...": "ਲੋਡ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "products available": "ਉਤਪਾਦ ਉਪਲਬਧ ਹਨ",
    "Order failed": "ਆਰਡਰ ਅਸਫਲ ਰਿਹਾ",
    "Open cart": "ਕਾਰਟ ਖੋਲ੍ਹੋ",
    "results for": "ਲਈ ਨਤੀਜੇ",
    "No products found": "ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ ਮਿਲੇ",
    "Top matches": "ਚੋਟੀ ਦੇ ਮੈਚ",
    "North India's Largest Manufacturer": "ਉੱਤਰੀ ਭਾਰਤ ਦਾ ਸਭ ਤੋਂ ਵੱਡਾ ਨਿਰਮਾਤਾ",
    "points. Scan SRV products to earn more!": "ਅੰਕ ਹੋਰ ਕਮਾਈ ਕਰਨ ਲਈ SRV ਉਤਪਾਦਾਂ ਨੂੰ ਸਕੈਨ ਕਰੋ!",
    "Loading products...": "ਉਤਪਾਦ ਲੋਡ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...",
    "SRV Electricals — since 2000. Explore the latest SRV product range and offers.": "SRV ਇਲੈਕਟ੍ਰੀਕਲਸ — 2000 ਤੋਂ। ਨਵੀਨਤਮ SRV ਉਤਪਾਦ ਰੇਂਜ ਅਤੇ ਪੇਸ਼ਕਸ਼ਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ।",
    "points. Your bonus grows as your electricians redeem more!": "ਅੰਕ ਤੁਹਾਡਾ ਬੋਨਸ ਵਧਦਾ ਹੈ ਕਿਉਂਕਿ ਤੁਹਾਡੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਹੋਰ ਰਿਡੀਮ ਕਰਦੇ ਹਨ!",
    "This QR code has already been redeemed. Original scan details are shown below.": "ਇਹ QR ਕੋਡ ਪਹਿਲਾਂ ਹੀ ਰੀਡੀਮ ਕੀਤਾ ਜਾ ਚੁੱਕਾ ਹੈ। ਅਸਲੀ ਸਕੈਨ ਵੇਰਵੇ ਹੇਠਾਂ ਦਿਖਾਏ ਗਏ ਹਨ।",
    "Scan products to earn more": "ਹੋਰ ਕਮਾਈ ਕਰਨ ਲਈ ਉਤਪਾਦਾਂ ਨੂੰ ਸਕੈਨ ਕਰੋ",
    "Next": "ਅਗਲਾ",
    "Gift Order Requested!": "ਗਿਫਟ ​​ਆਰਡਰ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ!",
    "pts. Keep growing your electrician network to unlock this gift!": "ਅੰਕ ਇਸ ਤੋਹਫ਼ੇ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ ਆਪਣੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਨੈੱਟਵਰਕ ਨੂੰ ਵਧਾਉਂਦੇ ਰਹੋ!",
    "Already Scanned": "ਪਹਿਲਾਂ ਹੀ ਸਕੈਨ ਕੀਤਾ ਗਿਆ ਹੈ",
    "Back to Home": "ਘਰ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    "Login or signup to access this feature": "ਇਸ ਵਿਸ਼ੇਸ਼ਤਾ ਨੂੰ ਐਕਸੈਸ ਕਰਨ ਲਈ ਲੌਗਇਨ ਜਾਂ ਸਾਈਨ ਅੱਪ ਕਰੋ",
    "What you unlock after login": "ਲੌਗਇਨ ਕਰਨ ਤੋਂ ਬਾਅਦ ਤੁਸੀਂ ਕੀ ਅਨਲੌਕ ਕਰਦੇ ਹੋ",
    "Chat on WhatsApp": "ਵਟਸਐਪ 'ਤੇ ਚੈਟ ਕਰੋ",
    "Dealer account access": "ਡੀਲਰ ਖਾਤੇ ਤੱਕ ਪਹੁੰਚ",
    "Login or Signup": "ਲੌਗਇਨ ਜਾਂ ਸਾਈਨ ਅੱਪ ਕਰੋ",
    "Use another number": "ਕੋਈ ਹੋਰ ਨੰਬਰ ਵਰਤੋ",
    "Partners": "ਭਾਈਵਾਲ",
    "Electrician account access": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਖਾਤੇ ਤੱਕ ਪਹੁੰਚ",
    "Members": "ਮੈਂਬਰ",
    "Login or create your dealer account to unlock profile tools, network details and business controls.": "ਪ੍ਰੋਫਾਈਲ ਟੂਲਸ, ਨੈੱਟਵਰਕ ਵੇਰਵਿਆਂ ਅਤੇ ਕਾਰੋਬਾਰੀ ਨਿਯੰਤਰਣਾਂ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਆਪਣਾ ਡੀਲਰ ਖਾਤਾ ਬਣਾਓ।",
    "Get Started": "ਸ਼ੁਰੂ ਕਰੋ",
    "Login or create your electrician account to unlock rewards, scan history and your complete profile.": "ਇਨਾਮਾਂ, ਸਕੈਨ ਇਤਿਹਾਸ ਅਤੇ ਆਪਣੀ ਪੂਰੀ ਪ੍ਰੋਫਾਈਲ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਆਪਣਾ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਖਾਤਾ ਬਣਾਓ।",
    "Welcome Electrician": "ਸੁਆਗਤ ਹੈ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ",
    "Welcome Dealer": "ਸੁਆਗਤ ਹੈ ਡੀਲਰ",
    "Track rewards, scans and profile progress with your SRV account.": "ਆਪਣੇ SRV ਖਾਤੇ ਨਾਲ ਇਨਾਮਾਂ, ਸਕੈਨ ਅਤੇ ਪ੍ਰੋਫਾਈਲ ਦੀ ਤਰੱਕੀ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ।",
    "Upload failed": "ਅੱਪਲੋਡ ਅਸਫਲ ਰਿਹਾ",
    "Invalid Google Pay number": "ਅਵੈਧ Google Pay ਨੰਬਰ",
    "Error": "ਗਲਤੀ",
    "Login to Account": "ਖਾਤੇ ਵਿੱਚ ਲੌਗਇਨ ਕਰੋ",
    "Manage business growth, connected electricians and dealer tools in one place.": "ਕਾਰੋਬਾਰੀ ਵਿਕਾਸ, ਕਨੈਕਟ ਕੀਤੇ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਅਤੇ ਡੀਲਰ ਟੂਲਸ ਨੂੰ ਇੱਕ ਥਾਂ 'ਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।",
    "Switch Your Role": "ਆਪਣੀ ਭੂਮਿਕਾ ਬਦਲੋ",
    "Could not read this image. Please choose another one.": "ਇਹ ਚਿੱਤਰ ਪੜ੍ਹ ਨਹੀਂ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਹੋਰ ਚੁਣੋ।",
    "Failed to save bank details. Please try again.": "ਬੈਂਕ ਵੇਰਵੇ ਸੁਰੱਖਿਅਤ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Payment details linked": "ਭੁਗਤਾਨ ਵੇਰਵੇ ਲਿੰਕ ਕੀਤੇ ਗਏ",
    "Please enter a valid 10 digit Google Pay number.": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10 ਅੰਕਾਂ ਦਾ Google Pay ਨੰਬਰ ਦਾਖਲ ਕਰੋ।",
    "Add Google Pay number and UPI ID for smooth payouts": "ਨਿਰਵਿਘਨ ਭੁਗਤਾਨਾਂ ਲਈ Google Pay ਨੰਬਰ ਅਤੇ UPI ID ਸ਼ਾਮਲ ਕਰੋ",
    "Google Pay Number": "Google Pay ਨੰਬਰ",
    "Select a clear square QR image from your gallery": "ਆਪਣੀ ਗੈਲਰੀ ਤੋਂ ਇੱਕ ਸਪਸ਼ਟ ਵਰਗ QR ਚਿੱਤਰ ਚੁਣੋ",
    "UPI QR Code": "UPI QR ਕੋਡ",
    "Upload UPI QR Code": "UPI QR ਕੋਡ ਅੱਪਲੋਡ ਕਰੋ",
    "Enter Google Pay Number": "Google Pay ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
    "Uploading...": "ਅੱਪਲੋਡ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "Replace QR image": "QR ਚਿੱਤਰ ਨੂੰ ਬਦਲੋ",
    "Linked account": "ਲਿੰਕ ਕੀਤਾ ਖਾਤਾ",
    "Bank details required": "ਬੈਂਕ ਵੇਰਵੇ ਲੋੜੀਂਦੇ ਹਨ",
    "Requested amount cannot be more than your available dealer bonus.": "ਬੇਨਤੀ ਕੀਤੀ ਰਕਮ ਤੁਹਾਡੇ ਉਪਲਬਧ ਡੀਲਰ ਬੋਨਸ ਤੋਂ ਵੱਧ ਨਹੀਂ ਹੋ ਸਕਦੀ।",
    "Please add your bank details first.": "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਆਪਣੇ ਬੈਂਕ ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ।",
    "Add bank details before raising a withdrawal request": "ਕਢਵਾਉਣ ਦੀ ਬੇਨਤੀ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਬੈਂਕ ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ",
    "Invalid amount": "ਅਵੈਧ ਰਕਮ",
    "Request dealer bonus payout": "ਡੀਲਰ ਬੋਨਸ ਭੁਗਤਾਨ ਦੀ ਬੇਨਤੀ ਕਰੋ",
    "withdrawal request has been sent for SRV Team approval.": "SRV ਟੀਮ ਦੀ ਮਨਜ਼ੂਰੀ ਲਈ ਵਾਪਸੀ ਦੀ ਬੇਨਤੀ ਭੇਜੀ ਗਈ ਹੈ।",
    "Enter how many points you want in your bank account. SRV Team will review and transfer the payout manually.": "ਦਰਜ ਕਰੋ ਕਿ ਤੁਸੀਂ ਆਪਣੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਕਿੰਨੇ ਪੁਆਇੰਟ ਚਾਹੁੰਦੇ ਹੋ। SRV ਟੀਮ ਹੱਥੀਂ ਭੁਗਤਾਨ ਦੀ ਸਮੀਖਿਆ ਕਰੇਗੀ ਅਤੇ ਟ੍ਰਾਂਸਫਰ ਕਰੇਗੀ।",
    "Enter the dealer bonus amount you want in your bank account. SRV Team will review and transfer it manually.": "ਡੀਲਰ ਬੋਨਸ ਦੀ ਰਕਮ ਦਾਖਲ ਕਰੋ ਜੋ ਤੁਸੀਂ ਆਪਣੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਚਾਹੁੰਦੇ ਹੋ। SRV ਟੀਮ ਇਸਦੀ ਸਮੀਖਿਆ ਕਰੇਗੀ ਅਤੇ ਹੱਥੀਂ ਟ੍ਰਾਂਸਫਰ ਕਰੇਗੀ।",
    "Requested points cannot be more than your available balance.": "ਬੇਨਤੀ ਕੀਤੇ ਪੁਆਇੰਟ ਤੁਹਾਡੇ ਉਪਲਬਧ ਬਕਾਇਆ ਤੋਂ ਵੱਧ ਨਹੀਂ ਹੋ ਸਕਦੇ।",
    "points withdrawal request has been sent for SRV Team approval.": "ਅੰਕ ਵਾਪਸ ਲੈਣ ਦੀ ਬੇਨਤੀ SRV ਟੀਮ ਦੀ ਮਨਜ਼ੂਰੀ ਲਈ ਭੇਜੀ ਗਈ ਹੈ।",
    "Request failed": "ਬੇਨਤੀ ਅਸਫਲ ਰਹੀ",
    "Account Holder": "ਖਾਤਾ ਧਾਰਕ",
    "Available Points": "ਉਪਲਬਧ ਅੰਕ",
    "Available Dealer Bonus": "ਉਪਲਬਧ ਡੀਲਰ ਬੋਨਸ",
    "1 point = 1 INR payout request": "1 ਪੁਆਇੰਟ = 1 INR ਭੁਗਤਾਨ ਬੇਨਤੀ",
    "Linked bank account": "ਲਿੰਕ ਕੀਤਾ ਬੈਂਕ ਖਾਤਾ",
    "No account holder saved yet.": "ਅਜੇ ਤੱਕ ਕੋਈ ਖਾਤਾ ਧਾਰਕ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "Add Bank Details": "ਬੈਂਕ ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ",
    "Edit Bank Details": "ਬੈਂਕ ਵੇਰਵਿਆਂ ਨੂੰ ਸੰਪਾਦਿਤ ਕਰੋ",
    "Call": "ਕਾਲ ਕਰੋ",
    "Withdrawal amount": "ਕਢਵਾਉਣ ਦੀ ਰਕਮ",
    "Enter points amount": "ਅੰਕਾਂ ਦੀ ਰਕਮ ਦਾਖਲ ਕਰੋ",
    "Head Office": "ਮੁਖ਼ ਦਫ਼ਤਰ",
    "Points to withdraw": "ਵਾਪਸ ਲੈਣ ਲਈ ਅੰਕ",
    "Email support at": "'ਤੇ ਈਮੇਲ ਸਹਾਇਤਾ",
    "What is SRV Electricals?": "SRV ਇਲੈਕਟ੍ਰੀਕਲ ਕੀ ਹੈ?",
    "Submit transfer request": "ਟ੍ਰਾਂਸਫਰ ਦੀ ਬੇਨਤੀ ਦਰਜ ਕਰੋ",
    "How do QR rewards work?": "QR ਇਨਾਮ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਨ?",
    "Call support at": "'ਤੇ ਸਹਾਇਤਾ ਨੂੰ ਕਾਲ ਕਰੋ",
    "SRV Electricals is an Indian electrical-products manufacturer established in 2000. The company supplies reliable products for residential, commercial and industrial installations.": "SRV ਇਲੈਕਟ੍ਰੀਕਲਸ 2000 ਵਿੱਚ ਸਥਾਪਿਤ ਇੱਕ ਭਾਰਤੀ ਇਲੈਕਟ੍ਰੀਕਲ-ਉਤਪਾਦ ਨਿਰਮਾਤਾ ਹੈ। ਕੰਪਨੀ ਰਿਹਾਇਸ਼ੀ, ਵਪਾਰਕ ਅਤੇ ਉਦਯੋਗਿਕ ਸਥਾਪਨਾਵਾਂ ਲਈ ਭਰੋਸੇਯੋਗ ਉਤਪਾਦਾਂ ਦੀ ਸਪਲਾਈ ਕਰਦੀ ਹੈ।",
    "Which products are available in the app?": "ਐਪ ਵਿੱਚ ਕਿਹੜੇ ਉਤਪਾਦ ਉਪਲਬਧ ਹਨ?",
    "You can browse fan boxes, concealed and modular boxes, MCB distribution boxes, bus bars, ventilation and industrial fans, stabilizers, switchgear, lighting products and other electrical accessories.": "ਤੁਸੀਂ ਪੱਖੇ ਦੇ ਬਕਸੇ, ਛੁਪੇ ਹੋਏ ਅਤੇ ਮਾਡਿਊਲਰ ਬਕਸੇ, MCB ਡਿਸਟ੍ਰੀਬਿਊਸ਼ਨ ਬਾਕਸ, ਬੱਸ ਬਾਰ, ਹਵਾਦਾਰੀ ਅਤੇ ਉਦਯੋਗਿਕ ਪੱਖੇ, ਸਟੈਬੀਲਾਇਜ਼ਰ, ਸਵਿਚਗੀਅਰ, ਲਾਈਟਿੰਗ ਉਤਪਾਦ ਅਤੇ ਹੋਰ ਬਿਜਲੀ ਉਪਕਰਣਾਂ ਨੂੰ ਬ੍ਰਾਊਜ਼ ਕਰ ਸਕਦੇ ਹੋ।",
    "Where can I see my points and wallet history?": "ਮੈਂ ਆਪਣੇ ਪੁਆਇੰਟ ਅਤੇ ਵਾਲਿਟ ਇਤਿਹਾਸ ਕਿੱਥੇ ਦੇਖ ਸਕਦਾ/ਸਕਦੀ ਹਾਂ?",
    "Sign in with the correct role, open the scanner and scan the genuine QR code printed on an eligible SRV product. Valid points are credited to your wallet after successful verification. Each QR code can be redeemed only once.": "ਸਹੀ ਭੂਮਿਕਾ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ, ਸਕੈਨਰ ਖੋਲ੍ਹੋ ਅਤੇ ਇੱਕ ਯੋਗ SRV ਉਤਪਾਦ 'ਤੇ ਪ੍ਰਿੰਟ ਕੀਤੇ ਅਸਲ QR ਕੋਡ ਨੂੰ ਸਕੈਨ ਕਰੋ। ਵੈਧ ਪੁਆਇੰਟ ਸਫਲ ਪੁਸ਼ਟੀਕਰਨ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡੇ ਵਾਲਿਟ ਵਿੱਚ ਕ੍ਰੈਡਿਟ ਕੀਤੇ ਜਾਂਦੇ ਹਨ। ਹਰੇਕ QR ਕੋਡ ਨੂੰ ਸਿਰਫ਼ ਇੱਕ ਵਾਰ ਰੀਡੀਮ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।",
    "Open Wallet from the bottom navigation to view your available balance and transaction history. Pull down to refresh if you have just scanned a QR code or received transferred points.": "ਆਪਣਾ ਉਪਲਬਧ ਬਕਾਇਆ ਅਤੇ ਲੈਣ-ਦੇਣ ਇਤਿਹਾਸ ਦੇਖਣ ਲਈ ਹੇਠਲੇ ਨੈਵੀਗੇਸ਼ਨ ਤੋਂ ਵਾਲਿਟ ਖੋਲ੍ਹੋ। ਜੇਕਰ ਤੁਸੀਂ ਹੁਣੇ ਇੱਕ QR ਕੋਡ ਸਕੈਨ ਕੀਤਾ ਹੈ ਜਾਂ ਟ੍ਰਾਂਸਫਰ ਕੀਤੇ ਪੁਆਇੰਟ ਪ੍ਰਾਪਤ ਕੀਤੇ ਹਨ ਤਾਂ ਤਾਜ਼ਾ ਕਰਨ ਲਈ ਹੇਠਾਂ ਖਿੱਚੋ।",
    "How can I redeem a gift?": "ਮੈਂ ਤੋਹਫ਼ੇ ਨੂੰ ਕਿਵੇਂ ਰੀਡੀਮ ਕਰ ਸਕਦਾ ਹਾਂ?",
    "Open Gift Store, select a gift available for your role, confirm that you have enough points and submit the redemption. Gift redemptions and their delivery updates are shown separately under Gift Store Order.": "ਤੋਹਫ਼ਾ ਸਟੋਰ ਖੋਲ੍ਹੋ, ਆਪਣੀ ਭੂਮਿਕਾ ਲਈ ਉਪਲਬਧ ਤੋਹਫ਼ੇ ਦੀ ਚੋਣ ਕਰੋ, ਪੁਸ਼ਟੀ ਕਰੋ ਕਿ ਤੁਹਾਡੇ ਕੋਲ ਲੋੜੀਂਦੇ ਅੰਕ ਹਨ ਅਤੇ ਰੀਡੈਂਪਸ਼ਨ ਜਮ੍ਹਾਂ ਕਰੋ। ਗਿਫਟ ​​ਸਟੋਰ ਆਰਡਰ ਦੇ ਤਹਿਤ ਗਿਫਟ ਰੀਡੀਮਸ਼ਨ ਅਤੇ ਉਹਨਾਂ ਦੇ ਡਿਲੀਵਰੀ ਅੱਪਡੇਟ ਵੱਖਰੇ ਤੌਰ 'ਤੇ ਦਿਖਾਏ ਗਏ ਹਨ।",
    "Which payment methods are supported?": "ਕਿਹੜੀਆਂ ਭੁਗਤਾਨ ਵਿਧੀਆਂ ਸਮਰਥਿਤ ਹਨ?",
    "Online product purchases are processed securely through Razorpay using supported UPI, card, netbanking or wallet options. An order is confirmed only after the payment is successfully verified.": "Razorpay ਦੁਆਰਾ ਸਮਰਥਿਤ UPI, ਕਾਰਡ, ਨੈੱਟਬੈਂਕਿੰਗ ਜਾਂ ਵਾਲਿਟ ਵਿਕਲਪਾਂ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਔਨਲਾਈਨ ਉਤਪਾਦ ਖਰੀਦਦਾਰੀ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਕੀਤੀ ਜਾਂਦੀ ਹੈ। ਭੁਗਤਾਨ ਦੀ ਸਫਲਤਾਪੂਰਵਕ ਪੁਸ਼ਟੀ ਹੋਣ ਤੋਂ ਬਾਅਦ ਹੀ ਇੱਕ ਆਰਡਰ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",
    "Closing the payment window does not confirm an order and no successful purchase will appear in My Orders. You can return to checkout and try again whenever you are ready.": "ਭੁਗਤਾਨ ਵਿੰਡੋ ਨੂੰ ਬੰਦ ਕਰਨਾ ਕਿਸੇ ਆਰਡਰ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ ਕਰਦਾ ਹੈ ਅਤੇ ਮੇਰੇ ਆਰਡਰ ਵਿੱਚ ਕੋਈ ਸਫਲ ਖਰੀਦ ਨਹੀਂ ਦਿਖਾਈ ਦੇਵੇਗੀ। ਤੁਸੀਂ ਚੈੱਕਆਉਟ 'ਤੇ ਵਾਪਸ ਆ ਸਕਦੇ ਹੋ ਅਤੇ ਜਦੋਂ ਵੀ ਤੁਸੀਂ ਤਿਆਰ ਹੋਵੋ ਤਾਂ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰ ਸਕਦੇ ਹੋ।",
    "What happens if I cancel or close Razorpay?": "ਜੇਕਰ ਮੈਂ Razorpay ਨੂੰ ਰੱਦ ਜਾਂ ਬੰਦ ਕਰਾਂਗਾ ਤਾਂ ਕੀ ਹੋਵੇਗਾ?",
    "How can I cancel, return or request a refund?": "ਮੈਂ ਕਿਵੇਂ ਰੱਦ ਕਰ ਸਕਦਾ ਹਾਂ, ਵਾਪਸ ਕਰ ਸਕਦਾ ਹਾਂ ਜਾਂ ਰਿਫੰਡ ਦੀ ਬੇਨਤੀ ਕਿਵੇਂ ਕਰ ਸਕਦਾ ਹਾਂ?",
    "Where can I download the latest catalogue?": "ਮੈਂ ਨਵੀਨਤਮ ਕੈਟਾਲਾਗ ਕਿੱਥੋਂ ਡਾਊਨਲੋਡ ਕਰ ਸਕਦਾ/ਸਕਦੀ ਹਾਂ?",
    "Open My Orders, select the relevant product order and choose an available action. Cancellation is available for eligible active orders, while returns and refunds depend on delivery and payment status. Add a clear reason before submitting.": "ਮੇਰੇ ਆਰਡਰ ਖੋਲ੍ਹੋ, ਸੰਬੰਧਿਤ ਉਤਪਾਦ ਆਰਡਰ ਚੁਣੋ ਅਤੇ ਉਪਲਬਧ ਕਾਰਵਾਈ ਚੁਣੋ। ਰੱਦ ਕਰਨਾ ਯੋਗ ਕਿਰਿਆਸ਼ੀਲ ਆਰਡਰਾਂ ਲਈ ਉਪਲਬਧ ਹੈ, ਜਦੋਂ ਕਿ ਵਾਪਸੀ ਅਤੇ ਰਿਫੰਡ ਡਿਲੀਵਰੀ ਅਤੇ ਭੁਗਤਾਨ ਸਥਿਤੀ 'ਤੇ ਨਿਰਭਰ ਕਰਦੇ ਹਨ। ਦਰਜ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਇੱਕ ਸਪੱਸ਼ਟ ਕਾਰਨ ਸ਼ਾਮਲ ਕਰੋ।",
    "Tap Product Catalog on the home page to open the latest SRV catalogue. The catalogue contains the current product range and is updated by SRV administrators.": "ਨਵੀਨਤਮ SRV ਕੈਟਾਲਾਗ ਖੋਲ੍ਹਣ ਲਈ ਹੋਮ ਪੇਜ 'ਤੇ ਉਤਪਾਦ ਕੈਟਾਲਾਗ 'ਤੇ ਟੈਪ ਕਰੋ। ਕੈਟਾਲਾਗ ਵਿੱਚ ਮੌਜੂਦਾ ਉਤਪਾਦ ਰੇਂਜ ਸ਼ਾਮਲ ਹੈ ਅਤੇ ਇਸਨੂੰ SRV ਪ੍ਰਸ਼ਾਸਕਾਂ ਦੁਆਰਾ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "How do I contact support?": "ਮੈਂ ਸਹਾਇਤਾ ਨਾਲ ਕਿਵੇਂ ਸੰਪਰਕ ਕਰਾਂ?",
    "What should I do if an OTP is delayed?": "ਜੇਕਰ OTP ਵਿੱਚ ਦੇਰੀ ਹੁੰਦੀ ਹੈ ਤਾਂ ਮੈਨੂੰ ਕੀ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ?",
    "Confirm that the mobile number is correct, wait for the SMS and use only the latest OTP within its validity period. If it expires, request a fresh OTP and avoid pressing Verify more than once.": "ਪੁਸ਼ਟੀ ਕਰੋ ਕਿ ਮੋਬਾਈਲ ਨੰਬਰ ਸਹੀ ਹੈ, SMS ਦੀ ਉਡੀਕ ਕਰੋ ਅਤੇ ਇਸਦੀ ਵੈਧਤਾ ਮਿਆਦ ਦੇ ਅੰਦਰ ਸਿਰਫ ਨਵੀਨਤਮ OTP ਦੀ ਵਰਤੋਂ ਕਰੋ। ਜੇਕਰ ਇਸਦੀ ਮਿਆਦ ਪੁੱਗ ਜਾਂਦੀ ਹੈ, ਤਾਂ ਇੱਕ ਨਵੇਂ OTP ਦੀ ਬੇਨਤੀ ਕਰੋ ਅਤੇ ਇੱਕ ਤੋਂ ਵੱਧ ਵਾਰ ਪੁਸ਼ਟੀ ਕਰੋ ਨੂੰ ਦਬਾਉਣ ਤੋਂ ਬਚੋ।",
    "KYC Verification": "ਕੇਵਾਈਸੀ ਪੁਸ਼ਟੀਕਰਨ",
    "Please upload either PAN Card or GST Number": "ਕਿਰਪਾ ਕਰਕੇ ਪੈਨ ਕਾਰਡ ਜਾਂ GST ਨੰਬਰ ਅੱਪਲੋਡ ਕਰੋ",
    "Use the phone, WhatsApp or email options in Contact Us, or open Need Help to create a support ticket. Include your registered mobile number and order or QR details so the team can assist quickly.": "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ ਵਿੱਚ ਫ਼ੋਨ, WhatsApp ਜਾਂ ਈਮੇਲ ਵਿਕਲਪਾਂ ਦੀ ਵਰਤੋਂ ਕਰੋ, ਜਾਂ ਇੱਕ ਸਹਾਇਤਾ ਟਿਕਟ ਬਣਾਉਣ ਲਈ ਮਦਦ ਦੀ ਲੋੜ ਹੈ ਖੋਲ੍ਹੋ। ਆਪਣਾ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਅਤੇ ਆਰਡਰ ਜਾਂ QR ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ ਤਾਂ ਜੋ ਟੀਮ ਜਲਦੀ ਸਹਾਇਤਾ ਕਰ ਸਕੇ।",
    "Failed to submit KYC documents. Please try again.": "KYC ਦਸਤਾਵੇਜ਼ ਜਮ੍ਹਾਂ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Ready to Resubmit": "ਮੁੜ-ਸਪੁਰਦ ਕਰਨ ਲਈ ਤਿਆਰ",
    "Please upload Aadhar Card": "ਕਿਰਪਾ ਕਰਕੇ ਆਧਾਰ ਕਾਰਡ ਅਪਲੋਡ ਕਰੋ",
    "KYC Status": "ਕੇਵਾਈਸੀ ਸਥਿਤੀ",
    "Required Documents": "ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼",
    "Rejection Reason": "ਅਸਵੀਕਾਰ ਕਰਨ ਦਾ ਕਾਰਨ",
    "Your updated documents are ready. Tap submit to send them for fresh SRV Team review.": "ਤੁਹਾਡੇ ਅੱਪਡੇਟ ਕੀਤੇ ਦਸਤਾਵੇਜ਼ ਤਿਆਰ ਹਨ। ਉਹਨਾਂ ਨੂੰ ਤਾਜ਼ਾ SRV ਟੀਮ ਸਮੀਖਿਆ ਲਈ ਭੇਜਣ ਲਈ ਸਪੁਰਦ ਕਰੋ 'ਤੇ ਟੈਪ ਕਰੋ।",
    "Upload Aadhar Card for KYC verification": "ਕੇਵਾਈਸੀ ਵੈਰੀਫਿਕੇਸ਼ਨ ਲਈ ਆਧਾਰ ਕਾਰਡ ਅਪਲੋਡ ਕਰੋ",
    "Upload Aadhar Card and either PAN Card or GST Number for verification": "ਤਸਦੀਕ ਲਈ ਆਧਾਰ ਕਾਰਡ ਅਤੇ ਪੈਨ ਕਾਰਡ ਜਾਂ GST ਨੰਬਰ ਅੱਪਲੋਡ ਕਰੋ",
    "Aadhar Card": "ਆਧਾਰ ਕਾਰਡ",
    "Please try again later.": "ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Completion Progress": "ਮੁਕੰਮਲ ਹੋਣ ਦੀ ਪ੍ਰਗਤੀ",
    "Order": "ਆਰਡਰ",
    "Choose one from both PAN Card or GST Number": "ਪੈਨ ਕਾਰਡ ਜਾਂ ਜੀਐਸਟੀ ਨੰਬਰ ਦੋਵਾਂ ਵਿੱਚੋਂ ਇੱਕ ਚੁਣੋ",
    "Gift": "ਤੋਹਫ਼ਾ",
    "Reason": "ਕਾਰਨ",
    "Order Updates": "ਆਰਡਰ ਅੱਪਡੇਟ",
    "Submitting...": "ਸਪੁਰਦ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "PAN Card or GST Number": "ਪੈਨ ਕਾਰਡ ਜਾਂ ਜੀਐਸਟੀ ਨੰਬਰ",
    "Tracking ID": "ਟਰੈਕਿੰਗ ਆਈ.ਡੀ",
    "Sending": "ਭੇਜ ਰਿਹਾ ਹੈ",
    "Delivery Executive details will be available once the order is out for delivery": "ਡਿਲਿਵਰੀ ਕਾਰਜਕਾਰੀ ਵੇਰਵੇ ਡਿਲੀਵਰੀ ਲਈ ਆਰਡਰ ਦੇ ਬਾਹਰ ਹੋਣ ਤੋਂ ਬਾਅਦ ਉਪਲਬਧ ਹੋਣਗੇ",
    "SRV's promises": "SRV ਦੇ ਵਾਅਦੇ",
    "Tell us why you want to cancel, return or refund": "ਸਾਨੂੰ ਦੱਸੋ ਕਿ ਤੁਸੀਂ ਕਿਉਂ ਰੱਦ ਕਰਨਾ, ਵਾਪਸ ਕਰਨਾ ਜਾਂ ਰਿਫੰਡ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ",
    "Courier Partner": "ਕੋਰੀਅਰ ਪਾਰਟਨਰ",
    "This reason is shared with the order support team.": "ਇਹ ਕਾਰਨ ਆਰਡਰ ਸਹਾਇਤਾ ਟੀਮ ਨਾਲ ਸਾਂਝਾ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "No product orders found yet.": "ਅਜੇ ਤੱਕ ਕੋਈ ਉਤਪਾਦ ਆਰਡਰ ਨਹੀਂ ਮਿਲੇ ਹਨ।",
    "No orders found for this filter.": "ਇਸ ਫਿਲਟਰ ਲਈ ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਮਿਲੇ।",
    "Expected Delivery": "ਉਮੀਦ ਕੀਤੀ ਡਿਲਿਵਰੀ",
    "Reward redemption": "ਇਨਾਮ ਰੀਡੈਮਸ਼ਨ",
    "Load more orders": "ਹੋਰ ਆਰਡਰ ਲੋਡ ਕਰੋ",
    "Gift Store Order": "ਗਿਫਟ ​​ਸਟੋਰ ਆਰਡਰ",
    "Loading your orders...": "ਤੁਹਾਡੇ ਆਰਡਰ ਲੋਡ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...",
    "Gift Order Details": "ਗਿਫਟ ​​ਆਰਡਰ ਦੇ ਵੇਰਵੇ",
    "Delivery Address": "ਡਿਲਿਵਰੀ ਪਤਾ",
    "Your future redemption activity will appear here.": "ਤੁਹਾਡੀ ਭਵਿੱਖੀ ਰੀਡੈਂਪਸ਼ਨ ਗਤੀਵਿਧੀ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗੀ।",
    "Total Requests": "ਕੁੱਲ ਬੇਨਤੀਆਂ",
    "Your request has been submitted successfully.": "ਤੁਹਾਡੀ ਬੇਨਤੀ ਸਫਲਤਾਪੂਰਵਕ ਸਪੁਰਦ ਕੀਤੀ ਗਈ ਹੈ।",
    "No redemption history yet": "ਹਾਲੇ ਤੱਕ ਕੋਈ ਰੀਡੈਮਪਸ਼ਨ ਇਤਿਹਾਸ ਨਹੀਂ ਹੈ",
    "Address saved with order": "ਪਤਾ ਆਰਡਰ ਨਾਲ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ",
    "Photo limit reached": "ਫ਼ੋਟੋ ਦੀ ਸੀਮਾ ਪੂਰੀ ਹੋ ਗਈ ਹੈ",
    "Photos ready": "ਫੋਟੋਆਂ ਤਿਆਰ ਹਨ",
    "We could not submit your request right now. Please try again.": "ਅਸੀਂ ਇਸ ਵੇਲੇ ਤੁਹਾਡੀ ਬੇਨਤੀ ਦਰਜ ਨਹੀਂ ਕਰ ਸਕੇ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "You can attach up to 5 photos.": "ਤੁਸੀਂ 5 ਫੋਟੋਆਂ ਤੱਕ ਨੱਥੀ ਕਰ ਸਕਦੇ ਹੋ।",
    "Ticket Closed": "ਟਿਕਟ ਬੰਦ",
    "In Progress": "ਤਰੱਕੀ ਹੋ ਰਹੀ ਹੈ",
    "Could not close ticket. Please try again.": "ਟਿਕਟ ਬੰਦ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Could not send reply. Please try again.": "ਜਵਾਬ ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Resolved": "ਹੱਲ ਕੀਤਾ",
    "WhatsApp chat has opened on the SRV number. Please attach the selected photos manually inside WhatsApp.": "SRV ਨੰਬਰ 'ਤੇ WhatsApp ਚੈਟ ਖੁੱਲ੍ਹ ਗਈ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ WhatsApp ਵਿੱਚ ਚੁਣੀਆਂ ਗਈਆਂ ਫੋਟੋਆਂ ਨੂੰ ਹੱਥੀਂ ਨੱਥੀ ਕਰੋ।",
    "Closed": "ਬੰਦ",
    "Just now": "ਹੁਣੇ",
    "Created": "ਬਣਾਇਆ",
    "Could not delete message. Please try again.": "ਸੁਨੇਹਾ ਮਿਟਾਇਆ ਨਹੀਂ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Your ticket has been closed.": "ਤੁਹਾਡੀ ਟਿਕਟ ਬੰਦ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ।",
    "Delete": "ਮਿਟਾਓ",
    "Continue on WhatsApp": "WhatsApp 'ਤੇ ਜਾਰੀ ਰੱਖੋ",
    "Do you want to delete this message?": "ਕੀ ਤੁਸੀਂ ਇਸ ਸੁਨੇਹੇ ਨੂੰ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "Delete message": "ਸੁਨੇਹਾ ਮਿਟਾਓ",
    "Reply to support": "ਸਮਰਥਨ ਲਈ ਜਵਾਬ ਦਿਓ",
    "Ticket closed": "ਟਿਕਟ ਬੰਦ",
    "Your reply is sent securely": "ਤੁਹਾਡਾ ਜਵਾਬ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਭੇਜਿਆ ਗਿਆ ਹੈ",
    "This ticket is closed": "ਇਹ ਟਿਕਟ ਬੰਦ ਹੈ",
    "Type a message...": "ਇੱਕ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...",
    "Closing...": "ਬੰਦ ਹੋ ਰਿਹਾ ਹੈ...",
    "Are you sure you want to close this ticket?": "ਕੀ ਤੁਸੀਂ ਪੱਕਾ ਇਸ ਟਿਕਟ ਨੂੰ ਬੰਦ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "My Tickets": "ਮੇਰੀਆਂ ਟਿਕਟਾਂ",
    "Photos": "ਫੋਟੋਆਂ",
    "Remove photo": "ਫੋਟੋ ਹਟਾਓ",
    "Close Ticket": "ਟਿਕਟ ਬੰਦ ਕਰੋ",
    "Add more": "ਹੋਰ ਸ਼ਾਮਲ ਕਰੋ",
    "New Request": "ਨਵੀਂ ਬੇਨਤੀ",
    "Add multiple photos": "ਕਈ ਫੋਟੋਆਂ ਸ਼ਾਮਲ ਕਰੋ",
    "You cannot send more messages": "ਤੁਸੀਂ ਹੋਰ ਸੁਨੇਹੇ ਨਹੀਂ ਭੇਜ ਸਕਦੇ",
    "No tickets yet": "ਅਜੇ ਤੱਕ ਕੋਈ ਟਿਕਟ ਨਹੀਂ",
    "Tap + to select and attach multiple photos": "ਕਈ ਫ਼ੋਟੋਆਂ ਨੂੰ ਚੁਣਨ ਅਤੇ ਨੱਥੀ ਕਰਨ ਲਈ + 'ਤੇ ਟੈਪ ਕਰੋ",
    "This saves your issue in the SRV system so SRV Team can track and resolve it.": "ਇਹ ਤੁਹਾਡੀ ਸਮੱਸਿਆ ਨੂੰ SRV ਸਿਸਟਮ ਵਿੱਚ ਰੱਖਿਅਤ ਕਰਦਾ ਹੈ ਤਾਂ ਕਿ SRV ਟੀਮ ਇਸਨੂੰ ਟ੍ਰੈਕ ਅਤੇ ਹੱਲ ਕਰ ਸਕੇ।",
    "Upload Photos": "ਫੋਟੋਆਂ ਅੱਪਲੋਡ ਕਰੋ",
    "Create a new request to get help": "ਮਦਦ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਇੱਕ ਨਵੀਂ ਬੇਨਤੀ ਬਣਾਓ",
    "Open ticket": "ਓਪਨ ਟਿਕਟ",
    "Support activity": "ਸਹਿਯੋਗ ਗਤੀਵਿਧੀ",
    "View details": "ਵੇਰਵੇ ਵੇਖੋ",
    "replies": "ਜਵਾਬ",
    "Submit Request": "ਬੇਨਤੀ ਦਰਜ ਕਰੋ",
    "No notifications yet.": "ਅਜੇ ਤੱਕ ਕੋਈ ਸੂਚਨਾਵਾਂ ਨਹੀਂ ਹਨ।",
    "Valid till": "ਤੱਕ ਵੈਧ ਹੈ",
    "Add selected photos?": "ਕੀ ਚੁਣੀਆਂ ਗਈਆਂ ਫ਼ੋਟੋਆਂ ਸ਼ਾਮਲ ਕਰੀਏ?",
    "Bumper Offer": "ਬੰਪਰ ਪੇਸ਼ਕਸ਼",
    "Discount": "ਛੂਟ",
    "Limited period offer": "ਸੀਮਤ ਮਿਆਦ ਦੀ ਪੇਸ਼ਕਸ਼",
    "Tap any ticket to view replies or close it.": "ਜਵਾਬ ਦੇਖਣ ਜਾਂ ਇਸ ਨੂੰ ਬੰਦ ਕਰਨ ਲਈ ਕਿਸੇ ਵੀ ਟਿਕਟ 'ਤੇ ਟੈਪ ਕਰੋ।",
    "Offer Details": "ਪੇਸ਼ਕਸ਼ ਵੇਰਵੇ",
    "Bonus Points": "ਬੋਨਸ ਅੰਕ",
    "Offer Validity": "ਪੇਸ਼ਕਸ਼ ਵੈਧਤਾ",
    "Starts": "ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ",
    "Special offer": "ਵਿਸ਼ੇਸ਼ ਪੇਸ਼ਕਸ਼",
    "Category": "ਸ਼੍ਰੇਣੀ",
    "Available now": "ਹੁਣ ਉਪਲਬਧ ਹੈ",
    "will be transferred to your bank account after approval.": "ਮਨਜ਼ੂਰੀ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਟ੍ਰਾਂਸਫਰ ਕੀਤਾ ਜਾਵੇਗਾ।",
    "End date will be updated soon": "ਸਮਾਪਤੀ ਮਿਤੀ ਜਲਦੀ ਹੀ ਅੱਪਡੇਟ ਕੀਤੀ ਜਾਵੇਗੀ",
    "Failed": "ਅਸਫਲ ਰਿਹਾ",
    "Ends": "ਖਤਮ ਹੁੰਦਾ ਹੈ",
    "Offers coming soon": "ਪੇਸ਼ਕਸ਼ਾਂ ਜਲਦੀ ਆ ਰਹੀਆਂ ਹਨ",
    "Link bank account first": "ਪਹਿਲਾਂ ਬੈਂਕ ਖਾਤਾ ਲਿੰਕ ਕਰੋ",
    "New SRV offers and promotions will appear here as soon as they are available.": "ਨਵੀਆਂ SRV ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਪ੍ਰੋਮੋਸ਼ਨ ਉਪਲਬਧ ਹੁੰਦੇ ਹੀ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।",
    "Total bonus earned": "ਕੁੱਲ ਬੋਨਸ ਕਮਾਇਆ ਗਿਆ",
    "OTP sent successfully": "OTP ਸਫਲਤਾਪੂਰਵਕ ਭੇਜਿਆ ਗਿਆ",
    "Please check your phone for the OTP": "ਕਿਰਪਾ ਕਰਕੇ OTP ਲਈ ਆਪਣੇ ਫ਼ੋਨ ਦੀ ਜਾਂਚ ਕਰੋ",
    "Please enter both passwords same.": "ਕਿਰਪਾ ਕਰਕੇ ਦੋਵੇਂ ਪਾਸਵਰਡ ਇੱਕੋ ਜਿਹੇ ਦਰਜ ਕਰੋ।",
    "Pending withdrawals": "ਨਿਕਾਸੀ ਬਕਾਇਆ",
    "Could not send OTP. Please try again.": "OTP ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Please request OTP first.": "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ OTP ਦੀ ਬੇਨਤੀ ਕਰੋ।",
    "Enter the OTP to continue.": "ਜਾਰੀ ਰੱਖਣ ਲਈ OTP ਦਾਖਲ ਕਰੋ।",
    "Invalid OTP. Please try again.": "ਅਵੈਧ OTP। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Password Changed": "ਪਾਸਵਰਡ ਬਦਲਿਆ ਗਿਆ",
    "OTP verified successfully. Create your new password now.": "OTP ਦੀ ਸਫਲਤਾਪੂਰਵਕ ਪੁਸ਼ਟੀ ਹੋਈ। ਹੁਣੇ ਆਪਣਾ ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ।",
    "CREATE ACCESS  ->": "ਪਹੁੰਚ ਬਣਾਓ ->",
    "You successfully changed your password.": "ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਆਪਣਾ ਪਾਸਵਰਡ ਬਦਲ ਲਿਆ ਹੈ।",
    "UPDATE SECURITY  ->": "ਅੱਪਡੇਟ ਸੁਰੱਖਿਆ ->",
    "ACCOUNT SECURITY": "ਖਾਤਾ ਸੁਰੱਖਿਆ",
    "Choose what you would like to do. Your account stays protected at every step.": "ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਕੀ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ। ਤੁਹਾਡਾ ਖਾਤਾ ਹਰ ਕਦਮ 'ਤੇ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦਾ ਹੈ।",
    "Password center": "ਪਾਸਵਰਡ ਕੇਂਦਰ",
    "Use at least 8 characters for a secure password.": "ਸੁਰੱਖਿਅਤ ਪਾਸਵਰਡ ਲਈ ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰਾਂ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "Verify OTP sent to your phone, then create a new password.": "ਤੁਹਾਡੇ ਫ਼ੋਨ 'ਤੇ ਭੇਜੇ ਗਏ OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ, ਫਿਰ ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ।",
    "Password already set": "ਪਾਸਵਰਡ ਪਹਿਲਾਂ ਹੀ ਸੈੱਟ ਹੈ",
    "You have already set a password for your account. Use Change Password to update it, or use Forgot Password from the login screen.": "ਤੁਸੀਂ ਆਪਣੇ ਖਾਤੇ ਲਈ ਪਹਿਲਾਂ ਹੀ ਇੱਕ ਪਾਸਵਰਡ ਸੈੱਟ ਕੀਤਾ ਹੈ। ਇਸਨੂੰ ਅੱਪਡੇਟ ਕਰਨ ਲਈ ਬਦਲੋ ਪਾਸਵਰਡ ਦੀ ਵਰਤੋਂ ਕਰੋ, ਜਾਂ ਲੌਗਇਨ ਸਕ੍ਰੀਨ ਤੋਂ ਭੁੱਲ ਗਏ ਪਾਸਵਰਡ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "Reset Password": "ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰੋ",
    "Re-enter your password": "ਆਪਣਾ ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਦਰਜ ਕਰੋ",
    "Verify OTP to unlock new password fields.": "ਨਵੇਂ ਪਾਸਵਰਡ ਖੇਤਰਾਂ ਨੂੰ ਅਨਲੌਕ ਕਰਨ ਲਈ OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।",
    "Policy updates shared": "ਨੀਤੀ ਅੱਪਡੇਟ ਸਾਂਝੇ ਕੀਤੇ",
    "Enter your current password": "ਆਪਣਾ ਮੌਜੂਦਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
    "Clear use of data": "ਡੇਟਾ ਦੀ ਸਾਫ਼ ਵਰਤੋਂ",
    "gifts": "ਤੋਹਫ਼ੇ",
    "Please enter a valid 10-digit phone number.": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 10-ਅੰਕਾਂ ਵਾਲਾ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ।",
    "Unable to save changes": "ਤਬਦੀਲੀਆਂ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ",
    "Invalid district": "ਅਵੈਧ ਜ਼ਿਲ੍ਹਾ",
    "Save profile changes?": "ਕੀ ਪ੍ਰੋਫਾਈਲ ਤਬਦੀਲੀਆਂ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰਨਾ ਹੈ?",
    "Save": "ਸੇਵ ਕਰੋ",
    "Rating not saved": "ਰੇਟਿੰਗ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਕੀਤੀ ਗਈ",
    "Go to Home": "ਘਰ 'ਤੇ ਜਾਓ",
    "Are you sure you want to update your profile details?": "ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ 'ਤੇ ਆਪਣੇ ਪ੍ਰੋਫਾਈਲ ਵੇਰਵਿਆਂ ਨੂੰ ਅੱਪਡੇਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    "District should contain only alphabets and spaces.": "ਜ਼ਿਲ੍ਹੇ ਵਿੱਚ ਸਿਰਫ਼ ਅੱਖਰ ਅਤੇ ਸਪੇਸ ਹੋਣੇ ਚਾਹੀਦੇ ਹਨ।",
    "Welcome from SRV": "SRV ਵੱਲੋਂ ਸੁਆਗਤ ਹੈ",
    "Tap once to choose your score": "ਆਪਣਾ ਸਕੋਰ ਚੁਣਨ ਲਈ ਇੱਕ ਵਾਰ ਟੈਪ ਕਰੋ",
    "Edit Rating": "ਰੇਟਿੰਗ ਦਾ ਸੰਪਾਦਨ ਕਰੋ",
    "Your feedback helps us improve. You can update it anytime.": "ਤੁਹਾਡੀ ਫੀਡਬੈਕ ਸਾਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ। ਤੁਸੀਂ ਇਸਨੂੰ ਕਿਸੇ ਵੀ ਸਮੇਂ ਅੱਪਡੇਟ ਕਰ ਸਕਦੇ ਹੋ।",
    "Copied": "ਕਾਪੀ ਕੀਤਾ",
    "Allow SRV to show this review in the app with my name and role. It may appear after 7 days.": "SRV ਨੂੰ ਮੇਰੇ ਨਾਮ ਅਤੇ ਭੂਮਿਕਾ ਨਾਲ ਐਪ ਵਿੱਚ ਇਹ ਸਮੀਖਿਆ ਦਿਖਾਉਣ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ। ਇਹ 7 ਦਿਨਾਂ ਬਾਅਦ ਦਿਖਾਈ ਦੇ ਸਕਦਾ ਹੈ।",
    "Referral app link copied successfully.": "ਰੈਫਰਲ ਐਪ ਲਿੰਕ ਸਫਲਤਾਪੂਰਵਕ ਕਾਪੀ ਕੀਤਾ ਗਿਆ।",
    "Rate your app experience": "ਆਪਣੇ ਐਪ ਅਨੁਭਵ ਨੂੰ ਦਰਜਾ ਦਿਓ",
    "Loading": "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ",
    "Your review helps us improve support, rewards, orders, and daily app experience.": "ਤੁਹਾਡੀ ਸਮੀਖਿਆ ਸਹਾਇਤਾ, ਇਨਾਮ, ਆਰਡਰ ਅਤੇ ਰੋਜ਼ਾਨਾ ਐਪ ਅਨੁਭਵ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਵਿੱਚ ਸਾਡੀ ਮਦਦ ਕਰਦੀ ਹੈ।",
    "SRV Referral Rewards": "SRV ਰੈਫਰਲ ਇਨਾਮ",
    "Invite a friend. Both earn points.": "ਕਿਸੇ ਦੋਸਤ ਨੂੰ ਸੱਦਾ ਦਿਓ। ਦੋਵੇਂ ਅੰਕ ਕਮਾਉਂਦੇ ਹਨ।",
    "Your Referral Code": "ਤੁਹਾਡਾ ਰੈਫਰਲ ਕੋਡ",
    "Copy App Link": "ਐਪ ਲਿੰਕ ਕਾਪੀ ਕਰੋ",
    "Please try again in a moment.": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਪਲ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Unable to open": "ਖੋਲ੍ਹਣ ਵਿੱਚ ਅਸਮਰੱਥ",
    "When your friend creates an account successfully from your referral, both of you receive 20 reward points.": "ਜਦੋਂ ਤੁਹਾਡਾ ਦੋਸਤ ਤੁਹਾਡੇ ਰੈਫਰਲ ਤੋਂ ਸਫਲਤਾਪੂਰਵਕ ਖਾਤਾ ਬਣਾਉਂਦਾ ਹੈ, ਤਾਂ ਤੁਹਾਨੂੰ ਦੋਵਾਂ ਨੂੰ 20 ਇਨਾਮ ਪੁਆਇੰਟ ਪ੍ਰਾਪਤ ਹੁੰਦੇ ਹਨ।",
    "Open": "ਖੋਲ੍ਹੋ",
    "Please login to like or comment on videos.": "ਕਿਰਪਾ ਕਰਕੇ ਵੀਡੀਓ 'ਤੇ ਪਸੰਦ ਜਾਂ ਟਿੱਪਣੀ ਕਰਨ ਲਈ ਲੌਗਇਨ ਕਰੋ।",
    "This video link cannot be opened on this device.": "ਇਹ ਵੀਡੀਓ ਲਿੰਕ ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਨਹੀਂ ਖੋਲ੍ਹਿਆ ਜਾ ਸਕਦਾ ਹੈ।",
    "Instagram": "Instagram",
    "Show less": "ਘੱਟ ਦਿਖਾਓ",
    "Show more": "ਹੋਰ ਦਿਖਾਓ",
    "Comment failed": "ਟਿੱਪਣੀ ਅਸਫਲ ਰਹੀ",
    "Unable to preview this video": "ਇਸ ਵੀਡੀਓ ਦੀ ਪੂਰਵਦਰਸ਼ਨ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ",
    "Videos will appear here again once SRV Team enables Play Zone from settings.": "SRV ਟੀਮ ਵੱਲੋਂ ਸੈਟਿੰਗਾਂ ਤੋਂ ਪਲੇ ਜ਼ੋਨ ਨੂੰ ਸਮਰੱਥ ਕਰਨ 'ਤੇ ਵੀਡੀਓ ਇੱਥੇ ਦੁਬਾਰਾ ਦਿਖਾਈ ਦੇਣਗੇ।",
    "Comments": "ਟਿੱਪਣੀਆਂ",
    "Loading videos...": "ਵੀਡੀਓ ਲੋਡ ਕੀਤੇ ਜਾ ਰਹੇ ਹਨ...",
    "views": "ਦ੍ਰਿਸ਼",
    "Play Zone is temporarily disabled": "ਪਲੇ ਜ਼ੋਨ ਅਸਥਾਈ ਤੌਰ 'ਤੇ ਅਸਮਰੱਥ ਹੈ",
    "No videos available yet": "ਅਜੇ ਤੱਕ ਕੋਈ ਵੀਡੀਓ ਉਪਲਬਧ ਨਹੀਂ ਹੈ",
    "Fresh videos for this profile will appear here once SRV Team uploads them.": "ਇੱਕ ਵਾਰ SRV ਟੀਮ ਦੁਆਰਾ ਉਹਨਾਂ ਨੂੰ ਅੱਪਲੋਡ ਕਰਨ ਤੋਂ ਬਾਅਦ ਇਸ ਪ੍ਰੋਫਾਈਲ ਲਈ ਤਾਜ਼ਾ ਵੀਡੀਓ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।",
    "Admin Team": "ਐਡਮਿਨ ਟੀਮ",
    "Add a comment...": "ਇੱਕ ਟਿੱਪਣੀ ਸ਼ਾਮਲ ਕਰੋ...",
    "Send": "ਭੇਜੋ",
    "No comments yet. Start the conversation.": "ਅਜੇ ਤੱਕ ਕੋਈ ਟਿੱਪਣੀ ਨਹੀਂ। ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ।",
    "SRV User": "SRV ਉਪਭੋਗਤਾ",
    "Posting": "ਪੋਸਟਿੰਗ",
    "Filter scan history": "ਫਿਲਟਰ ਸਕੈਨ ਇਤਿਹਾਸ",
    "Login to comment": "ਟਿੱਪਣੀ ਕਰਨ ਲਈ ਲੌਗਇਨ ਕਰੋ",
    "Total Scans": "ਕੁੱਲ ਸਕੈਨ",
    "Points Earned": "ਅੰਕ ਹਾਸਲ ਕੀਤੇ",
    "Not allowed": "ਆਗਿਆ ਨਹੀਂ ਹੈ",
    "No scan history found for this date.": "ਇਸ ਮਿਤੀ ਲਈ ਕੋਈ ਸਕੈਨ ਇਤਿਹਾਸ ਨਹੀਂ ਮਿਲਿਆ।",
    "User not found with this number": "ਇਸ ਨੰਬਰ ਨਾਲ ਯੂਜ਼ਰ ਨਹੀਂ ਮਿਲਿਆ",
    "Counter Boy": "ਕਾਊਂਟਰ ਬੁਆਏ",
    "Only electricians and counter boys can transfer points.": "ਸਿਰਫ਼ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਅਤੇ ਕਾਊਂਟਰ ਲੜਕੇ ਹੀ ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਕਰ ਸਕਦੇ ਹਨ।",
    "No scans yet. Start scanning products to earn points!": "ਅਜੇ ਤੱਕ ਕੋਈ ਸਕੈਨ ਨਹੀਂ ਹੈ। ਅੰਕ ਹਾਸਲ ਕਰਨ ਲਈ ਉਤਪਾਦਾਂ ਨੂੰ ਸਕੈਨ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ!",
    "Invalid number": "ਅਵੈਧ ਸੰਖਿਆ",
    "Invite link": "ਲਿੰਕ ਨੂੰ ਸੱਦਾ ਦਿਓ",
    "Please search for a user first.": "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਇੱਕ ਉਪਭੋਗਤਾ ਦੀ ਖੋਜ ਕਰੋ।",
    "Invalid receiver": "ਅਵੈਧ ਪ੍ਰਾਪਤਕਰਤਾ",
    "Search first": "ਪਹਿਲਾਂ ਖੋਜ ਕਰੋ",
    "Share this app link with receiver": "ਪ੍ਰਾਪਤਕਰਤਾ ਨਾਲ ਇਸ ਐਪ ਲਿੰਕ ਨੂੰ ਸਾਂਝਾ ਕਰੋ",
    "Enter valid points to transfer.": "ਟ੍ਰਾਂਸਫਰ ਕਰਨ ਲਈ ਵੈਧ ਪੁਆਇੰਟ ਦਾਖਲ ਕਰੋ।",
    "Insufficient points": "ਨਾਕਾਫ਼ੀ ਅੰਕ",
    "Transfer failed": "ਤਬਾਦਲਾ ਅਸਫਲ ਰਿਹਾ",
    "You do not have enough points.": "ਤੁਹਾਡੇ ਕੋਲ ਕਾਫ਼ੀ ਅੰਕ ਨਹੀਂ ਹਨ।",
    "points transferred to": "ਨੂੰ ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਕੀਤੇ ਗਏ",
    "Scan any SRV product QR to earn and manage electrician wallet points.": "ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਵਾਲਿਟ ਪੁਆਇੰਟ ਹਾਸਲ ਕਰਨ ਅਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰਨ ਲਈ ਕਿਸੇ ਵੀ SRV ਉਤਪਾਦ QR ਨੂੰ ਸਕੈਨ ਕਰੋ।",
    "Send App Link": "ਐਪ ਲਿੰਕ ਭੇਜੋ",
    "This number is not registered. Send app link so they can create account, then transfer points to this number.": "ਇਹ ਨੰਬਰ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ। ਐਪ ਲਿੰਕ ਭੇਜੋ ਤਾਂ ਜੋ ਉਹ ਖਾਤਾ ਬਣਾ ਸਕਣ, ਫਿਰ ਇਸ ਨੰਬਰ 'ਤੇ ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਕਰ ਸਕਣ।",
    "Points to Transfer": "ਟ੍ਰਾਂਸਫਰ ਕਰਨ ਲਈ ਪੁਆਇੰਟ",
    "Please enter a valid Indian mobile number": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
    "Please enter your phone number": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
    "Not Registered": "ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ",
    "Login Failed": "ਲਾਗਿਨ ਅਸਫਲ ਰਿਹਾ",
    "This phone number is not registered. Please create an account first.": "ਇਹ ਫ਼ੋਨ ਨੰਬਰ ਰਜਿਸਟਰਡ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਇੱਕ ਖਾਤਾ ਬਣਾਓ।",
    "Failed to send OTP": "OTP ਭੇਜਣਾ ਅਸਫਲ ਰਿਹਾ",
    "Please enter your name": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    "Please enter your password": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ",
    "Already Registered": "ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ",
    "This phone number is already registered. Please login instead.": "ਇਹ ਫ਼ੋਨ ਨੰਬਰ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਇਸਦੀ ਬਜਾਏ ਲੌਗਇਨ ਕਰੋ।",
    "Wrong Password": "ਗਲਤ ਪਾਸਵਰਡ",
    "Check your credentials and try again.": "ਆਪਣੇ ਪ੍ਰਮਾਣ ਪੱਤਰਾਂ ਦੀ ਜਾਂਚ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Incorrect password. Try again or use OTP login.": "ਗਲਤ ਪਾਸਵਰਡ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ OTP ਲੌਗਇਨ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "Google sign-in is not available in this app build. Please update the app and try again.": "ਇਸ ਐਪ ਬਿਲਡ ਵਿੱਚ Google ਸਾਈਨ-ਇਨ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਐਪ ਨੂੰ ਅੱਪਡੇਟ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Customer only": "ਸਿਰਫ਼ ਗਾਹਕ",
    "Google not configured": "Google ਕੌਂਫਿਗਰ ਨਹੀਂ ਕੀਤਾ ਗਿਆ",
    "Google did not return a sign-in token.": "Google ਨੇ ਸਾਈਨ-ਇਨ ਟੋਕਨ ਵਾਪਸ ਨਹੀਂ ਕੀਤਾ।",
    "Google Play Services is unavailable or needs an update on this device.": "Google Play ਸੇਵਾਵਾਂ ਉਪਲਬਧ ਨਹੀਂ ਹਨ ਜਾਂ ਇਸ ਡੀਵਾਈਸ 'ਤੇ ਅੱਪਡੇਟ ਦੀ ਲੋੜ ਹੈ।",
    "Google sign-in is already in progress.": "Google ਸਾਈਨ-ਇਨ ਪਹਿਲਾਂ ਹੀ ਪ੍ਰਗਤੀ ਵਿੱਚ ਹੈ।",
    "OTP verification failed. Please try again.": "OTP ਪੁਸ਼ਟੀਕਰਨ ਅਸਫਲ ਰਿਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Google Sign-In Failed": "Google ਸਾਈਨ-ਇਨ ਅਸਫਲ ਰਿਹਾ",
    "Please enter your district": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਦਾਖਲ ਕਰੋ",
    "Welcome Back": "ਵਾਪਸ ਸਵਾਗਤ",
    "Please enter your state": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਰਾਜ ਦਾਖਲ ਕਰੋ",
    "Registration Failed": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਸਫਲ ਰਹੀ",
    "Could not create account. Please try again.": "ਖਾਤਾ ਨਹੀਂ ਬਣਾਇਆ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Customers": "ਗਾਹਕ",
    "Login or create a new account": "ਲੌਗਇਨ ਕਰੋ ਜਾਂ ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ",
    "Please enter a valid 6-digit pincode": "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ 6-ਅੰਕਾਂ ਵਾਲਾ ਪਿਨਕੋਡ ਦਾਖਲ ਕਰੋ",
    "Please enter a valid email address without spaces": "ਕਿਰਪਾ ਕਰਕੇ ਖਾਲੀ ਥਾਂ ਤੋਂ ਬਿਨਾਂ ਇੱਕ ਵੈਧ ਈਮੇਲ ਪਤਾ ਦਾਖਲ ਕਰੋ",
    "Sending...": "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    "6-digit OTP": "6-ਅੰਕ ਦਾ OTP",
    "Back to Login": "ਲੌਗਇਨ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    "Trusted electrical products since 2000": "2000 ਤੋਂ ਭਰੋਸੇਯੋਗ ਬਿਜਲੀ ਉਤਪਾਦ",
    "Your full name": "ਤੁਹਾਡਾ ਪੂਰਾ ਨਾਮ",
    "Verify OTP first, then create your new password": "ਪਹਿਲਾਂ OTP ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ, ਫਿਰ ਆਪਣਾ ਨਵਾਂ ਪਾਸਵਰਡ ਬਣਾਓ",
    "Join SRV Electricals today": "ਅੱਜ ਹੀ SRV ਇਲੈਕਟ੍ਰੀਕਲਜ਼ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ",
    "Updating...": "ਅੱਪਡੇਟ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "optional": "ਵਿਕਲਪਿਕ",
    "4-digit OTP": "4-ਅੰਕ ਦਾ OTP",
    "your@email.com": "your@email.com",
    "Welcome back to SRV Electricals": "SRV ਇਲੈਕਟ੍ਰੀਕਲਸ ਵਿੱਚ ਵਾਪਸ ਸੁਆਗਤ ਹੈ",
    "Create a password": "ਇੱਕ ਪਾਸਵਰਡ ਬਣਾਓ",
    "Enter the OTP and verify before continuing to the remaining details.": "OTP ਦਾਖਲ ਕਰੋ ਅਤੇ ਬਾਕੀ ਵੇਰਵਿਆਂ ਨੂੰ ਜਾਰੀ ਰੱਖਣ ਤੋਂ ਪਹਿਲਾਂ ਪੁਸ਼ਟੀ ਕਰੋ।",
    "6-digit pincode": "6-ਅੰਕਾਂ ਵਾਲਾ ਪਿਨਕੋਡ",
    "Already have an account? ": "ਕੀ ਪਹਿਲਾਂ ਤੋਂ ਹੀ ਖਾਤਾ ਹੈ?",
    "Add the remaining details below to finish creating your account.": "ਆਪਣਾ ਖਾਤਾ ਬਣਾਉਣਾ ਪੂਰਾ ਕਰਨ ਲਈ ਹੇਠਾਂ ਬਾਕੀ ਵੇਰਵੇ ਸ਼ਾਮਲ ਕਰੋ।",
    "Sign up": "ਸਾਇਨ ਅਪ",
    "Referral Code": "ਰੈਫਰਲ ਕੋਡ",
    "Logging in...": "ਲੌਗਇਨ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...",
    "Don't have an account? ": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    "Creating...": "ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    "Cart": "ਕਾਰਟ",
    "Dealer Cart": "ਡੀਲਰ ਕਾਰਟ",
    "Counterboy Cart": "ਕਾਊਂਟਰਬੁਆਏ ਕਾਰਟ",
    "Review your selected products, adjust quantity and continue with enquiry.": "ਆਪਣੇ ਚੁਣੇ ਹੋਏ ਉਤਪਾਦਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ, ਮਾਤਰਾ ਨੂੰ ਵਿਵਸਥਿਤ ਕਰੋ ਅਤੇ ਪੁੱਛਗਿੱਛ ਜਾਰੀ ਰੱਖੋ।",
    "Customer Cart": "ਗਾਹਕ ਕਾਰਟ",
    "Total Qty": "ਕੁੱਲ ਮਾਤਰਾ",
    "Your cart is empty": "ਤੁਹਾਡਾ ਕਾਰਟ ਖਾਲੀ ਹੈ",
    "Browse categories, explore products and add items here for a cleaner enquiry flow.": "ਸ਼੍ਰੇਣੀਆਂ ਨੂੰ ਬ੍ਰਾਊਜ਼ ਕਰੋ, ਉਤਪਾਦਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ ਅਤੇ ਸਾਫ਼-ਸੁਥਰੀ ਪੁੱਛਗਿੱਛ ਦੇ ਪ੍ਰਵਾਹ ਲਈ ਇੱਥੇ ਆਈਟਮਾਂ ਸ਼ਾਮਲ ਕਰੋ।",
    "Browse Products": "ਉਤਪਾਦ ਬ੍ਰਾਊਜ਼ ਕਰੋ",
    "Save your favorite items here and enquire when you are ready.": "ਆਪਣੀਆਂ ਮਨਪਸੰਦ ਚੀਜ਼ਾਂ ਨੂੰ ਇੱਥੇ ਰੱਖਿਅਤ ਕਰੋ ਅਤੇ ਜਦੋਂ ਤੁਸੀਂ ਤਿਆਰ ਹੋਵੋ ਤਾਂ ਪੁੱਛਗਿੱਛ ਕਰੋ।",
    "No matching products": "ਕੋਈ ਮੇਲ ਖਾਂਦੇ ਉਤਪਾਦ ਨਹੀਂ ਹਨ",
    "Order Summary": "ਆਰਡਰ ਸੰਖੇਪ",
    "Try another product name or clear search.": "ਕੋਈ ਹੋਰ ਉਤਪਾਦ ਨਾਮ ਅਜ਼ਮਾਓ ਜਾਂ ਖੋਜ ਸਾਫ਼ ਕਰੋ।",
    "product": "ਉਤਪਾਦ",
    "Search products in cart": "ਕਾਰਟ ਵਿੱਚ ਉਤਪਾਦ ਖੋਜੋ",
    "Buy This Product": "ਇਹ ਉਤਪਾਦ ਖਰੀਦੋ",
    "item(s)": "ਆਈਟਮਾਂ",
    "Pay with Points": "ਪੁਆਇੰਟਾਂ ਨਾਲ ਭੁਗਤਾਨ ਕਰੋ",
    "UPI, cards & wallets": "UPI, ਕਾਰਡ ਅਤੇ ਵਾਲਿਟ",
    "points available": "ਅੰਕ ਉਪਲਬਧ ਹਨ",
    "Proceed to Checkout": "ਚੈੱਕਆਉਟ ਲਈ ਅੱਗੇ ਵਧੋ",
    "in cart": "ਕਾਰਟ ਵਿੱਚ",
    "Address required": "ਪਤਾ ਲੋੜੀਂਦਾ ਹੈ",
    "Razorpay secure payment": "Razorpay ਸੁਰੱਖਿਅਤ ਭੁਗਤਾਨ",
    "Address updated": "ਪਤਾ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ",
    "Cash on Delivery": "ਡਿਲਿਵਰੀ 'ਤੇ ਨਕਦ",
    "Pay when your order arrives": "ਤੁਹਾਡਾ ਆਰਡਰ ਆਉਣ 'ਤੇ ਭੁਗਤਾਨ ਕਰੋ",
    "Please enter your shipping address.": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਸ਼ਿਪਿੰਗ ਪਤਾ ਦਾਖਲ ਕਰੋ।",
    "Your order has been placed using points.": "ਤੁਹਾਡਾ ਆਰਡਰ ਪੁਆਇੰਟ ਵਰਤ ਕੇ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
    "but this order needs": "ਪਰ ਇਸ ਆਰਡਰ ਦੀ ਲੋੜ ਹੈ",
    "Your shipping address has been updated successfully.": "ਤੁਹਾਡਾ ਸ਼ਿਪਿੰਗ ਪਤਾ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "Minimum order amount": "ਘੱਟੋ-ਘੱਟ ਆਰਡਰ ਦੀ ਰਕਮ",
    "Cart item": "ਕਾਰਟ ਆਈਟਮ",
    "Payment not completed": "ਭੁਗਤਾਨ ਪੂਰਾ ਨਹੀਂ ਹੋਇਆ",
    "points deducted.": "ਅੰਕ ਕੱਟੇ ਗਏ।",
    "All cart products have been placed successfully with Cash on Delivery. You can track them from My Orders.": "ਸਾਰੇ ਕਾਰਟ ਉਤਪਾਦਾਂ ਨੂੰ ਕੈਸ਼ ਆਨ ਡਿਲੀਵਰੀ ਦੇ ਨਾਲ ਸਫਲਤਾਪੂਰਵਕ ਰੱਖਿਆ ਗਿਆ ਹੈ। ਤੁਸੀਂ ਉਹਨਾਂ ਨੂੰ ਮੇਰੇ ਆਦੇਸ਼ਾਂ ਤੋਂ ਟ੍ਰੈਕ ਕਰ ਸਕਦੇ ਹੋ।",
    "Online payment is available in the Android app.": "ਔਨਲਾਈਨ ਭੁਗਤਾਨ ਐਂਡਰਾਇਡ ਐਪ ਵਿੱਚ ਉਪਲਬਧ ਹੈ।",
    "Your order has been placed successfully with Cash on Delivery. You can track it from My Orders.": "ਕੈਸ਼ ਆਨ ਡਿਲੀਵਰੀ ਦੇ ਨਾਲ ਤੁਹਾਡਾ ਆਰਡਰ ਸਫਲਤਾਪੂਰਵਕ ਦਿੱਤਾ ਗਿਆ ਹੈ। ਤੁਸੀਂ ਇਸਨੂੰ ਮਾਈ ਆਰਡਰਸ ਤੋਂ ਟ੍ਰੈਕ ਕਰ ਸਕਦੇ ਹੋ।",
    "Checkout": "ਕਮਰਾ ਛੱਡ ਦਿਓ",
    "Payment received for all cart products. Your orders are confirmed and ready for processing.": "ਸਾਰੇ ਕਾਰਟ ਉਤਪਾਦਾਂ ਲਈ ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਹੋਇਆ। ਤੁਹਾਡੇ ਆਰਡਰ ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ ਹੈ ਅਤੇ ਪ੍ਰਕਿਰਿਆ ਲਈ ਤਿਆਰ ਹੈ।",
    "The payment could not be completed. Please try again.": "ਭੁਗਤਾਨ ਪੂਰਾ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    "Payment received. Your order has been confirmed and is ready for processing.": "ਭੁਗਤਾਨ ਪ੍ਰਾਪਤ ਹੋਇਆ। ਤੁਹਾਡੇ ਆਰਡਰ ਦੀ ਪੁਸ਼ਟੀ ਹੋ ​​ਗਈ ਹੈ ਅਤੇ ਪ੍ਰਕਿਰਿਆ ਲਈ ਤਿਆਰ ਹੈ।",
    "The payment was cancelled or could not be completed. No order has been confirmed and you have not been charged.": "ਭੁਗਤਾਨ ਰੱਦ ਕਰ ਦਿੱਤਾ ਗਿਆ ਸੀ ਜਾਂ ਪੂਰਾ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਸੇ ਆਰਡਰ ਦੀ ਪੁਸ਼ਟੀ ਨਹੀਂ ਕੀਤੀ ਗਈ ਹੈ ਅਤੇ ਤੁਹਾਡੇ ਤੋਂ ਕੋਈ ਖਰਚਾ ਨਹੀਂ ਲਿਆ ਗਿਆ ਹੈ।",
    "Payment failed": "ਭੁਗਤਾਨ ਅਸਫਲ ਰਿਹਾ",
    "Contact Info": "ਸੰਪਰਕ ਜਾਣਕਾਰੀ",
    "Review, choose payment, place order": "ਸਮੀਖਿਆ ਕਰੋ, ਭੁਗਤਾਨ ਚੁਣੋ, ਆਰਡਰ ਦਿਓ",
    "SECURE CHECKOUT": "ਸੁਰੱਖਿਅਤ ਚੈਕਆਉਟ",
    "1. Review": "1. ਸਮੀਖਿਆ ਕਰੋ",
    "Edit": "ਸੰਪਾਦਿਤ ਕਰੋ",
    "2. Delivery": "2. ਡਿਲਿਵਰੀ",
    "Enter your address": "ਆਪਣਾ ਪਤਾ ਦਰਜ ਕਰੋ",
    "3. Pay": "3. ਭੁਗਤਾਨ ਕਰੋ",
    "Shipping Address": "ਸ਼ਿਪਿੰਗ ਪਤਾ",
    "Edit shipping address": "ਸ਼ਿਪਿੰਗ ਪਤੇ ਦਾ ਸੰਪਾਦਨ ਕਰੋ",
    "PAYMENT": "ਭੁਗਤਾਨ",
    "Save Address": "ਪਤਾ ਸੇਵ ਕਰੋ",
    "Tap edit to update your delivery address.": "ਆਪਣਾ ਡਿਲੀਵਰੀ ਪਤਾ ਅੱਪਡੇਟ ਕਰਨ ਲਈ ਸੰਪਾਦਨ 'ਤੇ ਟੈਪ ਕਰੋ।",
    "Add another address": "ਕੋਈ ਹੋਰ ਪਤਾ ਸ਼ਾਮਲ ਕਰੋ",
    "Choose how you want to pay": "ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਕਿਵੇਂ ਭੁਗਤਾਨ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ",
    "COD": "ਸੀ.ਓ.ਡੀ",
    "Pay Online with Razorpay": "Razorpay ਨਾਲ ਔਨਲਾਈਨ ਭੁਗਤਾਨ ਕਰੋ",
    "Available": "ਉਪਲਬਧ ਹੈ",
    "UPI, cards, netbanking and wallets": "UPI, ਕਾਰਡ, ਨੈੱਟਬੈਂਕਿੰਗ ਅਤੇ ਵਾਲਿਟ",
    "Currently not supported": "ਵਰਤਮਾਨ ਵਿੱਚ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ",
    "FAST": "ਤੇਜ਼",
    "Not enough points": "ਕਾਫ਼ੀ ਅੰਕ ਨਹੀਂ ਹਨ",
    "PAYMENT METHOD": "ਭੁਗਤਾਨੇ ਦੇ ਢੰਗ",
    "Change": "ਬਦਲੋ",
    "Shipping": "ਸ਼ਿਪਿੰਗ",
    "POINTS": "ਪੁਆਇੰਟ",
    "Free": "ਮੁਫ਼ਤ",
    "Total": "ਕੁੱਲ",
    "Pay Securely": "ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਭੁਗਤਾਨ ਕਰੋ",
    "Place COD Order": "COD ਆਰਡਰ ਦਿਓ",
    "Enough for this order": "ਇਸ ਆਰਡਰ ਲਈ ਕਾਫ਼ੀ ਹੈ",
    "Item Total": "ਆਈਟਮ ਕੁੱਲ",
    "No videos yet": "ਅਜੇ ਤੱਕ ਕੋਈ ਵੀਡੀਓ ਨਹੀਂ",
    "Choose payment method": "ਭੁਗਤਾਨ ਵਿਧੀ ਚੁਣੋ",
    "OTP verified. Now create a new secure password.": "OTP ਦੀ ਪੁਸ਼ਟੀ ਕੀਤੀ ਗਈ। ਹੁਣ ਇੱਕ ਨਵਾਂ ਸੁਰੱਖਿਅਤ ਪਾਸਵਰਡ ਬਣਾਓ।",
    "Select a method before placing your order": "ਆਪਣਾ ਆਰਡਰ ਦੇਣ ਤੋਂ ਪਹਿਲਾਂ ਇੱਕ ਢੰਗ ਚੁਣੋ",
    "Videos will appear here once uploaded by SRV Team": "SRV ਟੀਮ ਦੁਆਰਾ ਅੱਪਲੋਡ ਕੀਤੇ ਜਾਣ ਤੋਂ ਬਾਅਦ ਵੀਡੀਓ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ",
    "videos": "ਵੀਡੀਓਜ਼",
    "visible": "ਦਿਖਾਈ ਦੇਣ ਵਾਲਾ",
    "Enter your registered mobile number. We will send an OTP to verify your account.": "ਆਪਣਾ ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ। ਅਸੀਂ ਤੁਹਾਡੇ ਖਾਤੇ ਦੀ ਪੁਸ਼ਟੀ ਕਰਨ ਲਈ ਇੱਕ OTP ਭੇਜਾਂਗੇ।",
    "SRV Videos": "SRV ਵੀਡੀਓਜ਼",
    "items": "ਆਈਟਮਾਂ",
    "Fresh Picks": "ਤਾਜ਼ਾ ਚੋਣ",
    "Now Showing": "ਹੁਣ ਦਿਖਾ ਰਿਹਾ ਹੈ",
    "Video Picks": "ਵੀਡੀਓ ਪਿਕਸ",
    "points.": "ਅੰਕ",
    "Explore smart product videos, quick reels, and simple explainers picked for everyday browsing.": "ਰੋਜ਼ਾਨਾ ਬ੍ਰਾਊਜ਼ਿੰਗ ਲਈ ਚੁਣੇ ਗਏ ਸਮਾਰਟ ਉਤਪਾਦ ਵੀਡੀਓ, ਤੇਜ਼ ਰੀਲਾਂ ਅਤੇ ਸਧਾਰਨ ਵਿਆਖਿਆਕਾਰਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ।",
    "pts.": "ਅੰਕ",
    "Professional Product Overview": "ਪੇਸ਼ੇਵਰ ਉਤਪਾਦ ਦੀ ਸੰਖੇਪ ਜਾਣਕਾਰੀ",
    "No videos in this category": "ਇਸ ਸ਼੍ਰੇਣੀ ਵਿੱਚ ਕੋਈ ਵੀਡੀਓ ਨਹੀਂ ਹਨ",
    "Switch category or wait for SRV Team uploads": "ਸ਼੍ਰੇਣੀ ਬਦਲੋ ਜਾਂ SRV ਟੀਮ ਅੱਪਲੋਡ ਦੀ ਉਡੀਕ ਕਰੋ",
    "No matching categories found": "ਕੋਈ ਮੇਲ ਖਾਂਦੀਆਂ ਸ਼੍ਰੇਣੀਆਂ ਨਹੀਂ ਲੱਭੀਆਂ",
    "Redemption Requested!": "ਰੀਡੈਂਪਸ਼ਨ ਦੀ ਬੇਨਤੀ ਕੀਤੀ ਗਈ!",
    "Redeem your SRV rewards": "ਆਪਣੇ SRV ਇਨਾਮ ਰੀਡੀਮ ਕਰੋ",
    "Use your earned points to claim gifts, offers, and customer rewards from one place.": "ਇੱਕ ਥਾਂ ਤੋਂ ਤੋਹਫ਼ੇ, ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਗਾਹਕ ਇਨਾਮਾਂ ਦਾ ਦਾਅਵਾ ਕਰਨ ਲਈ ਆਪਣੇ ਕਮਾਏ ਪੁਆਇੰਟਾਂ ਦੀ ਵਰਤੋਂ ਕਰੋ।",
    "Counter Boy Account": "ਕਾਊਂਟਰ ਬੁਆਏ ਖਾਤਾ",
    "Tap to view your details": "ਆਪਣੇ ਵੇਰਵੇ ਦੇਖਣ ਲਈ ਟੈਪ ਕਰੋ",
    "Scanned At": "'ਤੇ ਸਕੈਨ ਕੀਤਾ ਗਿਆ",
    "Tap to return to profile card": "ਪ੍ਰੋਫਾਈਲ ਕਾਰਡ 'ਤੇ ਵਾਪਸ ਜਾਣ ਲਈ ਟੈਪ ਕਰੋ",
    "Save cancelled": "ਸੁਰੱਖਿਅਤ ਕਰੋ ਰੱਦ",
    "Download failed": "ਡਾਊਨਲੋਡ ਅਸਫਲ ਰਿਹਾ",
    "PDF saved": "PDF ਸੁਰੱਖਿਅਤ ਕੀਤੀ ਗਈ",
    "Folder not selected.": "ਫੋਲਡਰ ਨਹੀਂ ਚੁਣਿਆ ਗਿਆ।",
    "Save profile card PDF": "ਪ੍ਰੋਫਾਈਲ ਕਾਰਡ PDF ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    "Profile card PDF saved to your selected device folder.": "ਪ੍ਰੋਫਾਈਲ ਕਾਰਡ PDF ਨੂੰ ਤੁਹਾਡੇ ਚੁਣੇ ਗਏ ਡਿਵਾਈਸ ਫੋਲਡਰ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ ਹੈ।",
    "Saved in local files:": "ਸਥਾਨਕ ਫਾਈਲਾਂ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ:",
    "Open Website": "ਵੈੱਬਸਾਈਟ ਖੋਲ੍ਹੋ",
    "Unable to create the profile card PDF right now.": "ਇਸ ਸਮੇਂ ਪ੍ਰੋਫਾਈਲ ਕਾਰਡ PDF ਬਣਾਉਣ ਵਿੱਚ ਅਸਮਰੱਥ।",
    "Add": "ਸ਼ਾਮਲ ਕਰੋ",
    "Points can only be transferred to another": "ਪੁਆਇੰਟ ਸਿਰਫ਼ ਦੂਜੇ ਨੂੰ ਟ੍ਰਾਂਸਫਰ ਕੀਤੇ ਜਾ ਸਕਦੇ ਹਨ",
    "Points transfer is available only between users with the same role.": "ਪੁਆਇੰਟ ਟ੍ਰਾਂਸਫਰ ਸਿਰਫ਼ ਇੱਕੋ ਭੂਮਿਕਾ ਵਾਲੇ ਉਪਭੋਗਤਾਵਾਂ ਵਿਚਕਾਰ ਉਪਲਬਧ ਹੈ।",
    "When electrician points are redeemed, the dealer bonus is credited automatically:": "ਜਦੋਂ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਪੁਆਇੰਟ ਰੀਡੀਮ ਕੀਤੇ ਜਾਂਦੇ ਹਨ, ਤਾਂ ਡੀਲਰ ਬੋਨਸ ਆਪਣੇ ਆਪ ਹੀ ਕ੍ਰੈਡਿਟ ਹੋ ਜਾਂਦਾ ਹੈ:",
    "Auto Bonus": "ਆਟੋ ਬੋਨਸ",
    "of the points redeemed by any electrician will be credited to your dealer wallet. 1 point = 1 INR, and you can withdraw it directly to your bank account.": "ਕਿਸੇ ਵੀ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਦੁਆਰਾ ਰੀਡੀਮ ਕੀਤੇ ਪੁਆਇੰਟਾਂ ਵਿੱਚੋਂ ਤੁਹਾਡੇ ਡੀਲਰ ਵਾਲੇਟ ਵਿੱਚ ਕ੍ਰੈਡਿਟ ਕੀਤਾ ਜਾਵੇਗਾ। 1 ਪੁਆਇੰਟ = 1 INR, ਅਤੇ ਤੁਸੀਂ ਇਸਨੂੰ ਸਿੱਧੇ ਆਪਣੇ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਕਢਵਾ ਸਕਦੇ ਹੋ।",
    "more to reach the minimum order amount.": "ਘੱਟੋ-ਘੱਟ ਆਰਡਰ ਦੀ ਰਕਮ ਤੱਕ ਪਹੁੰਚਣ ਲਈ ਹੋਰ।",
    "Please increase quantity. The minimum order amount is": "ਕਿਰਪਾ ਕਰਕੇ ਮਾਤਰਾ ਵਧਾਓ। ਘੱਟੋ-ਘੱਟ ਆਰਡਰ ਦੀ ਰਕਮ ਹੈ"
  }
};
