export type Screen =
  | 'home'
  | 'product'
  | 'play'
  | 'categories'
  | 'cart'
  | 'checkout'
  | 'electricians'
  | 'call_electrician'
  | 'rewards'
  | 'profile'
  | 'wallet'
  | 'notification'
  | 'scan'
  | 'dealer_tier'
  | 'electrician_tier'
  | 'bank_details'
  | 'transfer_points'
  | 'dealer_bonus'
  | 'support';
export type UserRole = 'dealer' | 'electrician' | 'user' | 'counterboy';
